main.go
Update import path to the new github org `terraform-providers/`
=> Update import path

main.go
=> fmt main.go

website/docs/r/rds_instance_v1.html.markdown
This changes the region and remove unsupported db type.
=> Update rds website docs

flexibleengine/resource_flexibleengine_elb_backend.go
=> Fix ELB backend issue

flexibleengine/data_source_flexibleengine_images_image_v2.go, flexibleengine/data_source_flexibleengine_images_image_v2_test.go, flexibleengine/data_source_flexibleengine_vpc_route_ids_v2_test.go, flexibleengine/data_source_flexibleengine_vpc_subnet_ids_v1_test.go, flexibleengine/import_flexibleengine_dns_recordset_v2_test.go, flexibleengine/import_flexibleengine_images_image_v2_test.go, flexibleengine/import_flexibleengine_networking_floatingip_v2_test.go, flexibleengine/import_flexibleengine_networking_secgroup_rule_v2_test.go, flexibleengine/import_flexibleengine_vpc_peering_connection_v2_test.go, flexibleengine/import_flexibleengine_vpc_route_test.go, flexibleengine/import_flexibleengine_vpc_subnet_v1_test.go, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_images_image_v2.go, flexibleengine/resource_flexibleengine_images_image_v2_test.go, flexibleengine/resource_flexibleengine_s3_bucket_test.go, flexibleengine/resource_flexibleengine_vpc_peering_connection_v2_test.go, flexibleengine/resource_flexibleengine_vpc_route_v2_test.go, flexibleengine/resource_flexibleengine_vpc_v1_test.go, website/docs/d/images_image_v2.html.markdown, website/docs/r/images_image_v2.html.markdown, website/flexibleengine.erb
This adds images services support to flexibleengine provider.
=> Add image resource support

README.md, flexibleengine/config.go, vendor/github.com/huaweicloud/golangsdk/auth_aksk_options.go, vendor/github.com/huaweicloud/golangsdk/openstack/client.go, vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/projects/doc.go, vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/projects/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/projects/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/projects/urls.go, vendor/vendor.json
Currently, when using AK/SK authentication, users have to configuration tenant id, it is not an easy job.
this PR try to add tenant name as an optional config.
=> Add TenantName configuration when AKSK authentication

flexibleengine/resource_flexibleengine_sfs_file_system_v2.go
=> fixes #39 of sfs ForceNew without config change

flexibleengine/config.go, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_dws_cluster_v1.go, flexibleengine/resource_flexibleengine_dws_cluster_v1_test.go, vendor/github.com/huaweicloud/golangsdk/openstack/client.go, vendor/github.com/huaweicloud/golangsdk/openstack/dws/cluster/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/dws/cluster/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/dws/cluster/urls.go, vendor/vendor.json, website/docs/r/dws_cluster_v1.html.markdown, website/flexibleengine.erb
--- PASS: TestDWSClusterBasic (1381.04s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 1381.048s
=> add resource of dws cluster

examples/vbs.tf, flexibleengine/config.go, flexibleengine/data_source_flexibleengine_vbs_backup_policy_v2.go, flexibleengine/data_source_flexibleengine_vbs_backup_policy_v2_test.go, flexibleengine/data_source_flexibleengine_vbs_backup_v2.go, flexibleengine/data_source_flexibleengine_vbs_backup_v2_test.go, flexibleengine/import_flexibleengine_vbs_backup_policy_v2_test.go, flexibleengine/import_flexibleengine_vbs_backup_v2_test.go, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_vbs_backup_policy_v2.go, flexibleengine/resource_flexibleengine_vbs_backup_policy_v2_test.go, flexibleengine/resource_flexibleengine_vbs_backup_v2.go, flexibleengine/resource_flexibleengine_vbs_backup_v2_test.go, flexibleengine/validators.go, vendor/github.com/huaweicloud/golangsdk/openstack/client.go, vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/backups/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/backups/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/backups/results_job.go, vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/backups/urls.go, vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/policies/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/policies/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/policies/urls.go, vendor/vendor.json, website/docs/d/vbs_backup_policy_v2.html.markdown, website/docs/d/vbs_backup_v2.html.markdown, website/docs/r/vbs_backup_policy_v2.html.markdown, website/docs/r/vbs_backup_v2.html.markdown, website/flexibleengine.erb
This PR adds a capability to manage Flexibleengine VBS Backup and Policy service.
=> Add VBS Backup and Policy service

.travis.yml, GNUmakefile, website/docs/d/images_image_v2.html.markdown, website/docs/r/mrs_job_v1.html.markdown
Previously:
```
$ make website-test
ifeq (,/Users/bflad/go/src/github.com/hashicorp/terraform-website)
/bin/sh: -c: line 0: syntax error near unexpected token `,/Users/bflad/go/src/github.com/hashicorp/terraform-website'
/bin/sh: -c: line 0: `ifeq (,/Users/bflad/go/src/github.com/hashicorp/terraform-website)'
make: *** [website-test] Error 2
$ make website-test
...
Found 1 broken link.
https://www.terraform.io/docs/providers/flexibleengine/d/images_image_v2.html
```
Now:
```
$ make website-test
...
Found no broken links.
```
=> docs: Frontmatter fixes and enable website-test Make target in TravisCI

examples/antiddos.tf, flexibleengine/config.go, flexibleengine/import_flexibleengine_antiddos_v1_test.go, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_antiddos_v1.go, flexibleengine/resource_flexibleengine_antiddos_v1_test.go, flexibleengine/validators.go, vendor/github.com/huaweicloud/golangsdk/openstack/antiddos/v1/antiddos/API-cn.md, vendor/github.com/huaweicloud/golangsdk/openstack/antiddos/v1/antiddos/API-en.md, vendor/github.com/huaweicloud/golangsdk/openstack/antiddos/v1/antiddos/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/antiddos/v1/antiddos/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/antiddos/v1/antiddos/url.go, vendor/github.com/huaweicloud/golangsdk/openstack/client.go, vendor/vendor.json, website/docs/r/antiddos_v1.html.markdown, website/flexibleengine.erb
This PR adds a capability to manage FlexibleEngine Antiddos service.
=> Add Antiddos service

flexibleengine/resource_flexibleengine_dns_recordset_v2.go, flexibleengine/resource_flexibleengine_dns_recordset_v2_test.go, flexibleengine/resource_flexibleengine_dns_zone_v2.go, flexibleengine/resource_flexibleengine_dns_zone_v2_test.go, flexibleengine/types.go, flexibleengine/util.go, website/docs/r/dns_recordset_v2.html.markdown, website/docs/r/dns_zone_v2.html.markdown
This PR is to sync dns from huaweicloud to this repository. the main target is to fix the zone type issue which cannot work when set dns zone type as PRIMARY.
After this change the zone type will change to support ```public/private```.
The acc test results:
=== RUN   TestAccDNSV2Zone_basic
--- PASS: TestAccDNSV2Zone_basic (47.11s)
=== RUN   TestAccDNSV2Zone_readTTL
--- PASS: TestAccDNSV2Zone_readTTL (48.61s)
=== RUN   TestAccDNSV2Zone_timeout
--- PASS: TestAccDNSV2Zone_timeout (45.50s)
--- PASS: TestAccDNSV2RecordSet_basic (137.95s)
=== RUN   TestAccDNSV2RecordSet_readTTL
--- PASS: TestAccDNSV2RecordSet_readTTL (72.03s)
=== RUN   TestAccDNSV2RecordSet_timeout
--- PASS: TestAccDNSV2RecordSet_timeout (72.17s)
=> Fix dns doc

flexibleengine/data_source_flexibleengine_cce_cluster_v3.go, flexibleengine/resource_flexibleengine_cce_cluster_v3.go, website/docs/d/cce_cluster_v3.html.md, website/docs/r/cce_cluster_v3.html.md
=> Clean up unneeded cce cluster attributes

flexibleengine/resource_flexibleengine_cce_cluster_v3.go, flexibleengine/resource_flexibleengine_cce_cluster_v3_test.go
=> Add a default value for CCE cluster version

flexibleengine/resource_flexibleengine_dns_zone_v2.go, website/docs/r/dns_zone_v2.html.markdown
=> Add support for attaching multi routers to dns zone

flexibleengine/compute_interface_attach_v2.go, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_compute_interface_attach_v2.go, flexibleengine/resource_flexibleengine_compute_interface_attach_v2_test.go, vendor/github.com/huaweicloud/golangsdk/openstack/compute/v2/extensions/attachinterfaces/doc.go, vendor/github.com/huaweicloud/golangsdk/openstack/compute/v2/extensions/attachinterfaces/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/compute/v2/extensions/attachinterfaces/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/compute/v2/extensions/attachinterfaces/urls.go, vendor/modules.txt, website/docs/r/compute_interface_attach_v2.html.markdown, website/flexibleengine.erb
=> Add compute interface attach support

flexibleengine/resource_flexibleengine_blockstorage_volume_v2.go, flexibleengine/resource_flexibleengine_blockstorage_volume_v2_test.go, vendor/github.com/huaweicloud/golangsdk/openstack/blockstorage/extensions/volumeactions/doc.go, vendor/github.com/huaweicloud/golangsdk/openstack/blockstorage/extensions/volumeactions/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/blockstorage/extensions/volumeactions/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/blockstorage/extensions/volumeactions/urls.go, vendor/modules.txt, website/docs/r/blockstorage_volume_v2.html.markdown
=> Add volume extending support

website/docs/r/as_group_v1.html.markdown
=> Update as_group documentation

flexibleengine/config.go, flexibleengine/golangsdk_utils.go, flexibleengine/resource_flexibleengine_compute_instance_v2.go, flexibleengine/resource_flexibleengine_compute_instance_v2_test.go, flexibleengine/resource_flexibleengine_ecs_auto_recovery_v1.go, vendor/github.com/huaweicloud/golangsdk/openstack/ecs/v1/auto_recovery/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/ecs/v1/auto_recovery/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/ecs/v1/auto_recovery/urls.go, vendor/modules.txt, website/docs/r/compute_instance_v2.html.markdown
=> Add instance auto_recovery support

website/docs/index.html.markdown
=> Update docs for authentication

website/docs/r/lb_listener_v2.html.markdown
=> Fix LB Listener docs

flexibleengine/resource_flexibleengine_as_group_v1.go, flexibleengine/resource_flexibleengine_as_group_v1_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/autoscaling/v1/groups/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/autoscaling/v1/groups/results.go, vendor/modules.txt, website/docs/r/as_group_v1.html.markdown
=> Add lbaas_listeners support to as_group

flexibleengine/data_source_flexibleengine_compute_bms_nic_v2_test.go, flexibleengine/data_source_flexibleengine_compute_bms_server_v2_test.go, flexibleengine/data_source_flexibleengine_csbs_backup_policy_v1_test.go, flexibleengine/data_source_flexibleengine_csbs_backup_v1_test.go, flexibleengine/resource_flexibleengine_blockstorage_volume_v2_test.go, flexibleengine/resource_flexibleengine_compute_bms_server_v2_test.go, flexibleengine/resource_flexibleengine_compute_instance_v2_test.go, flexibleengine/resource_flexibleengine_csbs_backup_policy_v1_test.go, flexibleengine/resource_flexibleengine_csbs_backup_v1_test.go, flexibleengine/resource_flexibleengine_nat_dnat_rule_v2_test.go, website/docs/r/blockstorage_volume_v2.html.markdown, website/docs/r/compute_bms_server_v2.html.markdown, website/docs/r/compute_instance_v2.html.markdown
This updates the example code and documentation to reflect how arguments/attributes of TypeMap should now be declared.
=> Terraform v0.12 TypeMap Fixes

flexibleengine/resource_flexibleengine_lb_monitor_v2.go, flexibleengine/resource_flexibleengine_lb_monitor_v2_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/monitors/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/monitors/results.go, vendor/modules.txt, website/docs/r/lb_monitor_v2.html.markdown
=> Add port option to lb_monitor

flexibleengine/data_source_flexibleengine_dns_zone_v2.go, flexibleengine/data_source_flexibleengine_dns_zone_v2_test.go, flexibleengine/provider.go, website/docs/d/dns_zone_v2.html.markdown, website/flexibleengine.erb
=> Add data source for dns_zone

flexibleengine/data_source_flexibleengine_blockstorage_volume_v2.go, flexibleengine/data_source_flexibleengine_blockstorage_volume_v2_test.go, flexibleengine/provider.go
=> Add blockstorage_volume data source

flexibleengine/resource_flexibleengine_blockstorage_volume_v2.go, flexibleengine/resource_flexibleengine_blockstorage_volume_v2_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/auth_aksk_options.go, vendor/github.com/huaweicloud/golangsdk/openstack/blockstorage/v2/volumes/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/nodes/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/client.go, vendor/github.com/huaweicloud/golangsdk/openstack/csbs/v1/policies/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/endpoint_location.go, vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/cluster/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/cluster/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/snatrules/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/snatrules/results.go, vendor/github.com/huaweicloud/golangsdk/provider_client.go, vendor/modules.txt, website/docs/r/blockstorage_volume_v2.html.markdown
=> Add Multiattach support for volume

website/docs/r/compute_instance_v2.html.markdown
=> Update instance boot_index description to make it more clear

flexibleengine/resource_flexibleengine_csbs_backup_policy_v1.go, flexibleengine/resource_flexibleengine_csbs_backup_policy_v1_test.go
=> Fix CSBS backup policy

flexibleengine/data_source_flexibleengine_cce_cluster_v3.go, flexibleengine/resource_flexibleengine_cce_cluster_v3.go, website/docs/d/cce_cluster_v3.html.md, website/docs/r/cce_cluster_v3.html.md
=> Add endpoints to CCE cluster

flexibleengine/resource_flexibleengine_cce_node_v3.go, website/docs/r/cce_nodes_v3.html.md
=> Add public_ip/private_ip to CCE node

flexibleengine/resource_flexibleengine_compute_floatingip_v2.go, flexibleengine/resource_flexibleengine_networking_floatingip_v2.go, website/docs/r/compute_floatingip_v2.html.markdown, website/docs/r/networking_floatingip_v2.html.markdown
=> Add default value for floating_ip pool

flexibleengine/resource_flexibleengine_lb_listener_v2_test.go
=> Add lb_listener acc test for TERMINATED_HTTPS

website/docs/r/lb_listener_v2.html.markdown
=> Add example for lb_listener with TERMINATED_HTTPS

website/docs/d/cce_node_v3.html.md, website/flexibleengine.erb
=> Fix cce_node datasource naming issue

flexibleengine/resource_flexibleengine_cce_cluster_v3.go, flexibleengine/resource_flexibleengine_cce_cluster_v3_test.go, website/docs/r/cce_cluster_v3.html.md
=> Add authentication mode support for CCE cluster

flexibleengine/resource_flexibleengine_cce_cluster_v3.go, flexibleengine/resource_flexibleengine_cce_node_v3.go, flexibleengine/resource_flexibleengine_cce_node_v3_test.go, website/docs/r/cce_nodes_v3.html.md
=> Add OS parameters to CCE node

flexibleengine/data_source_flexibleengine_cce_cluster_v3.go, flexibleengine/data_source_flexibleengine_cce_cluster_v3_test.go, flexibleengine/resource_flexibleengine_cce_cluster_v3.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/results.go, vendor/modules.txt, website/docs/d/cce_cluster_v3.html.md, website/docs/r/cce_cluster_v3.html.md
=> Add security_group_id to CCE cluster

flexibleengine/resource_flexibleengine_dcs_instance_v1.go, flexibleengine/resource_flexibleengine_dcs_instance_v1_test.go, website/docs/r/dcs_instance_v1.html.markdown
=> Fix DCS parameters issue for single node

flexibleengine/config.go, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_dds_instance_v3.go, flexibleengine/resource_flexibleengine_dds_instance_v3_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/client.go, vendor/github.com/huaweicloud/golangsdk/openstack/dds/v3/instances/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/dds/v3/instances/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/dds/v3/instances/urls.go, vendor/modules.txt
=> Add DDS instance resource

flexibleengine/data_source_flexibleengine_cce_node_ids_v3.go, flexibleengine/data_source_flexibleengine_cce_node_ids_v3_test.go, flexibleengine/provider.go, website/docs/d/cce_node_ids_v3.html.md, website/flexibleengine.erb
=> Add CCE node ids data source

flexibleengine/resource_flexibleengine_lb_monitor_v2.go
=> Fix lb monitor expected_codes issue

flexibleengine/diff_suppress_funcs.go, flexibleengine/resource_flexibleengine_rds_instance_v3.go, flexibleengine/resource_flexibleengine_rds_instance_v3_test.go
=> Fix RDS instance v3 db version issue

website/docs/r/rds_instance_v3.html.markdown
=> fixing RDS Microsoft SQL Server example values

flexibleengine/diff_suppress_funcs.go, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_lb_whitelist_v2.go, flexibleengine/resource_flexibleengine_lb_whitelist_v2_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/whitelists/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/whitelists/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/whitelists/urls.go, vendor/modules.txt, website/docs/r/lb_whitelist_v2.html.markdown, website/flexibleengine.erb
=> Add LB Whitelist

flexibleengine/resource_flexibleengine_cce_cluster_v3.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/urls.go, vendor/modules.txt, website/docs/r/cce_cluster_v3.html.md
=> Add certificates information to cce cluster

flexibleengine/resource_flexibleengine_cce_cluster_v3.go, flexibleengine/resource_flexibleengine_cce_cluster_v3_test.go, website/docs/r/cce_cluster_v3.html.md
This adds EIP support when creating a CCE cluster.
=> Add eip support for cce cluster

website/docs/r/cce_cluster_v3.html.md
=> fixing attribute reference,

flexibleengine/data_source_flexibleengine_lb_certificates_v2.go, flexibleengine/data_source_flexibleengine_lb_certificates_v2_test.go, flexibleengine/provider.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/urls.go, vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/certificates/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/certificates/results.go, vendor/modules.txt, website/docs/d/lb_certificate_v2.html.markdown, website/flexibleengine.erb
=> Add LB Certificate data source

flexibleengine/resource_flexibleengine_cce_node_v3.go
set annotations and labels to Computed
Fixed #285
=> Add Computed on annotations and labels for cce_node

flexibleengine/config.go, flexibleengine/data_source_flexibleengine_sdrs_domain_v1.go, flexibleengine/data_source_flexibleengine_sdrs_domain_v1_test.go, flexibleengine/provider.go, flexibleengine/provider_test.go, flexibleengine/resource_flexibleengine_sdrs_protectiongroup_v1.go, flexibleengine/resource_flexibleengine_sdrs_protectiongroup_v1_test.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/domains/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/domains/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/domains/urls.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/protectiongroups/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/protectiongroups/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/protectiongroups/results_job.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/protectiongroups/urls.go, vendor/modules.txt, website/docs/d/sdrs_domain_v1.html.markdown, website/docs/r/sdrs_protectiongroup_v1.html.markdown, website/flexibleengine.erb
=> Add SDRS resource support

flexibleengine/provider.go, flexibleengine/resource_flexibleengine_sdrs_drill.go, flexibleengine/resource_flexibleengine_sdrs_drill_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/drill/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/drill/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/drill/results_job.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/drill/urls.go, vendor/modules.txt, website/docs/r/sdrs_drill_v1.html.markdown, website/flexibleengine.erb
Add flexibleengine_sdrs_drill_v1 resource and docs
=> Add flexibleengine_sdrs_drill_v1 resource and docs

website/docs/index.html.markdown
=> Fix Provider docs with token issue

flexibleengine/resource_flexibleengine_cce_node_v3.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/nodes/results.go, vendor/modules.txt, website/docs/r/cce_nodes_v3.html.md
=> Add CCE node preinstall/postinstall script support

website/docs/r/vpc_eip_v1.html.markdown
=> Update max EIP bandwidth

flexibleengine/resource_flexibleengine_cce_node_v3.go, flexibleengine/resource_flexibleengine_nat_snat_rule_v2.go, website/docs/r/cce_nodes_v3.html.md, website/docs/r/nat_snat_rule_v2.html.markdown
This PR fixes two bugs:
* Support cidr and source_type parameters for snat rule; #303 
* Make preinstall and postinstall support strings without Base64 encoding; #297
=> Bugfix for cce_node and snat_rule

flexibleengine/config.go, flexibleengine/provider.go, flexibleengine/provider_test.go, flexibleengine/resource_flexibleengine_obs_bucket.go, flexibleengine/resource_flexibleengine_obs_bucket_object.go, flexibleengine/resource_flexibleengine_obs_bucket_object_test.go, flexibleengine/resource_flexibleengine_obs_bucket_test.go, flexibleengine/resource_flexibleengine_s3_bucket.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/auth.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/client.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/conf.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/const.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/convert.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/error.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/http.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/log.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/model.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/temporary.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/trait.go, vendor/github.com/huaweicloud/golangsdk/openstack/obs/util.go, vendor/modules.txt, website/docs/r/obs_bucket.html.markdown, website/docs/r/obs_bucket_object.html.markdown, website/flexibleengine.erb
Add obs_bucket and obs_bucket_object resource with OBS SDK
=> Add obs_bucket and obs_bucket_object resource

flexibleengine/resource_flexibleengine_mrs_cluster_v1.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/cluster/requests.go, vendor/modules.txt, website/docs/r/mrs_cluster_v1.html.markdown
=> pass cluster_type through to mrs API even it set to 0

flexibleengine/resource_flexibleengine_dds_instance_v3_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/dds/v3/instances/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/policies/requests.go, vendor/modules.txt
=> Fix DDS instance create issue

flexibleengine/resource_flexibleengine_cce_node_v3.go
This removes the Computed from annotations and lables arguments.
=> Fix annotations and lables of CCE node

website/docs/r/rds_instance_v3.html.markdown
=> fix document bug for rds instance v3

flexibleengine/resource_flexibleengine_dcs_instance_v1.go, flexibleengine/resource_flexibleengine_dds_instance_v3.go, flexibleengine/resource_flexibleengine_mls_instance_v1.go, flexibleengine/resource_flexibleengine_rds_instance_v3.go
From terraform-provider-huaweicloud patch
commit：d2b69a8ce7cfe867386cb718d0ce67778e4fa98b
=> set sensitive flag for password parameter

flexibleengine/resource_flexibleengine_dds_instance_v3.go, website/docs/r/dds_instance_v3.html.markdown
From terraform-provider-huaweicloud patch
commit：a08d401599a97666f65c7022f254f4b6a584625d
=> add port and nodes attributes for dds instance

flexibleengine/config.go, website/docs/index.html.markdown
* improvement on LoadAndValidate for config
* make OS_DEBUG together with TF_LOG
=> improvement on for flexibleengine config

flexibleengine/provider.go, flexibleengine/provider_test.go, flexibleengine/resource_flexibleengine_identity_agency_v3.go, flexibleengine/resource_flexibleengine_identity_agency_v3_test.go, vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/agency/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/agency/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/agency/urls.go, vendor/modules.txt, website/docs/r/identity_agency_v3.html.markdown, website/flexibleengine.erb
Manages an agency resource within FlexibleEngine.
=> Add identity agency resource and docs

flexibleengine/custom_functions.go, flexibleengine/resource_flexibleengine_css_cluster_v1.go, flexibleengine/resource_flexibleengine_css_cluster_v1_test.go, website/docs/r/css_cluster_v1.html.markdown
- rename expect_node_num to node_number
- remove Content-Type in request headers of get API
- update test acc
=> improvement on  css cluster resource

flexibleengine/resource_flexibleengine_dcs_instance_v1.go, flexibleengine/resource_flexibleengine_dcs_instance_v1_test.go, website/docs/r/dcs_instance_v1.html.markdown
$ make testacc TEST=./flexibleengine/ TESTARGS='-run TestAccDcsInstancesV1_basic'
TF_ACC=1 go test ./flexibleengine/ -v -run TestAccDcsInstancesV1_basic -timeout 720m
=== RUN   TestAccDcsInstancesV1_basic
--- PASS: TestAccDcsInstancesV1_basic (540.45s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 540.655s
=> Optimize DCS input parameters

flexibleengine/provider.go, flexibleengine/resource_flexibleengine_mrs_hybrid_cluster_v1.go, flexibleengine/resource_flexibleengine_mrs_hybrid_cluster_v1_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/cluster/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/cluster/results.go, vendor/modules.txt
```
$ make testacc TEST=./flexibleengine TESTARGS='-run TestAccMRSV1HybridCluster_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccMRSV1HybridCluster_basic -timeout 720m
=== RUN   TestAccMRSV1HybridCluster_basic
--- PASS: TestAccMRSV1HybridCluster_basic (1326.92s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 1326.930s
```
fixes #275
=> Add mrs hybrid cluster resource

website/docs/r/css_cluster_v1.html.markdown
=> update docs of css cluster resource

flexibleengine/resource_flexibleengine_css_cluster_v1.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/css/v1/snapshots/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/css/v1/snapshots/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/css/v1/snapshots/urls.go, vendor/modules.txt, website/docs/r/css_cluster_v1.html.markdown
we can update `backup_strategy` depend on golangsdk@bef093aea95e
=> Make backup_strategy updatable in css cluster

flexibleengine/compute_instance_v2_networking.go
=> [compute] get instance nics within same network name

flexibleengine/config.go, website/docs/index.html.markdown
if token, aksk and password are set simultaneously, then it will authenticate in the order of Token, Password and AKSK.
=> make authenticate in the order of token, password and aksk

website/docs/r/networking_port_v2.html.markdown
=> update description of allowed_address_pairs in networking port resource

flexibleengine/resource_flexibleengine_ces_alarmrule.go, flexibleengine/resource_flexibleengine_ces_alarmrule_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/cloudeyeservice/alarmrule/requests.go, vendor/modules.txt, website/docs/r/ces_alarmrule.html.markdown, website/flexibleengine.erb
fixes #376 
sync the huaweicloud/golangsdk#297 and clean up the codes.
=> improve for ces alarmrule

flexibleengine/config.go, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_sfs_turbo.go, flexibleengine/resource_flexibleengine_sfs_turbo_test.go, vendor/github.com/huaweicloud/golangsdk/openstack/sfs_turbo/v1/shares/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/sfs_turbo/v1/shares/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/sfs_turbo/v1/shares/urls.go, vendor/modules.txt, website/docs/r/sfs_turbo.html.markdown, website/flexibleengine.erb
=> Add sfs turbo resource and docs

flexibleengine/provider.go, flexibleengine/resource_flexibleengine_network_acl.go, flexibleengine/resource_flexibleengine_network_acl_rule.go, flexibleengine/resource_flexibleengine_network_acl_rule_test.go, flexibleengine/resource_flexibleengine_network_acl_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/policies/requests.go, vendor/modules.txt, website/docs/r/network_acl.html.markdown, website/docs/r/network_acl_rule.html.markdown, website/flexibleengine.erb
=> support network acl resources and docs

website/docs/r/css_cluster_v1.html.markdown
update description of `availability_zone`
=> update css_cluster docs

flexibleengine/resource_flexibleengine_cce_cluster_v3.go, flexibleengine/resource_flexibleengine_cce_node_v3.go
This bumps the Create/Delete timeouts for CCE cluster and node.
=> Bump timeout for CCE resources

flexibleengine/resource_flexibleengine_cce_node_v3.go, website/docs/r/cce_nodes_v3.html.md
=> resource cce node add param 'taints'

flexibleengine/resource_flexibleengine_lb_listener_v2.go
=> Add UDP support to protocol of lb_listener

flexibleengine/compute_bms_v2_server_addresses.go, flexibleengine/compute_instance_v2_networking.go
there is no necessary to support nova-network service as we can get networking informations by Neutron, so clean up it.
=> unsupport nova-network service

flexibleengine/compute_util.go, flexibleengine/resource_flexibleengine_compute_bms_server_v2.go, flexibleengine/resource_flexibleengine_compute_instance_v2.go, flexibleengine/resource_flexibleengine_drs_replication_v2.go
as the schemas of compute and bms are similar, we can merge some
methdods.
=> clean up codes for compute instance and bms

.travis.yml, GNUmakefile
github.com/hashicorp/terraform-website has removed `website-provider-test`
with 6d41be43, let's trim it in provider.
=> remove make website-test

website/docs/r/lb_l7policy_v2.html.markdown, website/docs/r/lb_l7rule_v2.html.markdown, website/docs/r/lb_monitor_v2.html.markdown
the flexibleengine_lb_l7policy_v2 action does not support "REDIRECT_TO_URL", let's fix it.
also update the format of usage.
=> update usage of lb resource

CHANGELOG.md
=> Update CHANGELOG for v1.18.1

flexibleengine/resource_flexibleengine_dds_instance_v3.go, flexibleengine/resource_flexibleengine_dds_instance_v3_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/dds/v3/instances/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/dds/v3/instances/results.go, vendor/modules.txt, website/docs/r/dds_instance_v3.html.markdown
support tags and ssl for dds instance resource
```
--- PASS: TestAccDDSV3Instance_basic (650.35s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 650.366s
```
=> support tags and ssl for dds instance resource

flexibleengine/provider_test.go
export `OS_ADMIN` to "admin", then we can run acctest for iam
=> precheck OS_ADMIN environment for iam acctest

flexibleengine/resource_flexibleengine_obs_bucket.go, flexibleengine/resource_flexibleengine_s3_bucket.go
item of `website` should at most 1.
=> add MaxItems in website block of obs/s3 bucket

docs/resources/compute_bms_server_v2.md, docs/resources/fw_firewall_group_v2.md, docs/resources/fw_policy_v2.md, docs/resources/fw_rule_v2.md, docs/resources/network_acl.md, docs/resources/network_acl_rule.md
- add `Network ACL` subcategory
- move flexibleengine_compute_bms_server_v2 to BMS subcategory
=> fix resources subcategory issue

flexibleengine/resource_flexibleengine_vpcep_approval.go
Fixes #495 
we can get the status from vpcep serviceID, then the approval can work cross-project.
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccVPCEndpointApproval'
TF_ACC=1 go test ./flexibleengine -v -run TestAccVPCEndpointApproval -timeout 720m
=== RUN   TestAccVPCEndpointApproval
=== PAUSE TestAccVPCEndpointApproval
=== CONT  TestAccVPCEndpointApproval
--- PASS: TestAccVPCEndpointApproval (311.67s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 311.685s
```
=> fix: vpcep approval can work cross-project

docs/resources/compute_instance_v2.md
=> update docs for compute instance

docs/data-sources/rds_flavors_v1.md, docs/resources/rds_instance_v1.md, flexibleengine/data_source_flexibleengine_rds_flavors_v1.go, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_rds_instance_v1.go
- deprecate flexibleengine_rds_instance_v1
- deprecate data.flexibleengine_rds_flavors_v1
=> deprecate rds v1 resource and data source

docs/resources/vpc_eip_v1.md, flexibleengine/resource_flexibleengine_vpc_eip_v1.go, flexibleengine/resource_flexibleengine_vpc_eip_v1_test.go, flexibleengine/value_specs.go
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccVpcV1EIP_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccVpcV1EIP_basic -timeout 720m
=== RUN   TestAccVpcV1EIP_basic
--- PASS: TestAccVpcV1EIP_basic (31.94s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 31.956s
```
=> eip: add status field and update docs

docs/resources/lts_group.md, docs/resources/lts_topic.md, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_lts_group.go, flexibleengine/resource_flexibleengine_lts_group_test.go, flexibleengine/resource_flexibleengine_lts_topic.go, flexibleengine/resource_flexibleengine_lts_topic_test.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/openstack/lts/v2/loggroups/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/lts/v2/loggroups/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/lts/v2/loggroups/urls.go, vendor/github.com/huaweicloud/golangsdk/openstack/lts/v2/logtopics/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/lts/v2/logtopics/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/lts/v2/logtopics/urls.go, vendor/github.com/huaweicloud/golangsdk/openstack/mls/v1/instances/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/rds/v3/configurations/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/drill/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/protectedinstances/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/protectiongroups/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/replications/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/falsealarmmasking_rules/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/policies/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/whiteblackip_rules/requests.go, vendor/modules.txt
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLTSGroupV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLTSGroupV2_basic -timeout 720m
=== RUN   TestAccLTSGroupV2_basic
=== PAUSE TestAccLTSGroupV2_basic
=== CONT  TestAccLTSGroupV2_basic
--- PASS: TestAccLTSGroupV2_basic (9.67s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 9.691s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLTSTopicV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLTSTopicV2_basic -timeout 720m
=== RUN   TestAccLTSTopicV2_basic
=== PAUSE TestAccLTSTopicV2_basic
=== CONT  TestAccLTSTopicV2_basic
--- PASS: …
```
=> feat: support lts group and topic resources

flexibleengine/resource_flexibleengine_vpc_subnet_v1.go
the waitForVpcSubnetDelete function will call subnets.Delete many times,
when the subnet was already deleted, it will return 404 or and 400 response code.
We should treat the response codes as a success.
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccFlexibleEngineVpcSubnetV1'
TF_ACC=1 go test ./flexibleengine -v -run TestAccFlexibleEngineVpcSubnetV1 -timeout 720m
=== RUN   TestAccFlexibleEngineVpcSubnetV1DataSource_basic
--- PASS: TestAccFlexibleEngineVpcSubnetV1DataSource_basic (47.52s)
=== RUN   TestAccFlexibleEngineVpcSubnetV1_basic
--- PASS: TestAccFlexibleEngineVpcSubnetV1_basic (63.86s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengin …
```
=> fix Subnet does not belong to the VPC error when deleting

docs/resources/identity_user_v3.md, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_identity_user_v3.go, flexibleengine/resource_flexibleengine_identity_user_v3_test.go, flexibleengine/utils.go, go.mod, go.sum, vendor/github.com/huaweicloud/golangsdk/.gitignore, vendor/github.com/huaweicloud/golangsdk/errors.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/urls.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/nodes/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/nodes/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/nodes/urls.go, vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/products/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3.0/users/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3.0/users/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3.0/users/urls.go, vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/cluster/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/cluster/results.go, vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/cluster/urls.go, vendor/github.com/huaweicloud/golangsdk/openstack/smn/v2/topics/requests.go, vendor/github.com/huaweicloud/golangsdk/openstack/smn/v2/topics/results.go, vendor/modules.txt
fixes #474 
the resulting result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccIdentityV3User_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccIdentityV3User_basic -timeout 720m
=== RUN   TestAccIdentityV3User_basic
--- PASS: TestAccIdentityV3User_basic (15.34s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 15.358s
```
=> feat: add email/phone field to identity_user_v3

flexibleengine/resource_flexibleengine_obs_bucket.go, go.mod, go.sum, vendor/github.com/chnsz/golangsdk/openstack/obs/CHANGELOG, vendor/github.com/chnsz/golangsdk/openstack/obs/README.MD, vendor/github.com/chnsz/golangsdk/openstack/obs/client.go, vendor/github.com/chnsz/golangsdk/openstack/obs/conf.go, vendor/github.com/chnsz/golangsdk/openstack/obs/const.go, vendor/github.com/chnsz/golangsdk/openstack/obs/convert.go, vendor/github.com/chnsz/golangsdk/openstack/obs/model.go, vendor/github.com/chnsz/golangsdk/openstack/obs/temporary.go, vendor/github.com/chnsz/golangsdk/openstack/obs/trait.go, vendor/modules.txt
=> vendor: bump obs sdk to v3.21.8

docs/index.md, flexibleengine/provider.go
=> provider: support both OS_USERNAME and OS_USER_NAME envs as user_name parameter

docs/data-sources/cce_addon_template.md, docs/resources/cce_addon_v3.md
add more usages and the supported addons
=> update docs for cce addon

docs/resources/antiddos_v1.md, flexibleengine/resource_flexibleengine_antiddos_v1.go, flexibleengine/resource_flexibleengine_antiddos_v1_test.go
related to #647
the following result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccAntiDdosV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccAntiDdosV1_basic -timeout 720m
=== RUN   TestAccAntiDdosV1_basic
--- PASS: TestAccAntiDdosV1_basic (474.18s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 474.189s
```
=> fix(antiddos): throw an error when got a 403 response

docs/resources/cce_addon_v3.md
=> docs(cce): fix documentation errors

flexibleengine/provider.go, flexibleengine/resource_flexibleengine_dis_stream_v2.go, flexibleengine/resource_flexibleengine_dis_stream_v2_test.go, vendor/github.com/chnsz/golangsdk/openstack/dis/v2/streams/requests.go, vendor/github.com/chnsz/golangsdk/openstack/dis/v2/streams/results.go, vendor/github.com/chnsz/golangsdk/openstack/dis/v2/streams/urls.go, vendor/modules.txt
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDis*'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDis* -timeout 720m
=== RUN   TestAccDisStreamV2_basic
=== PAUSE TestAccDisStreamV2_basic
=== CONT  TestAccDisStreamV2_basic
--- PASS: TestAccDisStreamV2_basic (8.97s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 9.044s
=> Feature stream

docs/resources/mrs_cluster_v1.md, docs/resources/mrs_cluster_v2.md, docs/resources/mrs_hybrid_cluster_v1.md, docs/resources/mrs_job_v1.md, docs/resources/mrs_job_v2.md
=> doc: update docs for MRS resources

flexibleengine/provider.go
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccObsBucket_basic'
=== PAUSE TestAccObsBucket_basic
=== CONT  TestAccObsBucket_basic
--- PASS: TestAccObsBucket_basic (94.63s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 94.699s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDNSV2Zone_private'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDNSV2Zone_private -timeout 720m
=== RUN   TestAccDNSV2Zone_private
=== PAUSE TestAccDNSV2Zone_private
=== CONT  TestAccDNSV2Zone_private
--- PASS: …
```
=> provider: support to custom endpoints to override the default endpoint URL

docs/resources/swr_organization.md, docs/resources/swr_organization_users.md, docs/resources/swr_repository.md, docs/resources/swr_repository_sharing.md, flexibleengine/acceptance/acceptance.go, flexibleengine/acceptance/resource_flexibleengine_swr_organization_test.go, flexibleengine/acceptance/resource_flexibleengine_swr_organization_users_test.go, flexibleengine/acceptance/resource_flexibleengine_swr_repository_sharing_test.go, flexibleengine/acceptance/resource_flexibleengine_swr_repository_test.go, flexibleengine/provider.go
fixes #756 
```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccSWROrganization_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccSWROrganization_basic -timeout 720m
=== RUN   TestAccSWROrganization_basic
=== PAUSE TestAccSWROrganization_basic
=== CONT  TestAccSWROrganization_basic
--- PASS: TestAccSWROrganization_basic (46.71s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      46.828s
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccSwrOrganizationPermissions_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run …
```
=> feat: new resources for SWR service

docs/resources/cce_namespace.md, docs/resources/cce_pvc.md, flexibleengine/acceptance/resource_flexibleengine_cce_namespace_test.go, flexibleengine/acceptance/resource_flexibleengine_cce_pvc_test.go, flexibleengine/provider.go, go.mod, go.sum
add new resources flexibleengine_cce_namespace and flexibleengine_cce_pvc
Test results:
```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccCcePersistentVolumeClaimsV1_sfs'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccCcePersistentVolumeClaimsV1_sfs -timeout 720m
=== RUN   TestAccCcePersistentVolumeClaimsV1_sfs
=== PAUSE TestAccCcePersistentVolumeClaimsV1_sfs
=== CONT  TestAccCcePersistentVolumeClaimsV1_sfs
--- PASS: TestAccCcePersistentVolumeClaimsV1_sfs (852.50s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      852.618s
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccCcePersistentVolumeClaimsV1_obs'
==> …
```
=> feat(cce): add cce namespace and pvc

docs/resources/cse_microservice.md, docs/resources/cse_microservice_engine.md, docs/resources/cse_microservice_instance.md, flexibleengine/acceptance/resource_flexibleengine_cse_microservice_engine_test.go, flexibleengine/acceptance/resource_flexibleengine_cse_microservice_instance_test.go, flexibleengine/acceptance/resource_flexibleengine_cse_microservice_test.go, flexibleengine/provider.go, go.mod, go.sum
add new cse resources
The following resources are added:
flexibleengine_cse_microservice
flexibleengine_cse_microservice_engine
flexibleengine_cse_microservice_instance
Test results:
```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccMicroserviceEngine_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccMicroserviceEngine_basic -timeout 720m
=== RUN   TestAccMicroserviceEngine_basic
=== PAUSE TestAccMicroserviceEngine_basic
=== CONT  TestAccMicroserviceEngine_basic
--- PASS: TestAccMicroserviceEngine_basic (1104.23s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance   1104.339s
make testacc TEST='./flexibleengine/acceptance/' …
```
=> feat(cse): add new cse resources

docs/resources/dcs_instance_v1.md
=> fix: update DCS instance docs

flexibleengine/resource_flexibleengine_dns_recordset_v2.go, flexibleengine/resource_flexibleengine_dns_recordset_v2_test.go
fixes #703 
it is caused by the API issue: `UpdateOpts.Records` field should not be empty
"code":"DNS.0308", "message":"Attribute 'records' is invalid, records is null or empty."
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDNSV2RecordSet_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDNSV2RecordSet_basic -timeout 720m
=== CONT  TestAccDNSV2RecordSet_basic
--- PASS: TestAccDNSV2RecordSet_basic (150.23s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 150.271s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDNSV2RecordSet_private'
==> …
```
=> fix(dns): always set Records field when updating

docs/data-sources/modelarts_dataset_versions.md, docs/data-sources/modelarts_datasets.md, docs/resources/modelarts_dataset.md, docs/resources/modelarts_dataset_version.md, flexibleengine/acceptance/data_source_flexibleengine_modelarts_dataset_versions_test.go, flexibleengine/acceptance/data_source_flexibleengine_modelarts_datasets_test.go, flexibleengine/acceptance/resource_flexibleengine_modelarts_dataset_test.go, flexibleengine/acceptance/resource_flexibleengine_modelarts_dataset_version_test.go, flexibleengine/provider.go
add new resource `flexibleengine_modelarts_dataset` and `flexibleengine_modelarts_dataset_version`
add new data_source `flexibleengine_modelarts_dataset_versions` and `flexibleengine_modelarts_datasets`
=> feat(modelarts): add new modelarts resources

docs/resources/drs_job.md, flexibleengine/acceptance/resource_flexibleengine_drs_job_test.go, flexibleengine/provider.go
=> feat(drs): add new drs job resource

docs/resources/rds_database_privilege.md, flexibleengine/acceptance/resource_flexibleengine_rds_account_test.go, flexibleengine/acceptance/resource_flexibleengine_rds_database_privilege_test.go, flexibleengine/provider.go, go.mod, go.sum
add new resource database_privilege
```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccRdsDatabasePrivilege_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccRdsDatabasePrivilege_basic -timeout 720m
=== RUN   TestAccRdsDatabasePrivilege_basic
=== PAUSE TestAccRdsDatabasePrivilege_basic
=== CONT  TestAccRdsDatabasePrivilege_basic
--- PASS: TestAccRdsDatabasePrivilege_basic (573.54s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      573.642s
```
=> feat(rds): add new resource database_privilege

flexibleengine/provider.go
=> fix(provider): auth_url should not use region var

docs/data-sources/elb_certificate.md, docs/data-sources/elb_flavors.md, docs/resources/elb_certificate.md, docs/resources/elb_ipgroup.md, docs/resources/lb_listener_v3.md, docs/resources/lb_loadbalancer_v3.md, docs/resources/lb_member_v3.md, docs/resources/lb_monitor_v3.md, docs/resources/lb_pool_v3.md, flexibleengine/acceptance/resource_flexibleengine_lb_member_v3_test.go, flexibleengine/acceptance/resource_flexibleengine_lb_monitor_v3_test.go, flexibleengine/acceptance/resource_flexibleengine_lb_pool_v3_test.go, flexibleengine/provider.go
fixes 
https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/issues/800
https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/issues/801
https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/issues/802
Test result:
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccElbV3Listener_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccElbV3Listener_basic -timeout 720m
=== RUN   TestAccElbV3Listener_basic
=== PAUSE TestAccElbV3Listener_basic
=== CONT  TestAccElbV3Listener_basic
--- PASS: TestAccElbV3Listener_basic (159.61s) 
PASS                                                                                                             
ok …
=> feat: fix lb issues

docs/resources/as_policy_v1.md, flexibleengine/resource_flexibleengine_as_policy_v1.go, flexibleengine/resource_flexibleengine_as_policy_v1_test.go
Result of test
```sh
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccASV1Policy_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccASV1Policy_basic -timeout 720m
=== RUN   TestAccASV1Policy_basic
--- PASS: TestAccASV1Policy_basic (28.00s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine        28.564s
```
=> feat(as/policy): ADD import for resource flexibleengine_as_policy_v1

docs/resources/cts_tracker_v1.md
In documentation add Timeout section and add more information on the required format for the argument `file_prefix_name`
=> doc(cts): add Timeout and add format file_prefix_name

docs/resources/dms_rocketmq_instance.md, flexibleengine/acceptance/resource_flexibleengine_dms_rocketmq_instance_test.go, flexibleengine/provider.go
test result:
```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccDmsRocketMQInstance_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccDmsRocketMQInstance_basic -timeout 720m
=== RUN   TestAccDmsRocketMQInstance_basic
=== PAUSE TestAccDmsRocketMQInstance_basic
=== CONT  TestAccDmsRocketMQInstance_basic
--- PASS: TestAccDmsRocketMQInstance_basic (1424.15s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      1424.296s
```
=> feat(dms): add new resource rocketmq_instance

docs/resources/dws_cluster_v1.md, flexibleengine/resource_flexibleengine_dws_cluster_v1.go, flexibleengine/resource_flexibleengine_dws_cluster_v1_test.go
related to #891 
the testing result:
```
make testacc TEST='./flexibleengine' TESTARGS='-run TestDWSClusterBasic'
TF_ACC=1 go test ./flexibleengine -v -run TestDWSClusterBasic -timeout 720m
=== RUN   TestDWSClusterBasic
--- PASS: TestDWSClusterBasic (1205.03s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 1205.143s
```
=> feat(dws): support public_ip parameter

docs/resources/compute_floatingip_v2.md, flexibleengine/resource_flexibleengine_compute_floatingip_v2.go, flexibleengine/resource_flexibleengine_lb_certificate_v2.go, flexibleengine/resource_flexibleengine_vpc_route_v2.go
=> fix: add missing DeprecationMessage for deprecated resources

flexibleengine/resource_flexibleengine_smn_subscription_v2.go
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccSMNV2Subscription_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccSMNV2Subscription_basic -timeout 720m
=== RUN   TestAccSMNV2Subscription_basic
--- PASS: TestAccSMNV2Subscription_basic (23.91s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 23.960s
```
=> fix: delete subscription resource if i t not exist

flexibleengine/acceptance/resource_flexibleengine_apig_vpc_channel_test.go, flexibleengine/provider.go, flexibleengine/resource_flexibleengine_ces_alarmrule.go, flexibleengine/resource_flexibleengine_ces_alarmrule_test.go, flexibleengine/resource_flexibleengine_sfs_turbo.go, go.mod, go.sum
Update the package references:
- CSE alarm rule
- APIG channel
Update the resource codes for build logic:
- SFS turbo
=> chore: refactor package reference and function usage

docs/data-sources/cce_cluster_v3.md, docs/resources/cce_cluster_v3.md, flexibleengine/data_source_flexibleengine_cce_cluster_v3.go, flexibleengine/resource_flexibleengine_cce_addon_v3.go, flexibleengine/resource_flexibleengine_cce_cluster_v3.go, go.mod, go.sum
add custom san support 
https://docs.prod-cloud-ocb.orange-business.com/api2/cce/cce_02_0236.html
=> feat(cce): specify customSan for cce cluster

main.go
=> chore: no need to flush obs log

flexibleengine/resource_flexibleengine_cce_node_pool.go
=> feat(cce) nodepool : set scall_enable as deprecated variable

docs/data-sources/cce_node_ids_v3.md, docs/data-sources/compute_bms_flavors_v2.md, docs/data-sources/compute_bms_keypairs_v2.md, docs/data-sources/compute_bms_nic_v2.md, docs/data-sources/compute_bms_server_v2.md, docs/data-sources/csbs_backup_policy_v1.md, docs/data-sources/csbs_backup_v1.md, docs/data-sources/cts_tracker_v1.md, docs/data-sources/rts_software_config.md, docs/data-sources/rts_stack_resource_v1.md, docs/data-sources/rts_stack_v1.md, docs/data-sources/sfs_file_system_v2.md, docs/data-sources/vbs_backup_policy_v2.md, docs/data-sources/vbs_backup_v2.md, docs/data-sources/vpc_peering_connection_v2.md, docs/data-sources/vpc_route_ids_v2.md, docs/data-sources/vpc_route_v2.md
=> docs: fix docs resource name issues

docs/resources/antiddos_v1.md
fix docs of Anti-DDoS service.
=> fix: fix docs of Anti-DDoS service.

docs/resources/ces_alarmrule.md
fix docs of CES service issues.
=> docs(CES): fix docs issues.

docs/data-sources/ddm_accounts.md, docs/data-sources/ddm_engines.md, docs/data-sources/ddm_flavors.md, docs/data-sources/ddm_instance_nodes.md, docs/data-sources/ddm_instances.md, docs/data-sources/ddm_schemas.md, docs/resources/ddm_account.md, docs/resources/ddm_instance.md, docs/resources/ddm_schema.md, flexibleengine/acceptance/data_source_flexibleengine_ddm_accounts_test.go, flexibleengine/acceptance/data_source_flexibleengine_ddm_engines_test.go, flexibleengine/acceptance/data_source_flexibleengine_ddm_flavors_test.go, flexibleengine/acceptance/data_source_flexibleengine_ddm_instance_nodes_test.go, flexibleengine/acceptance/data_source_flexibleengine_ddm_instances_test.go, flexibleengine/acceptance/data_source_flexibleengine_ddm_schemas_test.go, flexibleengine/acceptance/resource_flexibleengine_ddm_account_test.go, flexibleengine/acceptance/resource_flexibleengine_ddm_instance_test.go, flexibleengine/acceptance/resource_flexibleengine_ddm_schema_test.go, flexibleengine/provider.go
new data_sources:
flexibleengine_ddm_accounts
flexibleengine_ddm_engines
flexibleengine_ddm_flavors
flexibleengine_ddm_instance_nodes
flexibleengine_ddm_instances
flexibleengine_ddm_schemas
new resourcese:
flexibleengine_ddm_account
flexibleengine_ddm_instance
flexibleengine_ddm_schema
Test results:
```
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccDatasourceDdmEngines_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccDatasourceDdmEngines_basic -timeout 720m
=== RUN   TestAccDatasourceDdmEngines_basic
=== PAUSE TestAccDatasourceDdmEngines_basic
=== CONT  TestAccDatasourceDdmEngines_basic
--- PASS: TestAccDatasourceDdmEngines_basic (22.76s)
PASS
ok …
```
=> feat(ddm): add ddm resources

docs/data-sources/cbr_backup.md, docs/data-sources/cbr_vaults.md, docs/resources/cbr_policy.md, docs/resources/cbr_vault.md
=> docs(cbr): fix docs issues.

docs/resources/cse_microservice_instance.md
=> docs(cse): fix docs issues.

docs/data-sources/cts_tracker_v1.md, docs/resources/cts_tracker_v1.md
=> docs(cts): fix docs issues.

docs/data-sources/as_configurations.md, docs/data-sources/as_groups.md
Supplement missing documents of AS service
=> docs(as): Supplement missing documents

docs/data-sources/dcs_az_v1.md, docs/data-sources/dcs_maintainwindow_v1.md, docs/data-sources/dcs_product_v1.md, docs/resources/dcs_instance_v1.md, flexibleengine/resource_flexibleengine_dcs_instance_v1.go
=> docs(dcs): fix docs issue and schema missing field

docs/data-sources/compute_bms_flavors_v2.md, docs/data-sources/compute_bms_keypairs_v2.md, docs/data-sources/compute_bms_nic_v2.md, docs/data-sources/compute_bms_server_v2.md, docs/resources/compute_bms_server_v2.md
add attribute `tenant_id` filed
add attribute `tenant_id` filed
=> docs(bms): fix docs issues.

docs/resources/css_cluster_v1.md, docs/resources/css_snapshot_v1.md
=> docs(css): fix docs issues.

docs/data-sources/dms_kafka_instances.md, docs/data-sources/dms_product.md, docs/data-sources/dms_rocketmq_broker.md, docs/data-sources/dms_rocketmq_instances.md, docs/resources/dms_kafka_instance.md, docs/resources/dms_rocketmq_instance.md, docs/resources/dms_rocketmq_topic.md, flexibleengine/data_source_flexibleengine_dms_product_test.go
```hcl
=== RUN   TestAccDmsProductDataSource_basic
=== PAUSE TestAccDmsProductDataSource_basic
=== CONT  TestAccDmsProductDataSource_basic
--- PASS: TestAccDmsProductDataSource_basic (34.09s)
PASS
coverage: 1.8% of statements in ../../terraform-provider-flexibleengine/...
```
=> docs(dms): fix docs issues.

docs/resources/lb_loadbalancer_v3.md
add new parameter autoscaling_enabled, min_l7_flavor_id and backend_subnets
=> docs(elb): udpate the doc of loadbalancer

docs/resources/fgs_function.md, docs/resources/fgs_trigger.md
**type: ​**resource
**field:** `app`、`handler`
**reason: ​**The two fields are **Required**
**field:** `code_type`
**reason: ​**the field is **Required**
=> docs(fgs): fix docs issues

docs/data-sources/smn_topics.md, docs/data-sources/sms_source_servers.md, docs/resources/smn_topic_v2.md, docs/resources/sms_task.md, docs/resources/swr_organization.md, docs/resources/swr_organization_users.md, docs/resources/swr_repository.md, docs/resources/swr_repository_sharing.md, flexibleengine/acceptance/data_source_flexibleengine_smn_topics_test.go, flexibleengine/acceptance/resource_flexibleengine_smn_topic_test.go
**type: ​**resource
**reason:** terraform script and unit test are both passed<br />
```shell
=== RUN   TestAccSMNV2Topic_basic
=== PAUSE TestAccSMNV2Topic_basic
=== CONT  TestAccSMNV2Topic_basic
--- PASS: TestAccSMNV2Topic_basic (79.68s)
PASS
```
**field:** `tags`
**reason:** terraform script is not passed
**type: ​**data source
**reason:** terraform script and unit test are both passed<br />
```shell
=== RUN   TestAccDataTopics_basic
=== PAUSE TestAccDataTopics_basic
=== CONT  TestAccDataTopics_basic
--- PASS: TestAccDataTopics_basic (37.89s)
PASS
```
=> docs(smn/sms/swr): fix docs issues

docs/resources/mrs_cluster_v2.md, docs/resources/mrs_job_v2.md, flexibleengine/resource_flexibleengine_mrs_cluster_v2.go
=> docs(mrs): fix docs issues

docs/data-sources/kms_data_key_v1.md, docs/data-sources/kms_key_v1.md, docs/resources/kms_key_v1.md, docs/resources/lts_topic.md, docs/resources/mls_instance_v1.md, flexibleengine/resource_flexibleengine_mls_instance_v1.go
=> docs(kms/lts/mls): fix docs issues

docs/data-sources/sfs_file_system_v2.md, docs/data-sources/sfs_turbos.md, docs/resources/sfs_access_rule_v2.md, docs/resources/sfs_file_system_v2.md, docs/resources/sfs_turbo.md, flexibleengine/acceptance/data_source_flexibleengine_sfs_turbos_test.go, flexibleengine/acceptance/resource_flexibleengine_sfs_turbo_test.go
**reason:** the unit test are both passed
```hcl
=== RUN   TestAccSFSTurbo_basic
=== PAUSE TestAccSFSTurbo_basic
=== CONT  TestAccSFSTurbo_basic
--- PASS: TestAccSFSTurbo_basic (465.50s)
PASS
coverage: 2.1% of statements in ../../../terraform-provider-flexibleengine/...
```
**reason:** unit test was passed
```hcl
=== RUN   TestAccTurbosDataSource_basic
=== PAUSE TestAccTurbosDataSource_basic
=== CONT  TestAccTurbosDataSource_basic
--- PASS: TestAccTurbosDataSource_basic (380.42s)
PASS
coverage: 2.1% of statements in ../../../terraform-provider-flexibleengine/...
```
**field:** `description`, `project_id`
**reason:** terraform script was passed<br />
=> docs(sfs): fix docs issues.

docs/data-sources/cce_nodes.md, flexibleengine/acceptance/data_source_flexibleengine_cce_nodes_test.go, flexibleengine/provider.go
import `data_source_flexibleengine_cce_nodes` resource, unit test and document
fixes #xxx
```release-note
```
```
...
=== RUN   TestAccNodesDataSource_basic
=== PAUSE TestAccNodesDataSource_basic
=== CONT  TestAccNodesDataSource_basic
--- PASS: TestAccNodesDataSource_basic (972.24s)
PASS
coverage: 3.5% of statements in ../../../terraform-provider-flexibleengine/...
```
=> feat(CCE): import CCE resource, unit test and document.

CHANGELOG.md
fixes #xxx
```release-note
```
```
...
PASS
```
=> changelog: update CHANGELOG for v1.43.0

docs/resources/lb_loadbalancer_v3.md
fix `resource_flexibleengine_lb_loadbalancer_v3` docs issues
fixes #xxx
```release-note
```
```
```
=> docs(ELB): fix the docs issues.

docs/resources/cce_node_pool_v3.md, docs/resources/cce_node_v3.md, flexibleengine/acceptance/data_source_flexibleengine_obs_bucket_object_test.go, flexibleengine/resource_flexibleengine_cce_node_pool.go, flexibleengine/resource_flexibleengine_cce_node_pool_test.go, flexibleengine/resource_flexibleengine_cce_node_v3.go, flexibleengine/resource_flexibleengine_cce_node_v3_test.go
new fields are as follows:
**1. cce_node**
* runtime
**2. cce_node_pool**
* runtime
* security_groups
fixes #xxx
```release-note
```
```md
=== RUN   TestAccCCENodePool_securityGroups
=== PAUSE TestAccCCENodePool_securityGroups
=== CONT  TestAccCCENodePool_securityGroups
--- PASS: TestAccCCENodePool_securityGroups (864.71s)
PASS
```
```md
=== PAUSE TestAccCCENodeV3_basic
=== CONT  TestAccCCENodeV3_basic
--- PASS: TestAccCCENodeV3_basic (1123.47s)
PASS
```
=> feat(CCE): add new fields.

flexibleengine/resource_flexibleengine_cce_node_pool.go, flexibleengine/resource_flexibleengine_cce_node_v3.go
add new status of resource.
fixes #xxx
```release-note
```
```
=== RUN   TestAccCCENodePool_securityGroups
=== PAUSE TestAccCCENodePool_securityGroups
=== CONT  TestAccCCENodePool_securityGroups
--- PASS: TestAccCCENodePool_securityGroups (845.34s)
PASS
=== PAUSE TestAccCCENodeV3_basic
=== CONT  TestAccCCENodeV3_basic
--- PASS: TestAccCCENodeV3_basic (947.43s)
PASS
```
=> feat(CCE): add new status of resource.

.github/workflows/prow.yml, OWNERS
fixes #xxx
```release-note
```
```
...
PASS
```
=> feat(workflow): Add prow GitHub action to manage labels

.github/workflows/prow.yml
fixes #xxx
```release-note
```
```
NONE
```
=> refactor(workflow): Switch prow-action to chnsz organization.

docs/data-sources/dcs_flavors.md, docs/data-sources/dcs_instances.md, docs/resources/dcs_backup_v1.md, flexibleengine/acceptance/common.go, flexibleengine/acceptance/data_source_flexibleengine_dcs_flavors_test.go, flexibleengine/acceptance/data_source_flexibleengine_dcs_instances_test.go, flexibleengine/acceptance/data_source_flexibleengine_obs_bucket_object_test.go, flexibleengine/acceptance/resource_flexibleengine_dcs_backup_v1_test.go, flexibleengine/provider.go
=> feat(dcs): import DCS resources, datasources and docs

README.md, docs/guides/remote-state-backend.md
fixes #1074 
```release-note
```
```
...
PASS
```
=> docs(backend): update remote state backend for terraform v1.6.3

docs/data-sources/waf_certificate.md, flexibleengine/acceptance/data_source_flexibleengine_waf_certificate_test.go, flexibleengine/provider.go
fixes #xxx
```release-note
```
```
=== RUN   TestAccDataSourceWafCertificateV1_basic
=== PAUSE TestAccDataSourceWafCertificateV1_basic
=== CONT  TestAccDataSourceWafCertificateV1_basic
--- PASS: TestAccDataSourceWafCertificateV1_basic (731.59s)
PASS
```
=> feat(WAF): import WAF resource, unit test and document.

docs/data-sources/elb_loadbalancers.md, flexibleengine/acceptance/data_source_flexibleengine_elb_loadbalancers_test.go, flexibleengine/provider.go
fixes #xxx
```release-note
```
```
=== RUN   TestAccDatasourceLoadBalancers_basic
=== PAUSE TestAccDatasourceLoadBalancers_basic
=== CONT  TestAccDatasourceLoadBalancers_basic
--- PASS: TestAccDatasourceLoadBalancers_basic (95.04s)
PASS
```
=> feat(ELB): add a data source to get the list of ELB loadbalancers

CHANGELOG.md
fixes #xxx
```release-note
```
```
...
PASS
```
=> changelog: update CHANGELOG for v1.45.0

docs/resources/cce_cluster_v3.md, docs/resources/mrs_cluster_v1.md, docs/resources/mrs_hybrid_cluster_v1.md
fixes #1109 
```release-note
```
```
...
PASS
```
=> docs: fix the outdated URL in cce and markdown lint issues

.markdownlint.json
fixes #xxx
```release-note
```
```
...
PASS
```
=> chore: update config of markdownlint rules
