flexibleengine/resource_flexibleengine_elb_backend_test.go

This removes the ExpectNonEmptyPlan on elb backend test.

Fix elb backend test error

---

flexibleengine/import_flexibleengine_blockstorage_volume_v2_test.go
flexibleengine/resource_flexibleengine_blockstorage_volume_v2.go
vendor/github.com/huaweicloud/golangsdk/openstack/blockstorage/v2/volumes/requests.go
vendor/vendor.json
website/docs/r/blockstorage_volume_v2.html.markdown

This PR adds capability to delete EVS disk with cascading option so that snapshots are deleted first in order to facilitate successful volume deletion. This is useful in VBS acc tests.

Modify Volume delete interface

---

flexibleengine/resource_flexibleengine_vpc_subnet_v1.go

When this resource is used with a list variable that contains many subnets description, terraform exits with an error because all subnets are not created and the status is unknown.
`locals {
subnets = [
{
subnet_name       = "private_1"
subnet_cidr       = "10.20.2.0/24"
subnet_gateway_ip = "10.20.2.1"
},
{
subnet_name       = "private_2"
subnet_cidr       = "10.20.3.0/24"
subnet_gateway_ip = "10.20.3.1"
},
{
subnet_name       = "private_3"
subnet_cidr       = "10.20.4.0/24"
subnet_gateway_ip = "10.20.4.1"
},
]
}
resource "flexibleengine_vpc_subnet_v1" "subnet" {
count = "length(local.subnets) > 0 ? length(local.subnets) : 0}"
name          = "${lookup(local.subnets[count.index], "subnet_name")}"
cidr          = "${lookup(local.subnets[count.index], "subnet_cidr")}"
gateway_ip    = …

remove UNKNOWN status to avoid error when subnet creation is too long

---

website/docs/d/s3_bucket_object.html.markdown

Right now the rendered documentation is looking decidedly wonky: https://www.terraform.io/docs/providers/flexibleengine/d/s3_bucket_object.html

[docs] Remember to close the fenced code block

---

flexibleengine/resource_flexibleengine_lb_pool_v2.go

This removes the retryable error check as we keep receiving 409 from server side if protocol mismatch with listener.
fixes #165

Fix LB Pool stuck issue

---

website/docs/r/compute_instance_v2.html.markdown

This removes personality argument from compute_instance docs as it doesn't take effect on Cloud side.

Remove personality argument from compute_instance docs

---

flexibleengine/config.go
flexibleengine/provider.go

Remove deprecated terraform helpers to get UserAgent.
Add terraformVersion to provider config.

Prepare to SDK migration

---

flexibleengine/resource_flexibleengine_compute_instance_v2.go

we can get the error message in the fault field of querying response body.
This patch prepare to fix #254

Log fault message when build compute instance failed

---

flexibleengine/resource_flexibleengine_lb_listener_v2.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/listeners/results.go
vendor/modules.txt
website/docs/r/lb_listener_v2.html.markdown

'tls_ciphers_policy' was available in lb_listerner_v2 API, and we  implement it on Teraform.
fix #280

Support 'tls_ciphers_policy' in flexibleengine_lb_listener_v2 resource

---

flexibleengine/provider.go
flexibleengine/resource_flexibleengine_sdrs_replication_pair_v1.go
flexibleengine/resource_flexibleengine_sdrs_replication_pair_v1_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/replications/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/replications/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/replications/results_job.go
vendor/github.com/huaweicloud/golangsdk/openstack/sdrs/v1/replications/urls.go
vendor/github.com/huaweicloud/golangsdk/service_client.go
vendor/modules.txt
website/docs/r/sdrs_replication_pair_v1.html.markdown
website/flexibleengine.erb

This PR supports new resource named flexibleengine_sdrs_replication_pair_v1.
The result of running test case as follows:
```shell
$ TF_ACC=1 make testacc TEST=./flexibleengine TESTARGS='-run TestAccSdrsReplicationPairV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccSdrsReplicationPairV1_basic -timeout 720m
=== RUN   TestAccSdrsReplicationPairV1_basic
--- PASS: TestAccSdrsReplicationPairV1_basic (179.54s)
PASS
ok  	github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine	179.555s
```

Add flexibleengine_sdrs_replication_pair_v1 resource and docs

---

website/docs/r/nat_gateway_v2.html.markdown

fix "spec","tenant id","router_id" and "internal_network_id" description to avoid any mistake/misunderstanding

fix argument reference for a better user experience

---

flexibleengine/data_source_flexibleengine_networking_network_v2.go
flexibleengine/data_source_flexibleengine_networking_network_v2_test.go

fixes #312 
the result of Testacc as follows:
```
$ make testacc TEST=./flexibleengine TESTARGS='-run TestAccNetworkingNetworkV2DataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccNetworkingNetworkV2DataSource_basic -timeout 720m
=== RUN   TestAccNetworkingNetworkV2DataSource_basic
--- PASS: TestAccNetworkingNetworkV2DataSource_basic (316.63s)
PASS
ok  	github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine	316.642s
```

Update test case for data.flexibleengine_networking_network_v2

---

website/docs/r/dns_zone_v2.html.markdown

fixing format for tf v0.12 on router description and add router=vpc explanation on the doc

fixing format for tf v0.12 and router=vpc

---

flexibleengine/resource_flexibleengine_obs_bucket.go
flexibleengine/resource_flexibleengine_obs_bucket_object.go
flexibleengine/resource_flexibleengine_obs_bucket_test.go
website/docs/r/obs_bucket.html.markdown

fixes #337 
test results:
```
$ make testacc TEST=./flexibleengine TESTARGS='-run TestAccObsBucket_basic'
--- PASS: TestAccObsBucket_basic (95.45s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 95.463s
$ make testacc TEST=./flexibleengine TESTARGS='-run TestAccObsBucket_lifecycle'
TF_ACC=1 go test ./flexibleengine -v -run TestAccObsBucket_lifecycle -timeout 720m
=== RUN   TestAccObsBucket_lifecycle
--- PASS: TestAccObsBucket_lifecycle (80.04s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengi …
```

cancel validation of storage_class in obs bucket and object

---

website/docs/r/cce_cluster_v3.html.md

Adding the new v1.15 version for clusterVersion paramter .
@DafuSHI should we remove 'v1.11.7-r2 as it will be deprecated soon ?

Adding “v1.15.6-r1” in the cluster_version

---

flexibleengine/provider.go
flexibleengine/resource_flexibleengine_css_snapshot_v1.go
flexibleengine/resource_flexibleengine_css_snapshot_v1_test.go
website/docs/r/css_snapshot_v1.html.markdown
website/flexibleengine.erb

the resource named `flexibleengine_css_snapshot_v1` which was used to create and delete an css snapshot manually.
```
$ make testacc TEST=./flexibleengine TESTARGS='-run TestAccCssSnapshotV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCssSnapshotV1_basic -timeout 720m
=== RUN   TestAccCssSnapshotV1_basic
--- PASS: TestAccCssSnapshotV1_basic (946.97s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 946.978s
```

Add css snapshot resource and docs

---

go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/css/v1/snapshots/requests.go
vendor/modules.txt

reference to: huaweicloud/golangsdk#290
using "{}" instead of nil as request body, otherwise, we will get 403 response code from the enable/auto_setting API.

update golangsdk to fix css issue

---

flexibleengine/resource_flexibleengine_sfs_file_system_v2.go
flexibleengine/resource_flexibleengine_sfs_file_system_v2_test.go
website/docs/r/sfs_file_system_v2.html.md

improve for flexibleengine_sfs_file_system_v2 resource:
- set 'access_to' to be optional in sfs file system
- add 'access_rules' attribute to show all access rules
the testacc results as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccSFSFileSystemV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccSFSFileSystemV2_basic -timeout 720m
=== RUN   TestAccSFSFileSystemV2_basic
--- PASS: TestAccSFSFileSystemV2_basic (73.55s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 73.564s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccSFSFileSystemV2_without_rule'
TF_ACC=1 go test ./flexibleengine …
```

set 'access_to' to be optional in sfs file system

---

flexibleengine/provider.go
flexibleengine/resource_flexibleengine_sfs_access_rule_v2.go
flexibleengine/resource_flexibleengine_sfs_access_rule_v2_test.go
website/docs/r/sfs_access_rule_v2.html.md
website/docs/r/sfs_file_system_v2.html.md
website/flexibleengine.erb

fixes #332 
the result of acc as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccSFSAccessRuleV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccSFSAccessRuleV2_basic -timeout 720m
=== RUN   TestAccSFSAccessRuleV2_basic
--- PASS: TestAccSFSAccessRuleV2_basic (85.12s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 85.137s
```

Add sfs access rule resource and docs

---

.github/workflows/release.yml
.goreleaser.yml

Following the Hashicorp recommandation, I suggest to use Github Actions to automatically build and publish new provider releases to the Terraform Registry whenever a new version tag is created on our repo.
--> https://www.terraform.io/docs/registry/providers/publishing.html?_ga=2.33198973.2135645616.1599122209-954780048.1509639856#github-actions-preferred-

Add auto builder based on Github Actions and GoReleaser 

---

flexibleengine/resource_flexibleengine_css_cluster_v1.go

The backup function was auto enabled since 1.14.0 version, but it requires the authority of OBS Bucket and IAM Agency. 
Actually, it's no necessary to require the authority if we don't configure backup.

enable the backup function only when the strategy was configured

---

flexibleengine/resource_flexibleengine_css_cluster_v1.go
flexibleengine/resource_flexibleengine_css_cluster_v1_test.go
flexibleengine/tags.go
website/docs/r/css_cluster_v1.html.markdown

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCssClusterV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCssClusterV1_basic -timeout 720m
=== RUN   TestAccCssClusterV1_basic
--- PASS: TestAccCssClusterV1_basic (951.95s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine
```

make tags of css cluster to be update-able

---

flexibleengine/resource_flexibleengine_css_cluster_v1.go
flexibleengine/resource_flexibleengine_css_cluster_v1_test.go
website/docs/r/css_cluster_v1.html.markdown

Fixes #399 
This PR will support security mode for css cluster by adding two parameters `security_mode` and `password`.
The testing result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCssClusterV1_security'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCssClusterV1_security -timeout 720m
=== RUN   TestAccCssClusterV1_security
--- PASS: TestAccCssClusterV1_security (995.06s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 995.070s
```

support security mode for css cluster

---

flexibleengine/config.go
flexibleengine/golangsdk_utils.go
flexibleengine/resource_flexibleengine_cce_node_v3.go
flexibleengine/resource_flexibleengine_compute_instance_v2.go
flexibleengine/resource_flexibleengine_ecs_v1_util.go

unwrap `chooseECSV1Client` into `config.computeV1Client`
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccComputeV2Instance_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccComputeV2Instance_basic -timeout 720m
=== RUN   TestAccComputeV2Instance_basic
--- PASS: TestAccComputeV2Instance_basic (240.26s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 240.275s
```

unwrap chooseECSV1Client into config.computeV1Client

---

flexibleengine/data_source_flexibleengine_compute_instance_v2.go
flexibleengine/data_source_flexibleengine_compute_instance_v2_test.go
flexibleengine/provider.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/client.go
vendor/github.com/huaweicloud/golangsdk/openstack/compute/v2/servers/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/ecs/v1/block_devices/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/ecs/v1/block_devices/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/ecs/v1/block_devices/urls.go
vendor/github.com/huaweicloud/golangsdk/openstack/ecs/v1/cloudservers/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/ecs/v1/cloudservers/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/ecs/v1/cloudservers/results_job.go
vendor/github.com/huaweicloud/golangsdk/openstack/ecs/v1/cloudservers/urls.go
vendor/modules.txt
website/docs/d/compute_instance_v2.html.md
website/flexibleengine.erb

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccComputeInstanceDataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccComputeInstanceDataSource_basic -timeout 720m
=== RUN   TestAccComputeInstanceDataSource_basic
=== PAUSE TestAccComputeInstanceDataSource_basic
=== CONT  TestAccComputeInstanceDataSource_basic
--- PASS: TestAccComputeInstanceDataSource_basic (226.41s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 226.423s
```

add compute instance data source and docs

---

flexibleengine/resource_flexibleengine_compute_instance_v2.go
flexibleengine/resource_flexibleengine_compute_instance_v2_test.go
website/docs/d/compute_instance_v2.html.md
website/docs/r/compute_instance_v2.html.markdown

Compute instances can be imported by their `id`. For example,
```
terraform import flexibleengine_compute_instance_v2.my_instance b11b407c-e604-4e8d-8bc4-92398320b847
```

support to import compute instance and add more attributes

---

flexibleengine/import_flexibleengine_networking_port_v2_test.go
flexibleengine/resource_flexibleengine_networking_port_v2.go
flexibleengine/resource_flexibleengine_networking_port_v2_test.go

```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccNetworkingV2Port'
TF_ACC=1 go test ./flexibleengine -v -run TestAccNetworkingV2Port -timeout 720m
=== RUN   TestAccNetworkingV2Port_importBasic
--- PASS: TestAccNetworkingV2Port_importBasic (61.74s)
=== RUN   TestAccNetworkingV2Port_basic
--- PASS: TestAccNetworkingV2Port_basic (69.90s)
=== RUN   TestAccNetworkingV2Port_fixedip
--- PASS: TestAccNetworkingV2Port_fixedip (71.48s)
=== RUN   TestAccNetworkingV2Port_allowedAddressPairs
--- PASS: TestAccNetworkingV2Port_allowedAddressPairs (81.09s)
=== RUN   TestAccNetworkingV2Port_securityGroup
--- PASS: TestAccNetworkingV2Port_securityGroup (73.58s)
PASS
ok …
```

support import fixed_ip block to networking port

---

flexibleengine/provider.go
flexibleengine/resource_flexibleengine_vpcep_service.go
flexibleengine/resource_flexibleengine_vpcep_service_test.go
flexibleengine/tags.go
website/docs/r/vpcep_service.html.md
website/flexibleengine.erb

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccVPCEPService'
TF_ACC=1 go test ./flexibleengine -v -run TestAccVPCEPService -timeout 720m
=== RUN   TestAccVPCEPServiceBasic
=== PAUSE TestAccVPCEPServiceBasic
=== RUN   TestAccVPCEPServicePermission
=== PAUSE TestAccVPCEPServicePermission
=== CONT  TestAccVPCEPServiceBasic
=== CONT  TestAccVPCEPServicePermission
--- PASS: TestAccVPCEPServiceBasic (244.11s)
--- PASS: TestAccVPCEPServicePermission (287.40s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 287.410s
```

add vpc endpoint service resource and docs

---

flexibleengine/provider.go
flexibleengine/resource_flexibleengine_dns_ptrrecord_v2.go
flexibleengine/resource_flexibleengine_dns_ptrrecord_v2_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/dns/v2/ptrrecords/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/dns/v2/ptrrecords/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/dns/v2/ptrrecords/urls.go
vendor/modules.txt
website/docs/r/dns_ptrrecord_v2.html.markdown
website/docs/r/dns_recordset_v2.html.markdown
website/docs/r/dns_zone_v2.html.markdown
website/flexibleengine.erb

add a new resource named `flexibleengine_dns_ptrrecord_v2`, the testing result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDNSV2PtrRecord_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDNSV2PtrRecord_basic -timeout 720m
=== RUN   TestAccDNSV2PtrRecord_basic
=== PAUSE TestAccDNSV2PtrRecord_basic
=== CONT  TestAccDNSV2PtrRecord_basic
--- PASS: TestAccDNSV2PtrRecord_basic (55.97s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 55.987s
```

add dns ptr record resource and docs

---

flexibleengine/resource_flexibleengine_sfs_turbo.go
flexibleengine/resource_flexibleengine_sfs_turbo_test.go
website/docs/r/sfs_turbo.html.markdown

fixes #433 
```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccSFSTurbo_crypt'
TF_ACC=1 go test ./flexibleengine -v -run TestAccSFSTurbo_crypt -timeout 720m
=== RUN   TestAccSFSTurbo_crypt
--- PASS: TestAccSFSTurbo_crypt (404.53s)
PASS
ok    github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 404.53s
```

support kms cryption for sfs turbo

---

flexibleengine/provider.go
flexibleengine/resource_flexibleengine_vpcep_endpoint.go
flexibleengine/resource_flexibleengine_vpcep_endpoint_test.go
flexibleengine/resource_flexibleengine_vpcep_service_test.go
vendor/github.com/huaweicloud/golangsdk/openstack/vpcep/v1/endpoints/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/vpcep/v1/endpoints/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/vpcep/v1/endpoints/urls.go
vendor/modules.txt
website/docs/r/vpcep_endpoint.html.md
website/flexibleengine.erb

add a new resource named `flexibleengine_vpcep_endpoint` to manage a VPC endpoint. The testing result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccVPCEndpoint'
TF_ACC=1 go test ./flexibleengine -v -run TestAccVPCEndpoint -timeout 720m
=== RUN   TestAccVPCEndpointBasic
=== PAUSE TestAccVPCEndpointBasic
=== RUN   TestAccVPCEndpointPublic
=== PAUSE TestAccVPCEndpointPublic
=== CONT  TestAccVPCEndpointBasic
=== CONT  TestAccVPCEndpointPublic
--- PASS: TestAccVPCEndpointPublic (21.39s)
--- PASS: TestAccVPCEndpointBasic (239.39s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 239.399s
```

add vpc endpoint resource and docs

---

flexibleengine/provider.go
flexibleengine/resource_flexibleengine_vpcep_approval.go
flexibleengine/resource_flexibleengine_vpcep_approval_test.go
website/docs/r/vpcep_approval.html.md
website/flexibleengine.erb

reference to #334
add a new resource named `flexibleengine_vpcep_approval` to manage VPC endpoint connections. The testing result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccVPCEndpointApproval'
TF_ACC=1 go test ./flexibleengine -v -run TestAccVPCEndpointApproval -timeout 720m
=== RUN   TestAccVPCEndpointApproval
=== PAUSE TestAccVPCEndpointApproval
=== CONT  TestAccVPCEndpointApproval
--- PASS: TestAccVPCEndpointApproval (264.17s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 264.177s
```

add vpc endpoint approval resource and docs

---

flexibleengine/resource_flexibleengine_rds_instance_v3.go
flexibleengine/resource_flexibleengine_rds_instance_v3_test.go
flexibleengine/resource_flexibleengine_rds_read_replica_v3.go
flexibleengine/resource_flexibleengine_rds_read_replica_v3_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/rds/v3/instances/results.go
vendor/modules.txt
website/docs/r/rds_instance_v3.html.markdown
website/docs/r/rds_read_replica_v3.html.markdown

This PR is related to #427
The testing result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccRdsInstanceV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccRdsInstanceV3_basic -timeout 720m
=== RUN   TestAccRdsInstanceV3_basic
--- PASS: TestAccRdsInstanceV3_basic (617.40s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 617.415s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccRdsReplicaInstanceV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccRdsReplicaInstanceV3_basic -timeout 720m
=== RUN   TestAccRdsReplicaInstanceV3_basic
--- PASS: TestAccRdsReplicaInstanceV3_basic …
```

support tags for rds instance and read replica

---

flexibleengine/config.go
flexibleengine/resource_flexibleengine_as_group_v1.go
flexibleengine/resource_flexibleengine_as_group_v1_test.go
flexibleengine/resource_flexibleengine_lb_listener_v2.go
flexibleengine/resource_flexibleengine_lb_listener_v2_test.go
flexibleengine/resource_flexibleengine_lb_loadbalancer_v2.go
flexibleengine/resource_flexibleengine_lb_loadbalancer_v2_test.go
website/docs/r/as_group_v1.html.markdown
website/docs/r/lb_listener_v2.html.markdown
website/docs/r/lb_loadbalancer_v2.html.markdown

This PR is related to #427
The testing result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccASV1Group_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccASV1Group_basic -timeout 720m
=== RUN   TestAccASV1Group_basic
--- PASS: TestAccASV1Group_basic (79.82s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 79.830s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLBV2LoadBalancer_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2LoadBalancer_basic -timeout 720m
--- PASS: TestAccLBV2LoadBalancer_basic (47.61s)
PASS
ok …
```

support tags for as group and lb resources

---

flexibleengine/resource_flexibleengine_rds_instance_v3.go
flexibleengine/resource_flexibleengine_rds_instance_v3_test.go
website/docs/r/rds_instance_v3.html.markdown

fixes #389 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccRdsInstanceV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccRdsInstanceV3_basic -timeout 720m
=== RUN   TestAccRdsInstanceV3_basic
--- PASS: TestAccRdsInstanceV3_basic (625.80s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine (625.86s)
```

add time_zome to rds instance v3

---

flexibleengine/compute_util.go
flexibleengine/data_source_flexibleengine_compute_instance_v2.go
flexibleengine/resource_flexibleengine_compute_instance_v2.go
flexibleengine/resource_flexibleengine_compute_instance_v2_test.go
website/docs/d/compute_instance_v2.html.md
website/docs/r/compute_instance_v2.html.markdown

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccComputeV2Instance_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccComputeV2Instance_basic -timeout 720m
=== RUN   TestAccComputeV2Instance_basic
--- PASS: TestAccComputeV2Instance_basic (225.38s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 225.397s
```

add volume_attached/type to compute instance and update docs for import section

---

flexibleengine/data_source_flexibleengine_identity_custom_role_v3.go
flexibleengine/data_source_flexibleengine_identity_custom_role_v3_test.go
flexibleengine/provider.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3.0/policies/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3.0/policies/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3.0/policies/urls.go
vendor/modules.txt
website/docs/d/identity_custom_role_v3.html.markdown
website/flexibleengine.erb

fixes #422 
Test result:
```bash
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccFlexibleEngineIdentityCustomRoleV3DataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccFlexibleEngineIdentityCustomRoleV3DataSource_basic -timeout 720m
=== RUN   TestAccFlexibleEngineIdentityCustomRoleV3DataSource_basic
=== PAUSE TestAccFlexibleEngineIdentityCustomRoleV3DataSource_basic
=== CONT  TestAccFlexibleEngineIdentityCustomRoleV3DataSource_basic
--- PASS: TestAccFlexibleEngineIdentityCustomRoleV3DataSource_basic (43.33s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 43.360s
```

add data_source_flexibleengine_identity_custom_role_v3

---

flexibleengine/diff_suppress_funcs.go
flexibleengine/resource_flexibleengine_lb_certificate_v2.go
flexibleengine/resource_flexibleengine_lb_listener_v2.go
flexibleengine/resource_flexibleengine_lb_listener_v2_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/certificates/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/listeners/results.go
vendor/modules.txt
website/docs/r/lb_listener_v2.html.markdown

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLBV2Listener_withCert'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2Listener_withCert -timeout 720m
=== RUN   TestAccLBV2Listener_withCert
--- PASS: TestAccLBV2Listener_withCert (59.03s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 59.046s
```

Add http2_enable parameter in lb_listener_v2 resource

---

flexibleengine/resource_flexibleengine_sfs_file_system_v2.go
flexibleengine/resource_flexibleengine_sfs_file_system_v2_test.go

if `access_type` and `access_level` are empty in configure, the provider
will set to the default value, so we make them to be computed.
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccSFSFileSystemV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccSFSFileSystemV2_basic -timeout 720m
=== RUN   TestAccSFSFileSystemV2_basic
--- PASS: TestAccSFSFileSystemV2_basic (59.46s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 59.470s
```

Make access_type and access_level to be computed in sfs

---

flexibleengine/resource_flexibleengine_dcs_instance_v1.go
flexibleengine/resource_flexibleengine_dcs_instance_v1_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/instances/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/instances/results.go
vendor/modules.txt
website/docs/r/dcs_instance_v1.html.markdown

in this PR, we do the following changes:
- remove the deprecated `subnet_id` param;
- make `instance_type` to be deprecated;
- make `security_group_id` be optional for Redis 4.0 and 5.0 instance
- change type of `capacity` from int to float
- update docs
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDcsInstancesV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDcsInstancesV1_basic -timeout 720m
=== RUN   TestAccDcsInstancesV1_basic
--- PASS: TestAccDcsInstancesV1_basic (446.59s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 446.599s
```

improve on dcs instance resource

---

flexibleengine/resource_flexibleengine_dds_instance_v3.go
flexibleengine/resource_flexibleengine_dds_instance_v3_test.go
website/docs/r/dds_instance_v3.html.markdown

fixes #473 
```
--- PASS: TestAccDDSV3Instance_basic (667.96s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 667.969s
```

support version 4.0 in dds resource

---

flexibleengine/resource_flexibleengine_rds_instance_v3.go
flexibleengine/resource_flexibleengine_rds_instance_v3_test.go
website/docs/r/rds_instance_v3.html.markdown

fixes #158 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccRdsInstanceV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccRdsInstanceV3_basic -timeout 720m
=== RUN   TestAccRdsInstanceV3_basic
--- PASS: TestAccRdsInstanceV3_basic (598.25s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 598.257s
```

support fixed_ip into rds instance v3

---

website/docs/r/vpcep_service.html.md

fixes #479 
The documentation for VPC Endpoint Service is wrong. UDP or TCP in port_mapping should be specified with the key `protocol` not `type`.

fix a document error in vpcep service

---

flexibleengine/config.go
flexibleengine/resource_flexibleengine_identity_agency_v3.go

we set the Domain ID in Config, so iam resources can use it directly.
The acc testing result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccIdentityV3Agency_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccIdentityV3Agency_basic -timeout 720m
=== RUN   TestAccIdentityV3Agency_basic
--- PASS: TestAccIdentityV3Agency_basic (37.04s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 37.053s
```

set domain id in provider Config

---

flexibleengine/provider_test.go
flexibleengine/resource_flexibleengine_identity_agency_v3.go
flexibleengine/resource_flexibleengine_identity_agency_v3_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/agency/requests.go
vendor/modules.txt
website/docs/r/identity_agency_v3.html.markdown

fixes #409 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccIdentityV3Agency'
TF_ACC=1 go test ./flexibleengine -v -run TestAccIdentityV3Agency -timeout 720m
=== RUN   TestAccIdentityV3Agency_basic
--- PASS: TestAccIdentityV3Agency_basic (81.68s)
=== RUN   TestAccIdentityV3Agency_domain
--- PASS: TestAccIdentityV3Agency_domain (69.93s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 151.627s
```

support delegated_service_name param in iam agency

---

flexibleengine/resource_flexibleengine_cce_cluster_v3.go
flexibleengine/resource_flexibleengine_cce_cluster_v3_test.go
website/docs/r/cce_cluster_v3.html.md

fixes #257 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCEClusterV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCEClusterV3_basic -timeout 720m
=== RUN   TestAccCCEClusterV3_basic
--- PASS: TestAccCCEClusterV3_basic (1832.13s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine (1832.13s)
```

support authenticating_proxy_ca and kube_proxy_mode for cce cluster

---

flexibleengine/resource_flexibleengine_cce_node_pool.go
flexibleengine/resource_flexibleengine_cce_node_v3.go
flexibleengine/resource_flexibleengine_cce_node_v3_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/clusters/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/cce/v3/nodes/results.go
vendor/modules.txt
website/docs/r/cce_node_pool_v3.html.md
website/docs/r/cce_nodes_v3.html.md

fixes #406 
we can specifies the agency name to provide temporary credentials for CCE node to access other cloud services.
```hcl
extend_param = {
agency_name = "your iam agency name"
}
```
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodesV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCENodesV3_basic -timeout 720m
=== RUN   TestAccCCENodesV3_basic
--- PASS: TestAccCCENodesV3_basic (2167.30s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine (2167.30s)
```

add extend_param to specify agency name for cce node

---

website/docs/r/vpcep_service.html.md

fixes #494 
* `permissions` (Optional) - Specifies the list of accounts to access the VPC endpoint service.
The record is in the `iam:domain::domain_id` format, while `*` allows all users to access the VPC endpoint service.

update description of permissions in vpcep service

---

docs/resources/compute_instance_v2.md
flexibleengine/resource_flexibleengine_compute_instance_v2.go

we marked the `network/name` as a deprecated field, related #498

[compute] deprecate network/name field

---

flexibleengine/config.go
flexibleengine/resource_flexibleengine_s3_bucket_test.go

we can assemble the obs endpoit directly.
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccObsBucket_basic'
--- PASS: TestAccObsBucket_basic (20.46s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 20.476s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccS3Bucket_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccS3Bucket_basic -timeout 720m
=== RUN   TestAccS3Bucket_basic
--- PASS: TestAccS3Bucket_basic (13.91s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengi …
```

update endpoint of obs client

---

flexibleengine/config.go
flexibleengine/provider.go

if `endpoint_type` is invalid, the error message as follows:
```
Error: expected endpoint_type to be one of [public publicURL admin adminURL internal internalURL], got xxx
```
```bash
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccFlexibleEngineVpcV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccFlexibleEngineVpcV1_basic -timeout 720m
=== RUN   TestAccFlexibleEngineVpcV1_basic
--- PASS: TestAccFlexibleEngineVpcV1_basic (43.41s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 43.422s
```

add validation check for endpoint_type

---

flexibleengine/resource_flexibleengine_dns_recordset_v2.go
flexibleengine/resource_flexibleengine_dns_recordset_v2_test.go

fixes #492 
chang the type of records to Set which can ignore the order of records, the testing result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDNSV2RecordSet'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDNSV2RecordSet -timeout 720m
=== RUN   TestAccDNSV2RecordSet_readTTL
=== PAUSE TestAccDNSV2RecordSet_readTTL
=== RUN   TestAccDNSV2RecordSet_private
=== PAUSE TestAccDNSV2RecordSet_private
=== CONT  TestAccDNSV2RecordSet_basic
=== CONT  TestAccDNSV2RecordSet_private
=== CONT  TestAccDNSV2RecordSet_readTTL
--- PASS: TestAccDNSV2RecordSet_readTTL (52.10s)
--- PASS: TestAccDNSV2RecordSet_private (80.78s)
--- PASS: …
```

[dns] change records type to set

---

flexibleengine/resource_flexibleengine_lb_monitor_v2.go
flexibleengine/resource_flexibleengine_lb_monitor_v2_test.go

fixes #517 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLBV2Monitor_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2Monitor_basic -timeout 720m
=== RUN   TestAccLBV2Monitor_basic
--- PASS: TestAccLBV2Monitor_basic (133.44s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 133.457s
```

resolve lb monitor crashing in http(s) type

---

flexibleengine/resource_flexibleengine_dds_instance_v3.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/dds/v3/instances/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/dns/v2/ptrrecords/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/dns/v2/ptrrecords/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/dns/v2/zones/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/dns/v2/zones/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/monitors/requests.go
vendor/modules.txt

* [dds] change type of KeepDays to *int
* [lbaas_v2/monitors] make expected_codes be optional for HTTP(S) types
```
--- PASS: TestAccDDSV3Instance_basic (677.77s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine (677.823s)
```

upgrade huaweicloud/golangsdk

---

docs/resources/ces_alarmrule.md
flexibleengine/config.go
flexibleengine/config_test.go
flexibleengine/resource_flexibleengine_ces_alarmrule.go
flexibleengine/resource_flexibleengine_ces_alarmrule_test.go

fixes #526 
- add alarm_level parameter
- add validatition for parameters
- support importing the resource
- mark insufficientdata_actions as deprecated
- use CesV1Client to get the endpoint
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestCESAlarmRule_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestCESAlarmRule_basic -timeout 720m
=== RUN   TestCESAlarmRule_basic
--- PASS: TestCESAlarmRule_basic (293.41s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 293.426s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccServiceEndpoints_Management'
TF_ACC=1 go test …
```

improve on ces alarm rule resource

---

docs/data-sources/identity_custom_role_v3.md
docs/data-sources/identity_role_v3.md
docs/resources/identity_agency_v3.md
docs/resources/identity_role_v3.md
flexibleengine/data_source_flexibleengine_identity_custom_role_v3.go
flexibleengine/data_source_flexibleengine_identity_role_v3.go
flexibleengine/data_source_flexibleengine_identity_role_v3_test.go
flexibleengine/resource_flexibleengine_identity_agency_v3.go

- add more attributes in data.flexibleengine_identity_role_v3
- update docs
the acceptance testing as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccIdentityV3RoleDataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccIdentityV3RoleDataSource_basic -timeout 720m
=== RUN   TestAccIdentityV3RoleDataSource_basic
--- PASS: TestAccIdentityV3RoleDataSource_basic (11.41s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 11.424s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccIdentityV3Agency_basic'  
TF_ACC=1 go test ./flexibleengine -v -run TestAccIdentityV3Agency_basic -timeout 720m …
```

improve on identity role and agency

---

docs/resources/lb_loadbalancer_v2.md
flexibleengine/resource_flexibleengine_lb_loadbalancer_v2.go
flexibleengine/resource_flexibleengine_lb_loadbalancer_v2_test.go

the acceptance testing result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLBV2LoadBalancer'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2LoadBalancer -timeout 720m
--- PASS: TestAccLBV2LoadBalancer_basic (56.09s)
=== RUN   TestAccLBV2LoadBalancer_secGroup
--- PASS: TestAccLBV2LoadBalancer_secGroup (96.92s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 153.037s
```

feat: support to import loadbalancer resource

---

docs/data-sources/lb_loadbalancer_v2.md
flexibleengine/data_source_flexibleengine_lb_loadbalancer_v2.go
flexibleengine/data_source_flexibleengine_lb_loadbalancer_v2_test.go
flexibleengine/provider.go

fixes #476 
the acceptance testing result as follows:
```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccELBV2LoadbalancerDataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccELBV2LoadbalancerDataSource_basic -timeout 720m
=== RUN   TestAccELBV2LoadbalancerDataSource_basic
--- PASS: TestAccELBV2LoadbalancerDataSource_basic (34.98s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 34.995s
```

add lb_loadbalancer_v2 data source

---

docs/resources/cce_node_pool_v3.md
docs/resources/cce_nodes_v3.md
flexibleengine/resource_flexibleengine_cce_node_pool.go
flexibleengine/resource_flexibleengine_cce_node_pool_test.go
flexibleengine/resource_flexibleengine_cce_node_v3.go
flexibleengine/resource_flexibleengine_cce_node_v3_test.go

fixes #519 
- cce node: deprecated unused parameters and add `status` attribute
- cce node pool: support `tags` and `max_pods` fields
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodesV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCENodesV3_basic -timeout 720m
=== RUN   TestAccCCENodesV3_basic
--- PASS: TestAccCCENodesV3_basic (2112.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 2112.012s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodePool_basic'
=== RUN …
```

improve on cce node and node pool resource

---

docs/resources/as_lifecycle_hook_v1.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_as_lifecycle_hook.go
flexibleengine/resource_flexibleengine_as_lifecycle_hook_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/autoscaling/v1/lifecyclehooks/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/autoscaling/v1/lifecyclehooks/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/autoscaling/v1/lifecyclehooks/urls.go
vendor/github.com/huaweicloud/golangsdk/openstack/cloudeyeservice/alarmrule/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/cloudeyeservice/alarmrule/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/dds/v3/instances/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/dds/v3/instances/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/ecs/v1/cloudservers/results.go
vendor/modules.txt

fixes #525 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccASLifecycleHook_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccASLifecycleHook_basic -timeout 720m
=== RUN   TestAccASLifecycleHook_basic
=== PAUSE TestAccASLifecycleHook_basic
=== CONT  TestAccASLifecycleHook_basic
--- PASS: TestAccASLifecycleHook_basic (112.43s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 112.441s
```

add autoscaling lifecyclehook resource

---

flexibleengine/resource_flexibleengine_vpc_subnet_v1.go
flexibleengine/resource_flexibleengine_vpc_subnet_v1_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/subnets/requests.go
vendor/modules.txt

the acceptance testing result as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccFlexibleEngineVpcSubnetV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccFlexibleEngineVpcSubnetV1_basic -timeout 720m
=== RUN   TestAccFlexibleEngineVpcSubnetV1_basic
--- PASS: TestAccFlexibleEngineVpcSubnetV1_basic (70.15s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 70.163s
```

subnets: Allow DNS Nameservers to be cleared

---

docs/resources/obs_bucket.md
flexibleengine/resource_flexibleengine_obs_bucket.go
flexibleengine/resource_flexibleengine_obs_bucket_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/obs/CHANGELOG
vendor/github.com/huaweicloud/golangsdk/openstack/obs/README.MD
vendor/github.com/huaweicloud/golangsdk/openstack/obs/auth.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/client.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/conf.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/const.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/convert.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/extension.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/http.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/log.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/model.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/pool.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/provider.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/temporary.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/trait.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/transfer.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/util.go
vendor/modules.txt

fixes #505 
the acceptance testing results as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccObsBucket_'
TF_ACC=1 go test ./flexibleengine -v -run TestAccObsBucket_ -timeout 720m
--- PASS: TestAccObsBucket_basic (20.90s)
=== RUN   TestAccObsBucket_multiAZ
--- PASS: TestAccObsBucket_multiAZ (11.44s)
=== RUN   TestAccObsBucket_versioning
--- PASS: TestAccObsBucket_versioning (21.27s)
=== RUN   TestAccObsBucket_logging
--- PASS: TestAccObsBucket_logging (14.54s)
=== RUN   TestAccObsBucket_lifecycle
--- PASS: TestAccObsBucket_lifecycle (11.13s)
=== RUN   TestAccObsBucket_website
--- PASS: TestAccObsBucket_website (11.28s)
=== RUN   TestAccObsBucket_cors
--- PASS: …
```

feat: support to enable multi-AZ mode for OBS bucket

---

flexibleengine/import_flexibleengine_cce_node_test.go
flexibleengine/resource_flexibleengine_cce_node_v3.go
flexibleengine/resource_flexibleengine_cce_node_v3_test.go

- add expandResourceCCE* functions to make the Read more clearly;
- add acc checks for tags
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodeV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCENodeV3_basic -timeout 720m
--- PASS: TestAccCCENodeV3_basic (1975.14s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 1975.151s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodeV3_importBasic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCENodeV3_importBasic -timeout 720m
=== RUN   TestAccCCENodeV3_importBasic
--- PASS: …
```

refactor: add expandResource functions and add more acc checks for cce node

---

docs/resources/cce_node_pool_v3.md
flexibleengine/resource_flexibleengine_cce_node_pool.go
flexibleengine/resource_flexibleengine_cce_node_pool_test.go

fixes #549 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodePool_basic'
=== RUN   TestAccCCENodePool_basic
=== PAUSE TestAccCCENodePool_basic
=== CONT  TestAccCCENodePool_basic
--- PASS: TestAccCCENodePool_basic (2217.30s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 2217.322s
```

cce node pool: make taints and labels be updatable

---

docs/resources/obs_bucket.md
flexibleengine/resource_flexibleengine_obs_bucket.go
flexibleengine/resource_flexibleengine_obs_bucket_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/common/structs/structs.go
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/eips/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/eips/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/client.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/const.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/convert.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/model.go
vendor/github.com/huaweicloud/golangsdk/openstack/obs/trait.go
vendor/modules.txt

fixes #419 
fixes #252 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccObsBucket_basic'
--- PASS: TestAccObsBucket_basic (23.06s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 23.079s
```

support default encryption for an oss bucket

---

flexibleengine/config.go

fixes #548 
When the rds is located in sub project under a region, the provider will use the project id of the region rather than the sub project.
Setting the project id to Config.RegionProjectIDMap will fix it.
This PR wil also update the User-Agent to "terraform-provider-flexibleengine".

config: set RegionProjectIDMap as early as possible

---

docs/resources/waf_domain.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_waf_domain.go
flexibleengine/resource_flexibleengine_waf_domain_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/domains/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/domains/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/domains/urls.go
vendor/modules.txt

related to #533
add new resource **flexibleengine_waf_domain** to manage a WAF domain resource within FlexibleEngine.
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccWafDomainV1'
TF_ACC=1 go test ./flexibleengine -v -run TestAccWafDomainV1 -timeout 720m
=== RUN   TestAccWafDomainV1_basic
=== PAUSE TestAccWafDomainV1_basic
=== RUN   TestAccWafDomainV1_policy
=== PAUSE TestAccWafDomainV1_policy
=== CONT  TestAccWafDomainV1_basic
=== CONT  TestAccWafDomainV1_policy
--- PASS: TestAccWafDomainV1_policy (31.07s)
--- PASS: TestAccWafDomainV1_basic (41.69s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 41.702s
```

waf: add domain resource

---

docs/resources/waf_rule_alarm_masking.md
docs/resources/waf_rule_data_masking.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_waf_rule_alarm_masking.go
flexibleengine/resource_flexibleengine_waf_rule_alarm_masking_test.go
flexibleengine/resource_flexibleengine_waf_rule_data_masking.go
flexibleengine/resource_flexibleengine_waf_rule_data_masking_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/datamasking_rules/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/datamasking_rules/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/datamasking_rules/urls.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/falsealarmmasking_rules/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/falsealarmmasking_rules/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/falsealarmmasking_rules/urls.go
vendor/modules.txt

related to #533 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccWafRuleDataMasking_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccWafRuleDataMasking_basic -timeout 720m
=== RUN   TestAccWafRuleDataMasking_basic
--- PASS: TestAccWafRuleDataMasking_basic (24.66s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 24.673s
```

waf: add alarm_masking and data_masking resources

---

docs/resources/waf_rule_blacklist.md
docs/resources/waf_rule_cc_protection.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_waf_rule_blacklist.go
flexibleengine/resource_flexibleengine_waf_rule_blacklist_test.go
flexibleengine/resource_flexibleengine_waf_rule_cc_protection.go
flexibleengine/resource_flexibleengine_waf_rule_cc_protection_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/ccattackprotection_rules/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/ccattackprotection_rules/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/ccattackprotection_rules/urls.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/whiteblackip_rules/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/whiteblackip_rules/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/whiteblackip_rules/urls.go
vendor/modules.txt

related to #533
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccWafRuleCCAttackProtection_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccWafRuleCCAttackProtection_basic -timeout 720m
=== RUN   TestAccWafRuleCCAttackProtection_basic
--- PASS: TestAccWafRuleCCAttackProtection_basic (22.72s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 22.734s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccWafRuleBlackList_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccWafRuleBlackList_basic -timeout 720m
=== RUN   TestAccWafRuleBlackList_basic
=== PAUSE …
```

waf: add cc attack protection rule and blacklist rule resources

---

docs/resources/waf_rule_precise_protection.md
docs/resources/waf_rule_web_tamper_protection.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_waf_rule_precise_protection.go
flexibleengine/resource_flexibleengine_waf_rule_precise_protection_test.go
flexibleengine/resource_flexibleengine_waf_rule_web_tamper_protection.go
flexibleengine/resource_flexibleengine_waf_rule_web_tamper_protection_test.go
flexibleengine/validators.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/preciseprotection_rules/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/preciseprotection_rules/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/preciseprotection_rules/urls.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/webtamperprotection_rules/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/webtamperprotection_rules/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/waf/v1/webtamperprotection_rules/urls.go
vendor/modules.txt

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccWafRuleWebTamperProtection_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccWafRuleWebTamperProtection_basic -timeout 720m
=== RUN   TestAccWafRuleWebTamperProtection_basic
=== PAUSE TestAccWafRuleWebTamperProtection_basic
=== CONT  TestAccWafRuleWebTamperProtection_basic
--- PASS: TestAccWafRuleWebTamperProtection_basic (13.93s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 13.943s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccWafRulePreciseProtection_basic'
TF_ACC=1 go test ./flexibleengine -v -run …
```

waf: add precise protection rule and web tamper protection rule resource

---

docs/resources/waf_policy.md
flexibleengine/resource_flexibleengine_waf_policy.go
flexibleengine/resource_flexibleengine_waf_policy_test.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccWafPolicyV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccWafPolicyV1_basic -timeout 720m
=== RUN   TestAccWafPolicyV1_basic
=== PAUSE TestAccWafPolicyV1_basic
=== CONT  TestAccWafPolicyV1_basic
--- PASS: TestAccWafPolicyV1_basic (21.59s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 21.606s
```

waf: make full_detection be updatable in policy

---

flexibleengine/resource_flexibleengine_dds_instance_v3.go
flexibleengine/resource_flexibleengine_dds_instance_v3_test.go

fixes #571 
```
--- PASS: TestAccDDSV3Instance_basic (669.03s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 669.044s
```

fix: convert dds port to int

---

docs/resources/vpc_eip_v1.md
flexibleengine/resource_flexibleengine_vpc_eip_v1.go
flexibleengine/resource_flexibleengine_vpc_eip_v1_test.go

fixes #564 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccVpcV1EIP_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccVpcV1EIP_basic -timeout 720m
=== RUN   TestAccVpcV1EIP_basic
--- PASS: TestAccVpcV1EIP_basic (46.82s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 46.837s
```

eip: add tags support

---

docs/index.md
flexibleengine/provider.go

- set tenant_name to region when neither `tenant_name` nor `tenant_id` was specified
- set auth_url to https://iam.{{region}}.prod-cloud-ocb.orange-business.com/v3
- update docs
fixes #569

set default value for tenant_name and auth_url

---

docs/resources/vpc_flow_log_v1.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_vpc_flow_log.go
flexibleengine/resource_flexibleengine_vpc_flow_log_test.go
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/flowlogs/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/flowlogs/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/flowlogs/urls.go
vendor/modules.txt

fixes #451
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccVpcFlowLogV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccVpcFlowLogV1_basic -timeout 720m
=== RUN   TestAccVpcFlowLogV1_basic
=== PAUSE TestAccVpcFlowLogV1_basic
=== CONT  TestAccVpcFlowLogV1_basic
--- PASS: TestAccVpcFlowLogV1_basic (230.74s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 230.761s
```

feat: support vpc flow log resource

---

docs/resources/sfs_file_system_v2.md
flexibleengine/resource_flexibleengine_sfs_file_system_v2.go

fixes #420 
the `host` attribute is an internal attribute which is meaningless for users.
so, drop it.
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccSFSFileSystemV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccSFSFileSystemV2_basic -timeout 720m
=== RUN   TestAccSFSFileSystemV2_basic
--- PASS: TestAccSFSFileSystemV2_basic (55.96s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 55.976s
```

removed host attribute in sfs file system

---

docs/resources/sfs_file_system_v2.md
flexibleengine/resource_flexibleengine_sfs_file_system_v2.go

`share_type` is not defined in schema, and `volume_type` has the same meaning with it, so we can remove it.
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccSFSFileSystemV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccSFSFileSystemV2_basic -timeout 720m
=== RUN   TestAccSFSFileSystemV2_basic
--- PASS: TestAccSFSFileSystemV2_basic (74.79s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 74.800s
```

remove share_type attr in sfs data source

---

flexibleengine/config_test.go
flexibleengine/provider.go
flexibleengine/provider_test.go
flexibleengine/resource_flexibleengine_vpc_v1.go
flexibleengine/resource_flexibleengine_vpc_v1_test.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestProvider'
TF_ACC=1 go test ./flexibleengine -v -run TestProvider -timeout 720m
=== RUN   TestProvider
--- PASS: TestProvider (0.01s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 0.027s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccFlexibleEngineVpcV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccFlexibleEngineVpcV1_basic -timeout 720m
=== RUN   TestAccFlexibleEngineVpcV1_basic
--- PASS: TestAccFlexibleEngineVpcV1_basic (40.75s)
PASS
ok …
```

configure provider with ConfigureContextFunc

---

docs/resources/dli_queue.md
flexibleengine/resource_flexibleengine_dli_queue_v1.go
flexibleengine/resource_flexibleengine_dli_queue_v1_test.go
go.mod
go.sum
vendor/github.com/huaweicloud/golangsdk/openstack/dli/v1/queues/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/dli/v1/queues/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/dli/v1/queues/urls.go
vendor/modules.txt

Dli queue service  support scale and import 
```
make testacc TEST='./flexibleengine' TESTARGS='-run=TestAccDliQueueV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run=TestAccDliQueueV1_basic -timeout 720m
=== RUN   TestAccDliQueueV1_basic
=== PAUSE TestAccDliQueueV1_basic
=== CONT  TestAccDliQueueV1_basic
--- PASS: TestAccDliQueueV1_basic (717.89s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 717.943s
```

add dli queue scale

---

docs/resources/as_group_v1.md
flexibleengine/resource_flexibleengine_as_group_v1.go
flexibleengine/resource_flexibleengine_as_group_v1_test.go
flexibleengine/resource_flexibleengine_as_lifecycle_hook_test.go

fixes #524 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccASV1Group_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccASV1Group_basic -timeout 720m
=== RUN   TestAccASV1Group_basic
--- PASS: TestAccASV1Group_basic (77.88s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 77.890s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccASLifecycleHook_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccASLifecycleHook_basic -timeout 720m
=== RUN   TestAccASLifecycleHook_basic
=== PAUSE TestAccASLifecycleHook_basic
=== CONT  TestAccASLifecycleHook_basic
--- PASS: …
```

fix: support up to six load balancers can be added to an AS group

---

flexibleengine/config.go

when the domain name if not correct, the following error will be raised:
```
Error: Unable to find IAM domain ID with name xxxxx
```

config: add validation of domain name

---

docs/data-sources/compute_flavors_v2.md
docs/resources/compute_instance_v2.md
flexibleengine/data_source_flexibleengine_compute_flavors.go
flexibleengine/data_source_flexibleengine_compute_flavors_test.go
flexibleengine/provider.go
vendor/github.com/chnsz/golangsdk/openstack/ecs/v1/flavors/requests.go
vendor/github.com/chnsz/golangsdk/openstack/ecs/v1/flavors/results.go
vendor/github.com/chnsz/golangsdk/openstack/ecs/v1/flavors/urls.go
vendor/github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/hashcode/hashcode.go
vendor/modules.txt

refer to #560
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccEcsFlavorsDataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccEcsFlavorsDataSource_basic -timeout 720m
=== RUN   TestAccEcsFlavorsDataSource_basic
=== PAUSE TestAccEcsFlavorsDataSource_basic
=== CONT  TestAccEcsFlavorsDataSource_basic
--- PASS: TestAccEcsFlavorsDataSource_basic (9.15s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 9.163s
```

feat: add data source to get available compute flavors

---

docs/data-sources/rds_flavors_v3.md
flexibleengine/data_source_flexibleengine_rds_flavors_v3.go

refer to #560 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccRdsFlavorV3DataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccRdsFlavorV3DataSource_basic -timeout 720m
=== RUN   TestAccRdsFlavorV3DataSource_basic
--- PASS: TestAccRdsFlavorV3DataSource_basic (9.77s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 9.788s
```

feat: add vcpus and memory arguments into rds flavors data source

---

docs/data-sources/compute_bms_flavors_v2.md
flexibleengine/data_source_flexibleengine_compute_bms_flavor_v2.go
flexibleengine/data_source_flexibleengine_compute_bms_flavor_v2_test.go

refer to #560 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccBMSV2FlavorDataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccBMSV2FlavorDataSource_basic -timeout 720m
=== RUN   TestAccBMSV2FlavorDataSource_basic
--- PASS: TestAccBMSV2FlavorDataSource_basic (9.15s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 9.168s
```

feat: support to query an available BMS flavor by vcpus

---

flexibleengine/resource_flexibleengine_cce_cluster_v3.go
flexibleengine/resource_flexibleengine_cce_node_v3.go

the result of acceptance testing is as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodeV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCENodeV3_basic -timeout 720m
--- PASS: TestAccCCENodeV3_basic (748.73s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 748.748s
```

fix(cce): extend delay and pollInterval to get node ID

---

docs/resources/lb_listener_v2.md
flexibleengine/resource_flexibleengine_lb_listener_v2.go
flexibleengine/resource_flexibleengine_lb_listener_v2_test.go
vendor/github.com/chnsz/golangsdk/openstack/elb/v3/listeners/requests.go
vendor/github.com/chnsz/golangsdk/openstack/elb/v3/listeners/results.go
vendor/github.com/chnsz/golangsdk/openstack/elb/v3/listeners/urls.go
vendor/modules.txt

fixes #609
- use ElbV3Client
- deprecate admin_state_up and tenant_id for listener resource
- support to obtain client IP address with `transparent_client_ip_enable`
- add `idle_timeout`, `request_timeout` and `response_timeout` parameters
```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLBV2Listener'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2Listener -timeout 720m
--- PASS: TestAccLBV2Listener_basic (70.15s)
=== RUN   TestAccLBV2Listener_withCert
--- PASS: TestAccLBV2Listener_withCert (51.04s)
=== RUN   TestAccLBV2Listener_v3
--- PASS: TestAccLBV2Listener_v3 (51.59s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleeng …
```

feat: support to obtain client IP address on elb listener

---

flexibleengine/data_source_flexibleengine_vpc_eip_v1.go

```
make testacc TEST='./flexibleengine' TESTARGS='-run=TestAccVpcV1EipDataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run=TestAccVpcV1EipDataSource_basic -timeout 720m
=== RUN   TestAccVpcV1EipDataSource_basic
=== PAUSE TestAccVpcV1EipDataSource_basic
=== CONT  TestAccVpcV1EipDataSource_basic
--- PASS: TestAccVpcV1EipDataSource_basic (54.90s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 54.971s
```

fix(EIP): ignore the parameter if it is empty

---

docs/resources/dis_stream.md
flexibleengine/resource_flexibleengine_dis_stream_v2.go
flexibleengine/resource_flexibleengine_dis_stream_v2_test.go

fixes #620
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDisStreamV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDisStreamV2_basic -timeout 720m
=== RUN   TestAccDisStreamV2_basic
=== PAUSE TestAccDisStreamV2_basic
=== CONT  TestAccDisStreamV2_basic
--- PASS: TestAccDisStreamV2_basic (7.87s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 7.885s
```

enhance: add partitions attribute for dis stream

---

docs/resources/mrs_cluster_v2.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_mrs_cluster_v2.go
flexibleengine/resource_flexibleengine_mrs_cluster_v2_test.go
go.mod
go.sum
vendor/github.com/chnsz/golangsdk/openstack/mrs/v2/clusters/requests.go
vendor/github.com/chnsz/golangsdk/openstack/mrs/v2/clusters/results.go
vendor/github.com/chnsz/golangsdk/openstack/mrs/v2/clusters/urls.go
vendor/github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config/config.go
vendor/github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config/endpoints.go
vendor/github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config/logger.go
vendor/github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/utils/encoding.go
vendor/modules.txt

refer to #659 
the testing results are as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccMrsMapReduceCluster_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccMrsMapReduceCluster_basic -timeout 720m
=== RUN   TestAccMrsMapReduceCluster_basic
=== PAUSE TestAccMrsMapReduceCluster_basic
=== CONT  TestAccMrsMapReduceCluster_basic
--- PASS: TestAccMrsMapReduceCluster_basic (1232.38s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 1232.397s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccMrsMapReduceCluster_analysis'
TF_ACC=1 go test ./flexibleengine -v -run …
```

feat: add new resource flexibleengine_mrs_cluster_v2

---

flexibleengine/config.go
flexibleengine/data_source_flexibleengine_dns_zone_v2_test.go

fixes #664
dnsV2Client is a global client for DNS service, the endpoint is https://dns.{cloud}/v2/
testing result:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDNSV2'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDNSV2 -timeout 720m
=== RUN   TestAccDNSV2PtrRecord_basic
=== PAUSE TestAccDNSV2PtrRecord_basic
=== RUN   TestAccDNSV2RecordSet_readTTL
=== PAUSE TestAccDNSV2RecordSet_readTTL
=== RUN   TestAccDNSV2RecordSet_private
=== PAUSE TestAccDNSV2RecordSet_private
=== RUN   TestAccDNSV2Zone_basic
=== PAUSE TestAccDNSV2Zone_basic
=== RUN   TestAccDNSV2Zone_private
=== PAUSE TestAccDNSV2Zone_private
=== RUN   TestAccDNSV2Zone_readTTL …
```

fix: update endpoint of dnsV2Client

---

docs/resources/identity_provider.md
docs/resources/identity_provider_conversion.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_identity_provider.go
flexibleengine/resource_flexibleengine_identity_provider_conversion.go
flexibleengine/resource_flexibleengine_identity_provider_conversion_test.go
flexibleengine/resource_flexibleengine_identity_provider_test.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/mappings/requests.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/mappings/results.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/mappings/urls.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/metadatas/requests.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/metadatas/results.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/metadatas/urls.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/oidcconfig/requests.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/oidcconfig/results.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/oidcconfig/urls.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/protocols/requests.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/protocols/results.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/protocols/urls.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/providers/requests.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/providers/results.go
vendor/github.com/chnsz/golangsdk/openstack/identity/federatedauth/providers/urls.go
vendor/modules.txt

fixes #553 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccIdentityProvider_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccIdentityProvider_basic -timeout 720m
=== RUN   TestAccIdentityProvider_basic
=== PAUSE TestAccIdentityProvider_basic
=== CONT  TestAccIdentityProvider_basic
--- PASS: TestAccIdentityProvider_basic (12.47s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 12.487s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccIdentityProviderConversion_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccIdentityProviderConversion_basic -timeout 720m …
```

feat: add support to identity provider resources

---

docs/data-sources/dms_product.md
flexibleengine/data_source_flexibleengine_dms_product.go
flexibleengine/data_source_flexibleengine_dms_product_test.go
flexibleengine/provider.go
vendor/github.com/chnsz/golangsdk/openstack/dms/v2/products/requests.go
vendor/github.com/chnsz/golangsdk/openstack/dms/v2/products/results.go
vendor/github.com/chnsz/golangsdk/openstack/dms/v2/products/urls.go
vendor/modules.txt

related to #447, add new data source: **flexibleengine_dms_product**. 
the acceptance testing as follows:
```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDmsProductDataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDmsProductDataSource_basic -timeout 720m
=== RUN   TestAccDmsProductDataSource_basic
=== PAUSE TestAccDmsProductDataSource_basic
=== CONT  TestAccDmsProductDataSource_basic
--- PASS: TestAccDmsProductDataSource_basic (5.80s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 5.816s
```

feat: add dms product data source

---

docs/resources/dms_kafka_instance.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_dms_kafka_instance.go
flexibleengine/resource_flexibleengine_dms_kafka_instance_test.go
go.mod
go.sum
vendor/github.com/chnsz/golangsdk/openstack/dli/v1/queues/requests.go
vendor/github.com/chnsz/golangsdk/openstack/dli/v1/queues/results.go
vendor/github.com/chnsz/golangsdk/openstack/dms/v1/instances/requests.go
vendor/github.com/chnsz/golangsdk/openstack/dms/v1/instances/results.go
vendor/github.com/chnsz/golangsdk/openstack/dms/v1/instances/urls.go
vendor/github.com/chnsz/golangsdk/openstack/ecs/v1/cloudservers/requests.go
vendor/github.com/chnsz/golangsdk/openstack/networking/v1/bandwidths/requests.go
vendor/github.com/chnsz/golangsdk/openstack/networking/v1/bandwidths/results.go
vendor/github.com/chnsz/golangsdk/openstack/networking/v1/eips/requests.go
vendor/github.com/chnsz/golangsdk/openstack/networking/v1/eips/results.go
vendor/modules.txt

related to #447 
add a new resource `flexibleengine_dms_kafka_instance` to manage a DMS Kafka instance within FlexibleEngine.
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDmsKafkaInstance_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDmsKafkaInstance_basic -timeout 720m
--- PASS: TestAccDmsKafkaInstance_basic (383.54s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 383.554s
```

feat: add dms kafka instance resource

---

docs/resources/dms_kafka_topic.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_dms_kafka_topic.go
flexibleengine/resource_flexibleengine_dms_kafka_topic_test.go
go.mod
go.sum
vendor/github.com/chnsz/golangsdk/openstack/dms/v1/topics/doc.go
vendor/github.com/chnsz/golangsdk/openstack/dms/v1/topics/requests.go
vendor/github.com/chnsz/golangsdk/openstack/dms/v1/topics/results.go
vendor/github.com/chnsz/golangsdk/openstack/dms/v1/topics/urls.go
vendor/modules.txt

related to #447 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDmsKafkaTopic_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDmsKafkaTopic_basic -timeout 720m
=== RUN   TestAccDmsKafkaTopic_basic
=== PAUSE TestAccDmsKafkaTopic_basic
=== CONT  TestAccDmsKafkaTopic_basic
--- PASS: TestAccDmsKafkaTopic_basic (363.48s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 363.489s
```

feat: add dms kafka topic resource

---

flexibleengine/resource_flexibleengine_lb_listener_v2.go
flexibleengine/resource_flexibleengine_lb_listener_v2_test.go
flexibleengine/resource_flexibleengine_lb_loadbalancer_v2.go

fixes #680 
the testing result as follows"
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLBV2LoadBalancer_basic'==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2LoadBalancer_basic -timeout 720m
--- PASS: TestAccLBV2LoadBalancer_basic (42.93s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 42.946s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLBV2Listener_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2Listener_basic -timeout 720m
--- PASS: TestAccLBV2Listener_basic (84.22s)
PASS
ok …
```

fix(lb): avoid to request empty body when only update tags

---

flexibleengine/resource_flexibleengine_as_group_v1.go
flexibleengine/resource_flexibleengine_images_image_v2.go

Partial is a legacy function that was used for capturing state of specific
attributes if an update only partially worked. Enabling this flag without
setting any specific keys with the now removed SetPartial has a useful side
effect of preserving all of the resource's previous state. Although confusing,
it has been discovered that during an update when an error is returned, the
proposed config is set into state, even without any calls to d.Set.
In practice this default behavior goes mostly unnoticed since Terraform
refreshes between operations by default. The state situation discussed is
subject to further investigation and potential change. Until then, this
function has been preserved for the specific usecase.

chore: get rid of d.Partial

---

flexibleengine/resource_flexibleengine_blockstorage_volume_v2.go
flexibleengine/resource_flexibleengine_compute_instance_v2.go
flexibleengine/resource_flexibleengine_dns_ptrrecord_v2.go
flexibleengine/resource_flexibleengine_dns_recordset_v2.go
flexibleengine/resource_flexibleengine_dns_recordset_v2_test.go
flexibleengine/resource_flexibleengine_dns_zone_v2.go
flexibleengine/resource_flexibleengine_vpc_subnet_v1.go
flexibleengine/resource_flexibleengine_vpc_subnet_v1_test.go
flexibleengine/resource_flexibleengine_vpc_v1.go
flexibleengine/resource_flexibleengine_vpcep_service.go

fixes #693 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDNSV2RecordSet_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDNSV2RecordSet_basic -timeout 720m
=== CONT  TestAccDNSV2RecordSet_basic
--- PASS: TestAccDNSV2RecordSet_basic (66.84s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 66.854s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDNSV2RecordSet_readTTL'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDNSV2RecordSet_readTTL -timeout 720m
=== RUN …
```

fix: do not update other fields when only tags was changed

---

flexibleengine/data_source_flexibleengine_vpcep_endpoints_test.go

GitHub Actions/build
Check failure on line 18 in flexibleengine/data_source_flexibleengine_vpcep_endpoints_test.go
result of fmt.Sprintf call not used

chore: fix github check annotations

---

flexibleengine/resource_flexibleengine_lb_listener_v2.go
flexibleengine/resource_flexibleengine_lb_listener_v2_test.go
flexibleengine/resource_flexibleengine_lb_loadbalancer_v2.go
flexibleengine/resource_flexibleengine_lb_loadbalancer_v2_test.go
go.mod
go.sum
vendor/github.com/chnsz/golangsdk/openstack/elb/v3/listeners/requests.go
vendor/github.com/chnsz/golangsdk/openstack/networking/v1/vpcs/requests.go
vendor/github.com/chnsz/golangsdk/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
vendor/github.com/chnsz/golangsdk/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go
vendor/github.com/chnsz/golangsdk/pagination/marker.go
vendor/modules.txt

fixes #692 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLBV2LoadBalancer_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2LoadBalancer_basic -timeout 720m
--- PASS: TestAccLBV2LoadBalancer_basic (44.58s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 44.595s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLBV2Listener_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2Listener_basic -timeout 720m
--- PASS: TestAccLBV2Listener_basic (90.20s)
PASS
ok …
```

bugfix(elb): be able to remove a description

---

flexibleengine/config.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_obs_bucket.go
flexibleengine/resource_flexibleengine_obs_bucket_object.go
flexibleengine/resource_flexibleengine_obs_bucket_object_test.go
flexibleengine/resource_flexibleengine_obs_bucket_replication.go
flexibleengine/resource_flexibleengine_obs_bucket_replication_test.go
flexibleengine/resource_flexibleengine_obs_bucket_test.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccObsBucket'
TF_ACC=1 go test ./flexibleengine -v -run TestAccObsBucket -timeout 720m
=== RUN   TestAccObsBucketObject_source
=== PAUSE TestAccObsBucketObject_source
=== RUN   TestAccObsBucketObject_content
=== PAUSE TestAccObsBucketObject_content
=== RUN   TestAccObsBucketReplication_basic
=== PAUSE TestAccObsBucketReplication_basic
=== PAUSE TestAccObsBucket_basic
=== RUN   TestAccObsBucket_multiAZ
=== PAUSE TestAccObsBucket_multiAZ
=== RUN   TestAccObsBucket_versioning
=== PAUSE TestAccObsBucket_versioning
=== RUN   TestAccObsBucket_logging
=== PAUSE TestAccObsBucket_logging
=== RUN …
```

fix(obs): update obs Location when region is not specified

---

flexibleengine/auth_helpers.go
flexibleengine/config.go
flexibleengine/data_source_flexibleengine_s3_bucket_object.go
flexibleengine/data_source_flexibleengine_s3_bucket_object_test.go
flexibleengine/import_flexibleengine_s3_bucket.go
flexibleengine/resource_flexibleengine_obs_bucket.go
flexibleengine/resource_flexibleengine_s3_bucket.go
flexibleengine/resource_flexibleengine_s3_bucket_object.go
flexibleengine/resource_flexibleengine_s3_bucket_object_test.go
flexibleengine/resource_flexibleengine_s3_bucket_policy.go
flexibleengine/resource_flexibleengine_s3_bucket_policy_test.go
flexibleengine/resource_flexibleengine_s3_bucket_test.go
flexibleengine/s3session.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDataSourceS3BucketObject'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDataSourceS3BucketObject -timeout 720m
=== RUN   TestAccDataSourceS3BucketObject_basic
=== PAUSE TestAccDataSourceS3BucketObject_basic
=== RUN   TestAccDataSourceS3BucketObject_readableBody
=== PAUSE TestAccDataSourceS3BucketObject_readableBody
=== RUN   TestAccDataSourceS3BucketObject_allParams
=== PAUSE TestAccDataSourceS3BucketObject_allParams
=== CONT  TestAccDataSourceS3BucketObject_basic
=== CONT  TestAccDataSourceS3BucketObject_allParams
=== CONT  TestAccDataSourceS3BucketObject_readableBody
--- PASS: TestAccDataSourceS3BucketObject_readableBody (138.47s) …
```

refactor(config/s3): put s3 session out of Config struct

---

docs/resources/dcs_instance_v1.md
flexibleengine/config.go
flexibleengine/config_test.go
flexibleengine/data_source_flexibleengine_dcs_az_v1.go
flexibleengine/data_source_flexibleengine_dcs_maintainwindow_v1.go
flexibleengine/data_source_flexibleengine_dcs_product_v1.go
flexibleengine/data_source_flexibleengine_dds_flavor_v3.go
flexibleengine/data_source_flexibleengine_dds_flavors_v3.go
flexibleengine/data_source_flexibleengine_rds_flavors_v1.go
flexibleengine/data_source_flexibleengine_rds_flavors_v1_test.go
flexibleengine/data_source_flexibleengine_rds_flavors_v3.go
flexibleengine/data_source_flexibleengine_rds_flavors_v3_test.go
flexibleengine/resource_flexibleengine_dcs_instance_v1.go
flexibleengine/resource_flexibleengine_dcs_instance_v1_test.go
flexibleengine/resource_flexibleengine_dds_instance_v3.go
flexibleengine/resource_flexibleengine_dds_instance_v3_test.go
flexibleengine/resource_flexibleengine_rds_configuration_v3.go
flexibleengine/resource_flexibleengine_rds_configuration_v3_test.go
flexibleengine/resource_flexibleengine_rds_instance_v1.go
flexibleengine/resource_flexibleengine_rds_instance_v1_test.go
flexibleengine/resource_flexibleengine_rds_instance_v3_test.go
flexibleengine/resource_flexibleengine_rds_read_replica_v3_test.go

```
--- PASS: TestAccDDSV3Instance_basic (885.68s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 885.740s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDDSFlavor'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDDSFlavor -timeout 720m
=== RUN   TestAccDDSFlavorV3DataSource_basic
--- PASS: TestAccDDSFlavorV3DataSource_basic (63.11s)
=== RUN   TestAccDDSFlavorsV3DataSource_basic
--- …
```

chore: update RDS DDS and DCS service endpoints

---

flexibleengine/config.go
flexibleengine/config_test.go
flexibleengine/data_source_flexibleengine_lb_certificates_v2.go
flexibleengine/data_source_flexibleengine_lb_certificates_v2_test.go
flexibleengine/data_source_flexibleengine_lb_loadbalancer_v2.go
flexibleengine/lb_v2_shared.go
flexibleengine/resource_flexibleengine_lb_certificate_v2.go
flexibleengine/resource_flexibleengine_lb_certificate_v2_test.go
flexibleengine/resource_flexibleengine_lb_l7policy_v2.go
flexibleengine/resource_flexibleengine_lb_l7policy_v2_test.go
flexibleengine/resource_flexibleengine_lb_l7rule_v2.go
flexibleengine/resource_flexibleengine_lb_l7rule_v2_test.go
flexibleengine/resource_flexibleengine_lb_loadbalancer_v2.go
flexibleengine/resource_flexibleengine_lb_loadbalancer_v2_test.go
flexibleengine/resource_flexibleengine_lb_member_v2.go
flexibleengine/resource_flexibleengine_lb_member_v2_test.go
flexibleengine/resource_flexibleengine_lb_monitor_v2.go
flexibleengine/resource_flexibleengine_lb_monitor_v2_test.go
flexibleengine/resource_flexibleengine_lb_pool_v2.go
flexibleengine/resource_flexibleengine_lb_pool_v2_test.go
flexibleengine/resource_flexibleengine_lb_whitelist_v2.go
flexibleengine/resource_flexibleengine_lb_whitelist_v2_test.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLBV2LoadBalancer'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2LoadBalancer -timeout 720m
--- PASS: TestAccLBV2LoadBalancer_basic (137.30s)
=== RUN   TestAccLBV2LoadBalancer_secGroup
--- PASS: TestAccLBV2LoadBalancer_secGroup (202.89s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 340.237s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLBV2Listener_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2Listener_basic -timeout 720m
--- PASS: …
```

chore: update enhanced lb service endpoint

---

flexibleengine/config.go
flexibleengine/config_test.go
flexibleengine/resource_flexibleengine_dws_cluster_v1.go
flexibleengine/resource_flexibleengine_dws_cluster_v1_test.go
flexibleengine/resource_flexibleengine_mls_instance_v1_test.go
flexibleengine/resource_flexibleengine_mrs_cluster_v1_test.go
flexibleengine/resource_flexibleengine_smn_subscription_v2_test.go
flexibleengine/resource_flexibleengine_smn_topic_v2_test.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccSMNV2'
TF_ACC=1 go test ./flexibleengine -v -run TestAccSMNV2 -timeout 720m
=== RUN   TestAccSMNV2Subscription_basic
--- PASS: TestAccSMNV2Subscription_basic (53.57s)
=== RUN   TestAccSMNV2Topic_basic
--- PASS: TestAccSMNV2Topic_basic (91.67s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 145.298s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccMRSV1Cluster_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccMRSV1Cluster_basic -timeout 720m
=== RUN   TestAccMRSV1Cluster_basic
--- PASS: TestAccMRSV1Cluster_basic (1444.22s)
PASS
ok …
```

chore: update data analysis services endpoints

---

docs/resources/elb_backend.md
docs/resources/elb_health.md
docs/resources/elb_listener.md
docs/resources/elb_loadbalancer.md
flexibleengine/config.go
flexibleengine/config_test.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_elb_backend.go
flexibleengine/resource_flexibleengine_elb_backend_test.go
flexibleengine/resource_flexibleengine_elb_health.go
flexibleengine/resource_flexibleengine_elb_health_test.go
flexibleengine/resource_flexibleengine_elb_listener.go
flexibleengine/resource_flexibleengine_elb_listener_test.go
flexibleengine/resource_flexibleengine_elb_loadbalancer.go
flexibleengine/resource_flexibleengine_elb_loadbalancer_test.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccELB'
TF_ACC=1 go test ./flexibleengine -v -run TestAccELB -timeout 720m
=== RUN   TestAccELBV2LoadbalancerDataSource_basic
--- PASS: TestAccELBV2LoadbalancerDataSource_basic (81.07s)
=== RUN   TestAccELBBackend_basic
provider_test.go:111: This environment does not support deprecated tests
--- SKIP: TestAccELBBackend_basic (0.01s)
=== RUN   TestAccELBHealth_basic
provider_test.go:111: This environment does not support deprecated tests
--- SKIP: TestAccELBHealth_basic (0.00s)
=== RUN   TestAccELBListener_basic
provider_test.go:111: This environment does not support deprecated tests
--- SKIP: TestAccELBListener_basic (0.00s)
=== RUN   TestAccELBLoadBalancer_basic …
```

deprecate classic load balancers as they are no longer provided

---

docs/resources/drs_replication_v2.md
docs/resources/drs_replicationconsistencygroup_v2.md
flexibleengine/config.go
flexibleengine/config_test.go
flexibleengine/resource_flexibleengine_drs_replication_v2.go
flexibleengine/resource_flexibleengine_drs_replication_v2_test.go
flexibleengine/resource_flexibleengine_drs_replicationconsistencygroup_v2.go
flexibleengine/resource_flexibleengine_drs_replicationconsistencygroup_v2_test.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDRSV2Replication'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDRSV2Replication -timeout 720m
=== RUN   TestAccDRSV2Replication_basic
provider_test.go:111: This environment does not support deprecated tests
--- SKIP: TestAccDRSV2Replication_basic (0.00s)
=== RUN   TestAccDRSV2ReplicationConsistencyGroup_basic
provider_test.go:111: This environment does not support deprecated tests
--- SKIP: TestAccDRSV2ReplicationConsistencyGroup_basic (0.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 0.047s
```
**issue:**
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDRSV2Replication_basic'
==> Checking that …
```

deprecate DRS service as the APIs are not exist

---

flexibleengine/config.go
flexibleengine/config_test.go
flexibleengine/data_source_flexibleengine_nat_gateway_v2.go
flexibleengine/resource_flexibleengine_css_cluster_v1.go
flexibleengine/resource_flexibleengine_css_cluster_v1_test.go
flexibleengine/resource_flexibleengine_css_snapshot_v1.go
flexibleengine/resource_flexibleengine_css_snapshot_v1_test.go
flexibleengine/resource_flexibleengine_nat_dnat_rule_v2.go
flexibleengine/resource_flexibleengine_nat_dnat_rule_v2_test.go
flexibleengine/resource_flexibleengine_nat_gateway_v2.go
flexibleengine/resource_flexibleengine_nat_gateway_v2_test.go
flexibleengine/resource_flexibleengine_nat_snat_rule_v2.go
flexibleengine/resource_flexibleengine_nat_snat_rule_v2_test.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccNatGateway'
TF_ACC=1 go test ./flexibleengine -v -run TestAccNatGateway -timeout 720m
=== RUN   TestAccNatGatewayDataSource_basic
=== PAUSE TestAccNatGatewayDataSource_basic
=== RUN   TestAccNatGateway_basic
=== PAUSE TestAccNatGateway_basic
=== CONT  TestAccNatGatewayDataSource_basic
=== CONT  TestAccNatGateway_basic
--- PASS: TestAccNatGatewayDataSource_basic (119.37s)
--- PASS: TestAccNatGateway_basic (177.51s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 177.579s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccNatSnatRule_basic'
TF_ACC=1 go test …
```

chore: update nat gateway and CSS service endpoints

---

flexibleengine/config.go
flexibleengine/config_test.go
flexibleengine/data_source_flexibleengine_dns_zone_v2.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_dns_ptrrecord_v2.go
flexibleengine/resource_flexibleengine_dns_ptrrecord_v2_test.go
flexibleengine/resource_flexibleengine_dns_recordset_v2.go
flexibleengine/resource_flexibleengine_dns_recordset_v2_test.go
flexibleengine/resource_flexibleengine_dns_zone_v2.go
flexibleengine/resource_flexibleengine_dns_zone_v2_test.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDNSV2'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDNSV2 -timeout 720m
=== RUN   TestAccDNSV2PtrRecord_basic
=== PAUSE TestAccDNSV2PtrRecord_basic
=== RUN   TestAccDNSV2RecordSet_readTTL
=== PAUSE TestAccDNSV2RecordSet_readTTL
=== RUN   TestAccDNSV2RecordSet_private
=== PAUSE TestAccDNSV2RecordSet_private
=== RUN   TestAccDNSV2Zone_basic
=== PAUSE TestAccDNSV2Zone_basic
=== RUN   TestAccDNSV2Zone_private
=== PAUSE TestAccDNSV2Zone_private
=== RUN   TestAccDNSV2Zone_readTTL
=== PAUSE TestAccDNSV2Zone_readTTL
=== CONT  TestAccDNSV2PtrRecord_basic
=== CONT  TestAccDNSV2Zone_basic
=== CONT …
```

chore: update DNS service endpoint

---

flexibleengine/config.go
flexibleengine/config_test.go
flexibleengine/data_source_flexibleengine_identity_custom_role_v3.go
flexibleengine/data_source_flexibleengine_identity_project_v3.go
flexibleengine/data_source_flexibleengine_identity_role_v3.go
flexibleengine/resource_flexibleengine_identity_agency_v3.go
flexibleengine/resource_flexibleengine_identity_agency_v3_test.go
flexibleengine/resource_flexibleengine_identity_group_membership_v3.go
flexibleengine/resource_flexibleengine_identity_group_membership_v3_test.go
flexibleengine/resource_flexibleengine_identity_group_v3.go
flexibleengine/resource_flexibleengine_identity_group_v3_test.go
flexibleengine/resource_flexibleengine_identity_project_v3.go
flexibleengine/resource_flexibleengine_identity_project_v3_test.go
flexibleengine/resource_flexibleengine_identity_role_assignment_v3.go
flexibleengine/resource_flexibleengine_identity_role_assignment_v3_test.go
flexibleengine/resource_flexibleengine_identity_role_v3.go
flexibleengine/resource_flexibleengine_identity_role_v3_test.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccIdentityV3Agency'
TF_ACC=1 go test ./flexibleengine -v -run TestAccIdentityV3Agency -timeout 720m
=== RUN   TestAccIdentityV3Agency_basic
--- PASS: TestAccIdentityV3Agency_basic (167.10s)
=== RUN   TestAccIdentityV3Agency_domain
--- PASS: TestAccIdentityV3Agency_domain (230.34s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 397.519s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccIdentityRole'
TF_ACC=1 go test ./flexibleengine -v -run TestAccIdentityRole -timeout 720m
=== RUN   TestAccIdentityRoleAssignment_basic
--- PASS: …
```

chore: update IAM service endpoint

---

flexibleengine/config.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_dis_stream_v2_test.go
flexibleengine/resource_flexibleengine_dli_queue_v1_test.go
flexibleengine/resource_flexibleengine_dms_kafka_instance_test.go
flexibleengine/resource_flexibleengine_dms_kafka_topic_test.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccServiceEndpoints'
TF_ACC=1 go test ./flexibleengine -v -run TestAccServiceEndpoints -timeout 720m
=== RUN   TestAccServiceEndpoints_Global
config_test.go:42: Identity v3 endpoint:     https://iam.eu-west-0.prod-cloud-ocb.orange-business.com/v3/
config_test.go:42: IAM v3.0 endpoint:        https://iam.eu-west-0.prod-cloud-ocb.orange-business.com/v3.0/
--- PASS: TestAccServiceEndpoints_Global (3.76s)
=== RUN   TestAccServiceEndpoints_Management
config_test.go:42: CTS endpoint:     https://cts.eu-west-0.prod-cloud-ocb.orange-business.com/v1.0/{{project_id}}/
config_test.go:42: CES endpoint:     https://ces.eu-west-0.prod-cloud-ocb.orange-business.com/V1.0/{{project_id}}/ …
```

feat(conf): make Config struct as the alias of huaweicloud Config

---

flexibleengine/config_test.go
flexibleengine/provider.go

`cloud` parameter can specify the endpoint of cloud, and defaults to prod-cloud-ocb.orange-business.com.
usage:
```
provider "flexibleengine" {
...
cloud = "your_cloud_endpoint.com"
}
```

feat: support cloud parameter in provider

---

docs/data-sources/cts_tracker_v1.md
docs/resources/cts_tracker_v1.md
flexibleengine/data_source_flexibleengine_cts_tracker_v1.go
flexibleengine/data_source_flexibleengine_cts_tracker_v1_test.go
flexibleengine/resource_flexibleengine_cts_tracker_v1.go
flexibleengine/resource_flexibleengine_cts_tracker_v1_test.go
flexibleengine/resource_flexibleengine_obs_bucket.go

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCTSTrackerV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCTSTrackerV1_basic -timeout 720m
=== RUN   TestAccCTSTrackerV1_basic
--- PASS: TestAccCTSTrackerV1_basic (108.28s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 108.338s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCTSTrackerV1DataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCTSTrackerV1DataSource_basic -timeout 720m
=== RUN   TestAccCTSTrackerV1DataSource_basic
--- PASS: TestAccCTSTrackerV1DataSource_basic (93.52s)
PASS
ok …
```

fix(cts): check length to avoid index out of range

---

docs/data-sources/fgs_dependencies.md
docs/resources/fgs_dependency.md
docs/resources/fgs_function.md
docs/resources/fgs_trigger.md
flexibleengine/data_source_flexibleengine_fgs_dependencies_test.go
flexibleengine/provider.go
flexibleengine/provider_test.go
flexibleengine/resource_flexibleengine_fgs_dependency_test.go
flexibleengine/resource_flexibleengine_fgs_function_test.go
flexibleengine/resource_flexibleengine_fgs_trigger_test.go

fixes #691 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccFgsV2Function_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccFgsV2Function_basic -timeout 720m
=== RUN   TestAccFgsV2Function_basic
=== PAUSE TestAccFgsV2Function_basic
=== CONT  TestAccFgsV2Function_basic
--- PASS: TestAccFgsV2Function_basic (73.44s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 73.514s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccFgsV2Function_text'
TF_ACC=1 go test ./flexibleengine -v -run TestAccFgsV2Function_text -timeout 720m
=== RUN   TestAccFgsV2Function_text
=== PAUSE TestAccFgsV2Function_text
=== …
```

feat: support FunctionGraph service

---

flexibleengine/resource_flexibleengine_ces_alarmrule.go

fixes #737 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestCESAlarmRule_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestCESAlarmRule_basic -timeout 720m
=== RUN   TestCESAlarmRule_basic
--- PASS: TestCESAlarmRule_basic (235.92s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 236.003s
```

fix(ces): add contion.0.suppress_duration attribute

---

flexibleengine/resource_flexibleengine_as_configuration_v1.go
flexibleengine/resource_flexibleengine_cts_tracker_v1.go
go.mod
go.sum

fixes #738 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccASV1Configuration_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccASV1Configuration_basic -timeout 720m
=== RUN   TestAccASV1Configuration_basic
--- PASS: TestAccASV1Configuration_basic (47.32s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 47.411s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCTSTrackerV1_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCTSTrackerV1_basic -timeout 720m
=== RUN   TestAccCTSTrackerV1_basic
--- PASS: TestAccCTSTrackerV1_basic (85.63s)
PASS
ok …
```

fix(cts): only filter trckers by name

---

flexibleengine/acceptance/acceptance.go
flexibleengine/acceptance/data_source_flexibleengine_fgs_dependencies_test.go
flexibleengine/acceptance/resource_flexibleengine_fgs_dependency_test.go
flexibleengine/acceptance/resource_flexibleengine_fgs_function_test.go
flexibleengine/acceptance/resource_flexibleengine_fgs_trigger_test.go

```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccFgsV2Function_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccFgsV2Function_basic -timeout 720m
=== RUN   TestAccFgsV2Function_basic
=== PAUSE TestAccFgsV2Function_basic
=== CONT  TestAccFgsV2Function_basic
--- PASS: TestAccFgsV2Function_basic (77.56s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      77.646s
$
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccFunctionGraphTrigger_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccFunctionGraphTrigger_basic -timeout 720m
=== RUN …
```

chore: add acceptance package

---

docs/resources/vpc_v1.md
flexibleengine/acceptance/resource_flexibleengine_vpc_v1_test.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_vpc_v1.go

fixes #700 
```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccFlexibleEngineVpcV1'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccFlexibleEngineVpcV1 -timeout 720m
=== RUN   TestAccFlexibleEngineVpcV1_basic
=== PAUSE TestAccFlexibleEngineVpcV1_basic
=== RUN   TestAccFlexibleEngineVpcV1_secondaryCIDR
=== PAUSE TestAccFlexibleEngineVpcV1_secondaryCIDR
=== CONT  TestAccFlexibleEngineVpcV1_basic
=== CONT  TestAccFlexibleEngineVpcV1_secondaryCIDR
--- PASS: TestAccFlexibleEngineVpcV1_basic (111.79s)
--- PASS: TestAccFlexibleEngineVpcV1_secondaryCIDR (115.43s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      115.687s
$ make testacc …
```

feat(vpc): support description and secondary_cidr arguments

---

docs/resources/as_group_v1.md
flexibleengine/resource_flexibleengine_as_group_v1.go
flexibleengine/resource_flexibleengine_as_group_v1_test.go

fixes #701 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccASV1Group_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccASV1Group_basic -timeout 720m
=== RUN   TestAccASV1Group_basic
=== PAUSE TestAccASV1Group_basic
=== CONT  TestAccASV1Group_basic
--- PASS: TestAccASV1Group_basic (113.94s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 114.002s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccASGroup_forceDelete'
TF_ACC=1 go test ./flexibleengine -v -run TestAccASGroup_forceDelete -timeout 720m
=== RUN   TestAccASGroup_forceDelete
=== PAUSE TestAccASGroup_forceDelete
=== CONT …
```

feat: support to forcibly delete an AS group

---

docs/resources/networking_secgroup_rule_v2.md
flexibleengine/resource_flexibleengine_networking_secgroup_rule_v2.go
flexibleengine/resource_flexibleengine_networking_secgroup_rule_v2_test.go
flexibleengine/validators.go

fixes #747 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccNetworkingV2SecGroupRule'
TF_ACC=1 go test ./flexibleengine -v -run TestAccNetworkingV2SecGroupRule -timeout 720m
=== RUN   TestAccNetworkingV2SecGroupRule_basic
=== PAUSE TestAccNetworkingV2SecGroupRule_basic
=== RUN   TestAccNetworkingV2SecGroupRule_remoteGroup
=== PAUSE TestAccNetworkingV2SecGroupRule_remoteGroup
=== RUN   TestAccNetworkingV2SecGroupRule_ipv6
=== PAUSE TestAccNetworkingV2SecGroupRule_ipv6
=== RUN   TestAccNetworkingV2SecGroupRule_numericProtocol
=== PAUSE TestAccNetworkingV2SecGroupRule_numericProtocol
=== CONT  TestAccNetworkingV2SecGroupRule_basic
=== CONT  TestAccNetworkingV2SecGroupRule_numericProtocol
=== CONT …
```

fix: add validation for secgroup rule remote_ip_prefix

---

docs/resources/nat_dnat_rule_v2.md
flexibleengine/resource_flexibleengine_nat_dnat_rule_v2.go
flexibleengine/resource_flexibleengine_nat_dnat_rule_v2_test.go

fixes #750 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccNatDnat'
TF_ACC=1 go test ./flexibleengine -v -run TestAccNatDnat -timeout 720m
=== RUN   TestAccNatDnat_basic
=== PAUSE TestAccNatDnat_basic
=== RUN   TestAccNatDnat_protocol
=== PAUSE TestAccNatDnat_protocol
=== CONT  TestAccNatDnat_basic
=== CONT  TestAccNatDnat_protocol
--- PASS: TestAccNatDnat_basic (158.75s)
--- PASS: TestAccNatDnat_protocol (159.98s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 160.072s
```

feat: support description field of DNAT rule

---

docs/data-sources/cbr_vaults.md
docs/resources/cbr_policy.md
docs/resources/cbr_vault.md
flexibleengine/acceptance/acceptance.go
flexibleengine/acceptance/data_source_flexibleengine_cbr_vaults_test.go
flexibleengine/acceptance/resource_flexibleengine_cbr_policy_test.go
flexibleengine/acceptance/resource_flexibleengine_cbr_vault_test.go
flexibleengine/provider.go
go.mod
go.sum

fixes #754 
```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccCBRV3Vault_BasicServer'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccCBRV3Vault_BasicServer -timeout 720m
=== RUN   TestAccCBRV3Vault_BasicServer
=== PAUSE TestAccCBRV3Vault_BasicServer
=== CONT  TestAccCBRV3Vault_BasicServer
--- PASS: TestAccCBRV3Vault_BasicServer (341.52s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      341.610s
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccCBRV3Policy'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccCBRV3Policy -timeout 720m
=== RUN …
```

feat: add CBR vault and policy resource

---

flexibleengine/resource_flexibleengine_lts_group.go
go.mod
go.sum

fixes #764 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLTSGroupV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLTSGroupV2_basic -timeout 720m
=== RUN   TestAccLTSGroupV2_basic
=== PAUSE TestAccLTSGroupV2_basic
=== CONT  TestAccLTSGroupV2_basic
--- PASS: TestAccLTSGroupV2_basic (49.11s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 49.167s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLTSTopicV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLTSTopicV2_basic -timeout 720m
=== RUN   TestAccLTSTopicV2_basic
=== PAUSE TestAccLTSTopicV2_basic
=== CONT  TestAccLTSTopicV2_basic …
```

lts: fix an issue caused by API

---

docs/resources/api_gateway_api.md
docs/resources/api_gateway_group.md
flexibleengine/acceptance/resource_flexibleengine_api_gateway_api_test.go
flexibleengine/acceptance/resource_flexibleengine_api_gateway_group_test.go
flexibleengine/provider.go

new resource:
**flexibleengine_api_gateway_api**
**flexibleengine_api_gateway_group**
```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccApiGatewayGroup_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccApiGatewayGroup_basic -timeout 720m
=== RUN   TestAccApiGatewayGroup_basic
=== PAUSE TestAccApiGatewayGroup_basic
=== CONT  TestAccApiGatewayGroup_basic
--- PASS: TestAccApiGatewayGroup_basic (90.52s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      90.60
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccApiGatewayAPI_basic'
TF_ACC=1 go test …
```

feat(apigw): add group and api resources

---

docs/resources/cce_node_pool_v3.md
docs/resources/cce_node_v3.md
flexibleengine/resource_flexibleengine_cce_node_pool.go
flexibleengine/resource_flexibleengine_cce_node_v3.go
flexibleengine/resource_flexibleengine_cce_node_v3_test.go

add `data_volumes.*.kms_key_id` to support encrypt a data volume.
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodeV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCENodeV3_basic -timeout 720m
--- PASS: TestAccCCENodeV3_basic (878.21s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 878.290s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodeV3_data_volume_encryption'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCENodeV3_data_volume_encryption -timeout 720m
=== RUN   TestAccCCENodeV3_data_volume_encryption
=== PAUSE …
```

feat(cce): support data volume encryption in cce node and pool

---

docs/data-sources/enterprise_project.md
docs/resources/enterprise_project.md
flexibleengine/acceptance/data_source_flexibleengine_enterprise_project_test.go
flexibleengine/acceptance/resource_flexibleengine_enterprise_project_test.go
flexibleengine/provider.go

```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccEnterpriseProject_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccEnterpriseProject_basic -timeout 720m
=== RUN   TestAccEnterpriseProject_basic
=== PAUSE TestAccEnterpriseProject_basic
=== CONT  TestAccEnterpriseProject_basic
--- PASS: TestAccEnterpriseProject_basic (75.40s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      75.522s
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccEnterpriseProjectDataSource_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run …
```

feat(eps) support enterprise management service

---

docs/data-sources/elb_certificate.md
docs/resources/elb_certificate.md
docs/resources/elb_ipgroup.md
flexibleengine/acceptance/data_source_flexibleengine_elb_certificate_test.go
flexibleengine/acceptance/resource_flexibleengine_elb_certificate_test.go
flexibleengine/acceptance/resource_flexibleengine_elb_ipgroup_test.go
flexibleengine/provider.go

new resource:
* flexibleengine_elb_certificate
* flexibleengine_elb_ipgroup
new data source:
* flexibleengine_elb_certificate
```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccElbV3IpGroup_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccElbV3IpGroup_basic -timeout 720m
=== RUN   TestAccElbV3IpGroup_basic
=== PAUSE TestAccElbV3IpGroup_basic
=== CONT  TestAccElbV3IpGroup_basic
--- PASS: TestAccElbV3IpGroup_basic (92.86s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      93.105s
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccElbV3Certificate' …
```

feat(elb): add elb ipgroup and certificate resource

---

docs/resources/compute_instance_v2.md
flexibleengine/resource_flexibleengine_compute_instance_v2.go
flexibleengine/resource_flexibleengine_compute_instance_v2_test.go
flexibleengine/validators.go

the tags validation is not correct, should be removed.
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccComputeV2Instance_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccComputeV2Instance_basic -timeout 720m
=== RUN   TestAccComputeV2Instance_basic
--- PASS: TestAccComputeV2Instance_basic (145.58s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 145.693s
```

fix: remove tags validation of compute instance

---

docs/resources/dms_kafka_instance.md
flexibleengine/resource_flexibleengine_dms_kafka_instance.go
flexibleengine/resource_flexibleengine_dms_kafka_instance_test.go
go.mod
go.sum

```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDmsKafkaInstance_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDmsKafkaInstance_basic -timeout 720m
--- PASS: TestAccDmsKafkaInstance_basic (956.31s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 956.403s
```

feat(dms/kafka) support manager user and password

---

docs/resources/as_lifecycle_hook_v1.md
docs/resources/cce_node_pool_v3.md
docs/resources/compute_floatingip_associate_v2.md
docs/resources/css_snapshot_v1.md
docs/resources/dns_recordset_v2.md
docs/resources/mrs_job_v2.md
docs/resources/sfs_access_rule_v2.md

Some documentations don't render properly on registry website, for example :
and the associated mardown :
```md
terraform import flexibleengine_cce_node_pool_v3.node_pool_1 <cluster-id>/<node_pool-id>  # it's missing the "cluster id" & "nodepool id" parts
```
I tested `{ }` renders properly (on https://registry.terraform.io/tools/doc-preview)

docs: fix ids in "import" sections that don't properly render on registry website

---

docs/data-sources/networking_port.md
flexibleengine/acceptance/data_source_flexibleengine_networking_port_v2_test.go
flexibleengine/config.go
flexibleengine/provider.go
go.mod
go.sum
main.go

add new data_source networking port
Test result:
```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccNetworkingV2PortDataSource_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccNetworkingV2PortDataSource_basic -timeout 720m
=== RUN   TestAccNetworkingV2PortDataSource_basic
=== PAUSE TestAccNetworkingV2PortDataSource_basic
=== CONT  TestAccNetworkingV2PortDataSource_basic
--- PASS: TestAccNetworkingV2PortDataSource_basic (21.13s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      21.266s
```

feat(vpc): add new data_source networking port

---

docs/resources/vpc_eip_associate.md
flexibleengine/acceptance/resource_flexibleengine_vpc_eip_associate_test.go
flexibleengine/provider.go

```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccEIPAssociate_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccEIPAssociate_basic -timeout 720m
=== RUN   TestAccEIPAssociate_basic
=== PAUSE TestAccEIPAssociate_basic
=== CONT  TestAccEIPAssociate_basic
--- PASS: TestAccEIPAssociate_basic (194.06s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      194.134s
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccEIPAssociate_port'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccEIPAssociate_port -timeout 720m
=== …
```

feat: support vpc_eip_associate resource

---

docs/data-sources/identity_group.md
docs/data-sources/identity_users.md
flexibleengine/acceptance/data_source_flexibleengine_identity_group_test.go
flexibleengine/acceptance/data_source_flexibleengine_identity_users_test.go
flexibleengine/provider.go

fixes #214 
new data source:
+ flexibleengine_identity_group
+ flexibleengine_identity_users
```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccIdentityUsersDataSource_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccIdentityUsersDataSource_basic -timeout 720m
=== RUN   TestAccIdentityUsersDataSource_basic
=== PAUSE TestAccIdentityUsersDataSource_basic
=== CONT  TestAccIdentityUsersDataSource_basic
--- PASS: TestAccIdentityUsersDataSource_basic (77.18s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      77.314s
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run …
```

feat(iam): support identity group and users data source

---

docs/resources/cce_node_pool_v3.md
flexibleengine/resource_flexibleengine_cce_node_pool.go

fixes #787 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodePool_basic'
=== RUN   TestAccCCENodePool_basic
=== PAUSE TestAccCCENodePool_basic
=== CONT  TestAccCCENodePool_basic
--- PASS: TestAccCCENodePool_basic (1015.55s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 1015.750s
```

fix(cce/node_pool): add Synchronized into pending list

---

docs/data-sources/smn_topics.md
flexibleengine/acceptance/data_source_flexibleengine_smn_topics_test.go
flexibleengine/provider.go

fixes #804 
the result of acceptance as follows:
```
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccDataTopics_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccDataTopics_basic -timeout 720m
=== RUN   TestAccDataTopics_basic
=== PAUSE TestAccDataTopics_basic
=== CONT  TestAccDataTopics_basic
--- PASS: TestAccDataTopics_basic (27.50s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      27.591s
```

feat(smn): add data source to retrieve topics

---

.github/workflows/ci.yaml
docs/data-sources/sfs_turbos.md
flexibleengine/acceptance/data_source_flexibleengine_sfs_turbos_test.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_dli_queue_v1.go
flexibleengine/resource_flexibleengine_mrs_cluster_v2.go
flexibleengine/resource_flexibleengine_mrs_job_v2.go
flexibleengine/structure.go
go.mod
go.sum

fixes #767 
```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccTurbosDataSource_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccTurbosDataSource_basic -timeout 720m
=== RUN   TestAccTurbosDataSource_basic
=== PAUSE TestAccTurbosDataSource_basic
=== CONT  TestAccTurbosDataSource_basic
--- PASS: TestAccTurbosDataSource_basic (401.54s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      401.605s
```

feat(sfs): add data source to retrieve sfs turbos

---

docs/data-sources/cce_cluster_v3.md
flexibleengine/data_source_flexibleengine_cce_cluster_v3.go
flexibleengine/data_source_flexibleengine_cce_cluster_v3_test.go
flexibleengine/resource_flexibleengine_cce_cluster_v3.go
flexibleengine/resource_flexibleengine_cce_cluster_v3_test.go

`internal_endpoint` and `external_endpoint` are always empty as the provider misused the field of API response, so fix it.
the testing as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCEClusterV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCEClusterV3_basic -timeout 720m
=== RUN   TestAccCCEClusterV3_basic
--- PASS: TestAccCCEClusterV3_basic (415.54s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 415.579s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCEClusterV3DataSource_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCEClusterV3DataSource_basic -timeout 720m …
```

fix(cce): set internal_endpoint and external_endpoint correctly

---

docs/data-sources/cce_clusters.md
flexibleengine/acceptance/data_source_flexibleengine_cce_clusters_test.go
flexibleengine/provider.go

fixes #796 
```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccCCEClustersDataSource_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccCCEClustersDataSource_basic -timeout 720m
=== RUN   TestAccCCEClustersDataSource_basic
=== PAUSE TestAccCCEClustersDataSource_basic
=== CONT  TestAccCCEClustersDataSource_basic
--- PASS: TestAccCCEClustersDataSource_basic (762.56s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      762.647s
```

fix(cce): add a data source to get a list of CCE clusters

---

flexibleengine/data_source_flexibleengine_rts_software_config_v1_test.go
flexibleengine/data_source_flexibleengine_rts_stack_resource_v1_test.go
flexibleengine/data_source_flexibleengine_rts_stack_v1_test.go
flexibleengine/resource_flexibleengine_rts_stack_v1.go
flexibleengine/resource_flexibleengine_rts_stack_v1_test.go

**misuse of reflect.StringHeader**
```
$ make vet
go vet .
flexibleengine/resource_flexibleengine_rts_stack_v1.go:440:35: possible misuse of reflect.StringHeader
```
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccRts'
TF_ACC=1 go test ./flexibleengine -v -run TestAccRts -timeout 720m
=== RUN   TestAccRtsConfigV1DataSource_basic
--- PASS: TestAccRtsConfigV1DataSource_basic (27.27s)
=== RUN   TestAccRtsSoftwareConfigV1_basic
--- PASS: TestAccRtsSoftwareConfigV1_basic (27.20s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 54.512s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccRTS'
==> Checking that code complies with gofmt …
```

chore(rts): fix misuse of reflect.StringHeader

---

docs/data-sources/apig_environments.md
docs/resources/apig_api.md
docs/resources/apig_api_publishment.md
docs/resources/apig_application.md
docs/resources/apig_custom_authorizer.md
docs/resources/apig_environment.md
docs/resources/apig_group.md
docs/resources/apig_instance.md
docs/resources/apig_response.md
docs/resources/apig_throttling_policy.md
docs/resources/apig_throttling_policy_associate.md
docs/resources/apig_vpc_channel.md
flexibleengine/acceptance/data_source_flexibleengine_apig_environments_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_api_publishment_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_api_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_application_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_custom_authorizer_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_environment_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_group_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_instance_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_response_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_throttling_policy_associate_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_throttling_policy_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_vpc_channel_test.go
flexibleengine/provider.go

**add new data_source**:
flexibleengine_apig_environments
**add new resources**:
flexibleengine_apig_api_publishment
flexibleengine_apig_api
flexibleengine_apig_application
flexibleengine_apig_custom_authorizer
flexibleengine_apig_environment
flexibleengine_apig_group
flexibleengine_apig_instance
flexibleengine_apig_response
flexibleengine_apig_throttling_policy_associate
flexibleengine_apig_throttling_policy
flexibleengine_apig_vpc_channel
**Test results**:
```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccDataEnvironments_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccDataEnvironments_basic -timeout 720m
=== RUN   TestAccDataEnvironments_basic
=== PAUSE TestAccDataEnvironments_basic …
```

feat(apig): add new apig resources

---

docs/resources/tms_tags.md
flexibleengine/acceptance/resource_flexibleengine_tms_tags_test.go
flexibleengine/provider.go

add new tms resource：
flexibleengine_tms_tags
**Test results**:
```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccTmsTag_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccTmsTag_basic -timeout 720m
=== RUN   TestAccTmsTag_basic
--- PASS: TestAccTmsTag_basic (26.35s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      26.458s
```

feat(tms): add new tms resource

---

docs/data-sources/dcs_product_v1.md
docs/resources/dcs_instance_v1.md
flexibleengine/data_source_flexibleengine_dcs_product_v1.go
flexibleengine/data_source_flexibleengine_dcs_product_v1_test.go
flexibleengine/resource_flexibleengine_dcs_instance_v1.go
flexibleengine/resource_flexibleengine_dcs_instance_v1_test.go
go.mod
go.sum

related to #814 
the acceptance testing as follows:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run=TestAccDcsInstancesV1'
TF_ACC=1 go test ./flexibleengine -v -run=TestAccDcsInstancesV1 -timeout 720m
=== RUN   TestAccDcsInstancesV1_basic
=== PAUSE TestAccDcsInstancesV1_basic
=== RUN   TestAccDcsInstancesV1_redisV5
=== PAUSE TestAccDcsInstancesV1_redisV5
=== RUN   TestAccDcsInstancesV1_memcached
=== PAUSE TestAccDcsInstancesV1_memcached
=== CONT  TestAccDcsInstancesV1_basic
=== CONT  TestAccDcsInstancesV1_memcached
=== CONT  TestAccDcsInstancesV1_redisV5
--- PASS: TestAccDcsInstancesV1_basic (483.43s)
--- PASS: TestAccDcsInstancesV1_memcached (484.24s)
--- PASS: TestAccDcsInstancesV1_redisV5 (506.36s)
PASS
ok …
```

feat(dcs): support more filters in data source

---

docs/resources/dds_database_role.md
docs/resources/dds_database_user.md
flexibleengine/acceptance/resource_flexibleengine_dds_database_role_test.go
flexibleengine/acceptance/resource_flexibleengine_dds_database_user_test.go
flexibleengine/provider.go

```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccDatabaseRole_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccDatabaseRole_basic -timeout 720m
=== RUN   TestAccDatabaseRole_basic
=== PAUSE TestAccDatabaseRole_basic
=== CONT  TestAccDatabaseRole_basic
--- PASS: TestAccDatabaseRole_basic (826.74s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      826.858s
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccDatabaseUser_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccDatabaseUser_basic -timeout 720m
=== RUN …
```

feat(dds): add dds database role and user

---

flexibleengine/deprecated/doc.go
flexibleengine/deprecated/resource_flexibleengine_rds_instance_v3.go
flexibleengine/deprecated/resource_flexibleengine_vpc_subnet_v1.go
flexibleengine/deprecated/resource_flexibleengine_vpc_v1.go
flexibleengine/deprecated/utils.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_rds_read_replica_v3.go
flexibleengine/resource_flexibleengine_rds_read_replica_v3_test.go

Package deprecated includes files of resources and data sources that imported directly from HWC, so we should deprecate them.
the testing results are as follows:
```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run=TestAccVpcV1_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run=TestAccVpcV1_basic -timeout 720m
=== RUN   TestAccVpcV1_basic
=== PAUSE TestAccVpcV1_basic
=== CONT  TestAccVpcV1_basic
--- PASS: TestAccVpcV1_basic (65.18s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      65.255s
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run=TestAccVpcSubnetV1_basic'
TF_ACC=1 go …
```

chore: move deprecated resource into a dir

---

docs/resources/dms_kafka_user.md
flexibleengine/acceptance/resource_flexibleengine_dms_kafka_user_test.go
flexibleengine/provider.go

```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccDmsKafkaUser_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccDmsKafkaUser_basic -timeout 720m
=== RUN   TestAccDmsKafkaUser_basic
=== PAUSE TestAccDmsKafkaUser_basic
=== CONT  TestAccDmsKafkaUser_basic
--- PASS: TestAccDmsKafkaUser_basic (999.82s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      999.935s
```

feat(dms/kafka): add new resource user

---

docs/resources/dcs_instance_v1.md
flexibleengine/resource_flexibleengine_dcs_instance_v1.go
flexibleengine/resource_flexibleengine_dcs_instance_v1_test.go
go.mod
go.sum

```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDcsInstancesV1_redisV5'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDcsInstancesV1_redisV5 -timeout 720m
=== RUN   TestAccDcsInstancesV1_redisV5
=== PAUSE TestAccDcsInstancesV1_redisV5
=== CONT  TestAccDcsInstancesV1_redisV5
--- PASS: TestAccDcsInstancesV1_redisV5 (181.39s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 181.468s
```

feat(dcs/instance): support port customization

---

docs/resources/dms_kafka_instance.md
flexibleengine/resource_flexibleengine_dms_kafka_instance.go
go.mod
go.sum

```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDmsKafkaInstance_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDmsKafkaInstance_basic -timeout 720m
--- PASS: TestAccDmsKafkaInstance_basic (961.45s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 961.544s
```

feat(dms/kafka): support enable_auto_topic in kafka instance

---

docs/resources/cce_node_pool_v3.md
flexibleengine/resource_flexibleengine_cce_node_pool.go
flexibleengine/resource_flexibleengine_cce_node_pool_test.go

fixes #819 
```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodePool_basic'
=== RUN   TestAccCCENodePool_basic
=== PAUSE TestAccCCENodePool_basic
=== CONT  TestAccCCENodePool_basic
--- PASS: TestAccCCENodePool_basic (878.98s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 879.062s
```

fix(cce/node_pool): repalce scall_enable with scale_enable

---

docs/resources/lb_pool_v2.md
flexibleengine/acceptance/resource_flexibleengine_lb_pool_v2_test.go
flexibleengine/provider.go

fixes https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/issues/821
Test result:
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccLBV2Pool_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccLBV2Pool_basic -timeout 720m
=== RUN   TestAccLBV2Pool_basic
=== PAUSE TestAccLBV2Pool_basic
=== CONT  TestAccLBV2Pool_basic
--- PASS: TestAccLBV2Pool_basic (141.50s) 
PASS 
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      141.599s

fix: fix elb v2 pool

---

docs/data-sources/vpc_route_ids_v2.md
docs/data-sources/vpc_route_table.md
docs/data-sources/vpc_route_v2.md
docs/resources/vpc_route.md
docs/resources/vpc_route_table.md
docs/resources/vpc_route_v2.md
flexibleengine/acceptance/data_source_flexibleengine_vpc_route_table_test.go
flexibleengine/acceptance/resource_flexibleengine_vpc_route_table_route_test.go
flexibleengine/acceptance/resource_flexibleengine_vpc_route_table_test.go
flexibleengine/data_source_flexibleengine_vpc_route_ids_v2_test.go
flexibleengine/data_source_flexibleengine_vpc_route_v2_test.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_vpc_route_v2_test.go

add new resources route_table and route
**Test results**:
```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccVpcRouteTable_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccVpcRouteTable_basic -timeout 720m
=== RUN   TestAccVpcRouteTable_basic
=== PAUSE TestAccVpcRouteTable_basic
=== CONT  TestAccVpcRouteTable_basic
--- PASS: TestAccVpcRouteTable_basic (123.13s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      123.301s
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccVpcRouteTable_multiRoutes'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run …
```

feat(vpc): add new resources route_table and route

---

docs/resources/dli_database.md
docs/resources/dli_flinksql_job.md
docs/resources/dli_package.md
docs/resources/dli_spark_job.md
docs/resources/dli_table.md
flexibleengine/acceptance/acceptance.go
flexibleengine/acceptance/resource_flexibleengine_dli_database_test.go
flexibleengine/acceptance/resource_flexibleengine_dli_flinksql_job_test.go
flexibleengine/acceptance/resource_flexibleengine_dli_package_test.go
flexibleengine/acceptance/resource_flexibleengine_dli_spark_job_test.go
flexibleengine/acceptance/resource_flexibleengine_dli_table_test.go
flexibleengine/provider.go

fixes #826 
The following resources added:
flexibleengine_dli_database
flexibleengine_dli_table
flexibleengine_dli_package
flexibleengine_dli_flinksql_job
flexibleengine_dli_spark_job
Test results:
```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccDliDatabase_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccDliDatabase_basic -timeout 720m
=== RUN   TestAccDliDatabase_basic
=== PAUSE TestAccDliDatabase_basic
=== CONT  TestAccDliDatabase_basic
--- PASS: TestAccDliDatabase_basic (29.43s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      29.554s
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run …
```

feat(dli): add new dli resources

---

docs/resources/networking_router_route_v2.md
docs/resources/vpc_route_v2.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_networking_router_route_v2.go
flexibleengine/resource_flexibleengine_networking_router_route_v2_test.go

It has been deprecated, use `flexibleengine_vpc_route` instead.
```
$ make tetacc TEST='./flexibleengine' TESTARGS='-run=TestAccNetworkingV2RouterRoute_basic'
TF_ACC=1 go test ./flexibleengine -v -run=TestAccNetworkingV2RouterRoute_basic -timeout 720m
=== RUN   TestAccNetworkingV2RouterRoute_basic
provider_test.go:111: This environment does not support deprecated tests
--- SKIP: TestAccNetworkingV2RouterRoute_basic (0.00s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 0.044s
```

chore: deprecate networking_router_route_v2 resource

---

docs/resources/waf_dedicated_certificate.md
docs/resources/waf_dedicated_policy.md
flexibleengine/config.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_waf_dediacted_certificate.go
flexibleengine/resource_flexibleengine_waf_dedicated_certificate_test.go
flexibleengine/resource_flexibleengine_waf_dedicated_policy.go
flexibleengine/resource_flexibleengine_waf_dedicated_policy_test.go

add resources:
flexibleengine_waf_dedicated_certificate
flexibleengine_waf_dedicated_policy
**Test results**:
```
make testacc TEST='./flexibleengine/' TESTARGS='-run TestAccWafDedicatedPolicyV1_basic'
TF_ACC=1 go test ./flexibleengine/ -v -run TestAccWafDedicatedPolicyV1_basic -timeout 720m
=== RUN   TestAccWafDedicatedPolicyV1_basic
=== PAUSE TestAccWafDedicatedPolicyV1_basic
=== CONT  TestAccWafDedicatedPolicyV1_basic
--- PASS: TestAccWafDedicatedPolicyV1_basic (51.84s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 52.036s
make testacc TEST='./flexibleengine/' TESTARGS='-run TestAccWafDedicatedCertificateV1_basic'
TF_ACC=1 …
```

feat(waf): add dedicated certificate and policy

---

go.mod
go.sum

the release action runs failed
https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/actions/runs/3591491483
should update the hw provider version

fix: bump hw provider version to fix overflows

---

docs/resources/lts_topic.md
flexibleengine/resource_flexibleengine_lts_group.go
flexibleengine/resource_flexibleengine_lts_group_test.go
flexibleengine/resource_flexibleengine_lts_topic.go
flexibleengine/resource_flexibleengine_lts_topic_test.go

using **v2** APIs instead of **v2.0** APIs
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLTSGroupV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLTSGroupV2_basic -timeout 720m
=== RUN   TestAccLTSGroupV2_basic
=== PAUSE TestAccLTSGroupV2_basic
=== CONT  TestAccLTSGroupV2_basic
--- PASS: TestAccLTSGroupV2_basic (25.91s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 25.978s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccLTSTopicV2_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccLTSTopicV2_basic -timeout 720m
=== RUN   TestAccLTSTopicV2_basic
=== PAUSE TestAccLTSTopicV2_basic …
```

fix: update the API verison of LTS group and topic

---

docs/resources/as_lifecycle_hook_v1.md
flexibleengine/resource_flexibleengine_as_lifecycle_hook.go

In API documentation the import syntax is `{scaling_group_id}/{lifecycle_hook_name}` and not `{scaling_group_id}/{lifecycle_hook_id}`
Link of the documentation :
[https://docs.prod-cloud-ocb.orange-business.com/api/as/as_06_0903.html](https://docs.prod-cloud-ocb.orange-business.com/api/as/as_06_0903.html)

FIX import for resource flexibleengine_as_lifecycle_hook_v1

---

docs/resources/networking_vip_associate_v2.md
docs/resources/networking_vip_v2.md
flexibleengine/resource_flexibleengine_networking_vip_associate_v2_test.go
flexibleengine/resource_flexibleengine_networking_vip_v2.go
flexibleengine/resource_flexibleengine_networking_vip_v2_test.go

related to #857 
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccNetworkingV2VIP_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccNetworkingV2VIP_basic -timeout 720m
=== RUN   TestAccNetworkingV2VIP_basic
--- PASS: TestAccNetworkingV2VIP_basic (103.70s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 103.784s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccNetworkingV2VIPAssociate_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccNetworkingV2VIPAssociate_basic -timeout 720m
=== RUN   TestAccNetworkingV2VIPAssociate_basic
--- PASS: TestAccNetworkingV2VIPAssociate_basic (120.93s)
PASS
ok …
```

chore(vip): use ip_version instead of subnet_id

---

docs/resources/networking_port_v2.md
flexibleengine/resource_flexibleengine_networking_port_v2_test.go

related to #857 
the testing result:
```
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccNetworkingV2Port_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccNetworkingV2Port_basic -timeout 720m
=== RUN   TestAccNetworkingV2Port_basic
--- PASS: TestAccNetworkingV2Port_basic (79.34s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 79.415s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccNetworkingV2Port_fixedip'
TF_ACC=1 go test ./flexibleengine -v -run TestAccNetworkingV2Port_fixedip -timeout 720m
=== RUN   TestAccNetworkingV2Port_fixedip
--- PASS: TestAccNetworkingV2Port_fixedip (97.13s)
PASS
ok …
```

chore: update docs and acc test for networking port

---

flexibleengine/utils.go

support unmarshal the error body to ErrorResp
usage:
```go
if apiError, ok := err.(golangsdk.ErrDefault403); ok {
if resp, pErr := ParseErrorMsg(apiError.Body); pErr == nil && resp.ErrorCode == "xxxx" {
log.Printf("[WARN] add some message")
d.SetId("")
...
}
}
```

feat: support unmarshal the error body to ErrorResp

---

docs/resources/identity_acl.md
flexibleengine/acceptance/resource_flexibleengine_identity_acl_test.go
flexibleengine/provider.go

fixes #469 
test results:
```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccIdentitACL_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccIdentitACL_basic -timeout 720m
=== RUN   TestAccIdentitACL_basic
=== PAUSE TestAccIdentitACL_basic
=== CONT  TestAccIdentitACL_basic
--- PASS: TestAccIdentitACL_basic (32.87s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      32.969s
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccIdentitACL_apiAccess'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccIdentitACL_apiAccess -timeout 720m
=== RUN …
```

feat(iam): add new resource identity_acl

---

docs/data-sources/sms_source_servers.md
docs/resources/sms_server_template.md
docs/resources/sms_task.md
flexibleengine/acceptance/acceptance.go
flexibleengine/acceptance/data_source_flexibleengine_sms_source_servers_test.go
flexibleengine/acceptance/resource_flexibleengine_sms_server_template_test.go
flexibleengine/acceptance/resource_flexibleengine_sms_task_test.go
flexibleengine/provider.go

test result:
```
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccSourceServers_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccSourceServers_basic -timeout 720m
=== RUN   TestAccSourceServers_basic
=== PAUSE TestAccSourceServers_basic
=== CONT  TestAccSourceServers_basic
--- PASS: TestAccSourceServers_basic (25.09s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      25.199s
make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccServerTemplate_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccServerTemplate_basic -timeout 720m
=== RUN …
```

feat(sms): add new sms resources

---

docs/data-sources/dws_flavors.md
docs/resources/dws_cluster_v1.md
flexibleengine/acceptance/data_source_flexibleengine_dws_flavors_test.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_dws_cluster_v1_test.go

fixes #891 
```
$ make testacc TEST='./flexibleengine/' TESTARGS='-run TestDWSClusterBasic'
TF_ACC=1 go test ./flexibleengine/ -v -run TestDWSClusterBasic -timeout 720m
=== RUN   TestDWSClusterBasic
--- PASS: TestDWSClusterBasic (1168.19s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 1168.287s
$ make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccDwsFlavorsDataSource'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccDwsFlavorsDataSource -timeout 720m
=== RUN   TestAccDwsFlavorsDataSource_basic
=== PAUSE TestAccDwsFlavorsDataSource_basic
=== RUN   TestAccDwsFlavorsDataSource_memory
=== PAUSE …
```

feat(dws): add flavors data source

---

docs/resources/dns_ptrrecord_v2.md
docs/resources/dns_recordset_v2.md
docs/resources/dns_zone_v2.md
flexibleengine/resource_flexibleengine_dns_ptrrecord_v2.go

Hi,
I've made some updates to the DNS documentation to improve clarity and add more detail. The changes are as follows:
- docs(dns/ptrrecord): improve documentation
- docs(dns/recordset): improve documentation
- docs(dns/zone): improve documentation

docs(dns): improve documentation

---

flexibleengine/resource_flexibleengine_dms_kafka_instance.go
flexibleengine/resource_flexibleengine_dms_kafka_instance_test.go

The order of elements in Availability Zone list returned by Kafka API will be changed, so update the type to **TypeSet**.
the testing result:
```
$ make testacc TEST='./flexibleengine/' TESTARGS='-run TestAccDmsKafkaInstance_basic'
TF_ACC=1 go test ./flexibleengine/ -v -run TestAccDmsKafkaInstance_basic -timeout 720m
--- PASS: TestAccDmsKafkaInstance_basic (965.23s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 965.340s
```

fix(dms/kafka): fix the force replacement issue caused by az

---

flexibleengine/resource_flexibleengine_dcs_instance_v1.go
flexibleengine/utils.go

```
$ make testacc TEST='./flexibleengine/' TESTARGS='-run TestAccDcsInstancesV1_basic'
TF_ACC=1 go test ./flexibleengine/ -v -run TestAccDcsInstancesV1_basic -timeout 720m
=== RUN   TestAccDcsInstancesV1_basic
=== PAUSE TestAccDcsInstancesV1_basic
=== CONT  TestAccDcsInstancesV1_basic
--- PASS: TestAccDcsInstancesV1_basic (408.93s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 409.031s
$ make testacc TEST='./flexibleengine/' TESTARGS='-run TestAccDcsInstancesV1_redisV5'
TF_ACC=1 go test ./flexibleengine/ -v -run TestAccDcsInstancesV1_redisV5 -timeout 720m
=== RUN   TestAccDcsInstancesV1_redisV5 …
```

fix(dcs): ignore invalid security_group_id

---

docs/resources/antiddos_v1.md
flexibleengine/resource_flexibleengine_antiddos_v1.go
flexibleengine/utils.go

In crossplane the provider use `Read` Func before try create resource.
The terraform read function not catch err correctly therefore the
crossplane provider return err and do not try to create resource.
Error returned by crossplane :
```
Error retrieving AntiDdos: Action forbidden: [GET https://antiddos.eu-west-0.prod-cloud-ocb.orange-business.com/v1/xxx/antiddos/xxx], error message: {"error_code":"10001020", "error_msg":"IPID is invalid"}
```
In the fix use two method for catch notConfig Resource :
* In Read func call checkNotConfig func which verifies if error is not in listed codes (10001020 and 10001020)
* In Create/Update func edit loop stateChangeConf using
`antiddos.GetStatus` instead `antiddos.Get` to determine status of
antiddos
Details of codes : 
- **10000016** - VPC cannot be …

fix(antiddos): status returned in Create/Update/Delete func in flexibleengine_antiddos_v1 resource

---

docs/resources/cce_node_pool_v3.md
flexibleengine/resource_flexibleengine_cce_node_pool.go
flexibleengine/resource_flexibleengine_cce_node_pool_test.go

fixes #838 
test results:
```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodePool_basic'
=== RUN   TestAccCCENodePool_basic
=== PAUSE TestAccCCENodePool_basic
=== CONT  TestAccCCENodePool_basic
--- PASS: TestAccCCENodePool_basic (884.15s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 885.186s
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCENodePool_serverGroup'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCENodePool_serverGroup -timeout 720m
=== RUN   TestAccCCENodePool_serverGroup
=== PAUSE …
```

feat(cce): support server group in node pool

---

docs/resources/cce_node_v3.md
flexibleengine/resource_flexibleengine_cce_node_v3.go
flexibleengine/resource_flexibleengine_cce_node_v3_test.go

the testing result:
```
$ make testacc TEST='./flexibleengine/' TESTARGS='-run TestAccCCENodeV3_basic'
TF_ACC=1 go test ./flexibleengine/ -v -run TestAccCCENodeV3_basic -timeout 720m
=== PAUSE TestAccCCENodeV3_basic
=== CONT  TestAccCCENodeV3_basic
--- PASS: TestAccCCENodeV3_basic (841.42s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 841.513s
```

feat(cce/node): add subnet_id and ecs_group_id parameters

---

docs/resources/cce_pvc.md
go.mod
go.sum

fixes #892 
fixes #876 
```
$ make testacc TEST='./flexibleengine/acceptance/' TESTARGS='-run TestAccCcePersistentVolumeClaimsV1_basic'
TF_ACC=1 go test ./flexibleengine/acceptance/ -v -run TestAccCcePersistentVolumeClaimsV1_basic -timeout 720m
=== RUN   TestAccCcePersistentVolumeClaimsV1_basic
=== PAUSE TestAccCcePersistentVolumeClaimsV1_basic
=== CONT  TestAccCcePersistentVolumeClaimsV1_basic
--- PASS: TestAccCcePersistentVolumeClaimsV1_basic (918.12s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      918.218s
```

docs: update docs of cce pvc

---

docs/resources/dms_rocketmq_consumer_group.md
docs/resources/dms_rocketmq_instance.md

This PR to correct the import documentation for `flexibleengine_dms_rocketmq_consumer_group`

docs(dms): bad value in import for group

---

flexibleengine/resource_flexibleengine_antiddos_v1.go

In the AntiDDOS Resource catch bad http code 
In this error HTTP Code returned is 403 and not 400
```
cannot run refresh: refresh failed: Error retrieving AntiDdos: Action forbidden: [GET https://antiddos.eu-west-0.prod-cloud-ocb.orange-business.com/v1/5764591bf7ac4dd282dfbebb3e266701/antiddos/3f0c282f-6082-46bb-9afc-a9eadd28f4cf], error message: {"error_code":"10001020", "error_msg":"IPID is invalid"}:
```

fix(antiddos): fix http code used for parse error

---

docs/resources/dms_kafka_instance.md
flexibleengine/acceptance/resource_flexibleengine_apig_application_test.go
flexibleengine/acceptance/resource_flexibleengine_apig_throttling_policy_test.go
flexibleengine/provider.go
flexibleengine/provider_test.go
flexibleengine/resource_flexibleengine_dms_kafka_instance.go
flexibleengine/resource_flexibleengine_dms_kafka_instance_test.go
go.mod
go.sum

1. support tags in kafka instance
2. update the reference
```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccDmsKafkaInstance_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccDmsKafkaInstance_basic -timeout 720m
--- PASS: TestAccDmsKafkaInstance_basic (963.79s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 963.885s
```

feat(dms/kafka): support tags in kafka instance

---

docs/resources/obs_bucket_notifications.md
flexibleengine/provider.go
flexibleengine/provider_test.go
flexibleengine/resource_flexibleengine_obs_bucket_notifications.go
flexibleengine/resource_flexibleengine_obs_bucket_notifications_test.go

```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccObsBucket_notification'
==> Checking that code complies with gofmt requirements... 
TF_ACC=1 go test ./flexibleengine -v -run TestAccObsBucket_notification -timeout 720m 
=== RUN   TestAccObsBucket_notification 
=== PAUSE TestAccObsBucket_notification 
=== CONT  TestAccObsBucket_notification
--- PASS: TestAccObsBucket_notification (60.37s) 
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 60.450s
```

feat(obs): obs support notification

---

go.mod
go.sum

fixes #885 
fixes #906 
fixes #907 
```
$ make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccDatabaseRole_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccDatabaseRole_basic -timeout 720m
=== RUN   TestAccDatabaseRole_basic
=== PAUSE TestAccDatabaseRole_basic
=== CONT  TestAccDatabaseRole_basic
--- PASS: TestAccDatabaseRole_basic (685.31s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      685.406s
```

chore(deps): bump hw provider to v1.45.0

---

docs/data-sources/gaussdb_cassandra_instances.md
docs/data-sources/gaussdb_nosql_flavors.md
docs/resources/gaussdb_cassandra_instance.md
docs/resources/gaussdb_influx_instance.md
flexibleengine/acceptance/data_source_flexibleengine_gaussdb_cassandra_instances_test.go
flexibleengine/acceptance/data_source_flexibleengine_gaussdb_nosql_flavors_test.go
flexibleengine/acceptance/resource_flexibleengine_gaussdb_cassandra_instance_test.go
flexibleengine/acceptance/resource_flexibleengine_gaussdb_influx_instance_test.go
flexibleengine/provider.go

new resources:
flexibleengine_gaussdb_cassandra_instance
flexibleengine_gaussdb_influx_instance
new data_sources:
flexibleengine_gaussdb_cassandra_instances
flexibleengine_gaussdb_nosql_flavors
test results:
```
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccGaussDBNoSQLFlavors'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccGaussDBNoSQLFlavors -timeout 720m
=== RUN   TestAccGaussDBNoSQLFlavors_basic
=== PAUSE TestAccGaussDBNoSQLFlavors_basic
=== RUN   TestAccGaussDBNoSQLFlavors_influxdb
=== PAUSE TestAccGaussDBNoSQLFlavors_influxdb
=== RUN   TestAccGaussDBNoSQLFlavors_vcpus
=== PAUSE TestAccGaussDBNoSQLFlavors_vcpus
=== RUN   TestAccGaussDBNoSQLFlavors_memory
=== PAUSE …
```

feat(gaussdb): add nosql resources

---

docs/resources/dds_instance_v3.md
flexibleengine/resource_flexibleengine_dds_instance_v3.go
flexibleengine/resource_flexibleengine_dds_instance_v3_test.go

fixes #930 
```
$ make testacc TEST="./flexibleengine" TESTARGS="-run TestAccDDSV3Instance_basic"
--- PASS: TestAccDDSV3Instance_basic (526.83s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 526.881s
```

feat(dds): unset the validation of version to create MongoDB 4.2

---

docs/resources/obs_bucket.md
flexibleengine/resource_flexibleengine_obs_bucket.go
flexibleengine/resource_flexibleengine_obs_bucket_test.go

```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccObsBucket_basic'
=== PAUSE TestAccObsBucket_basic
=== CONT  TestAccObsBucket_basic
--- PASS: TestAccObsBucket_basic (51.09s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 51.161s
$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccObsBucket_parallelFS'
TF_ACC=1 go test ./flexibleengine -v -run TestAccObsBucket_parallelFS -timeout 720m
=== RUN   TestAccObsBucket_parallelFS
=== PAUSE TestAccObsBucket_parallelFS
=== CONT  TestAccObsBucket_parallelFS …
```

feat(obs): support parallel_fs in obs bucket

---

docs/resources/obs_bucket_acl.md
flexibleengine/acceptance/resource_flexibleengine_obs_bucket_acl_test.go
flexibleengine/provider.go

fixes #909 
```
make testacc TEST='./flexibleengine'/acceptance TESTARGS='-run TestAccOBSBucketAcl_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccOBSBucketAcl_basic -timeout 720m
=== RUN   TestAccOBSBucketAcl_basic
=== PAUSE TestAccOBSBucketAcl_basic
=== CONT  TestAccOBSBucketAcl_basic
--- PASS: TestAccOBSBucketAcl_basic (58.60s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      58.711s
```

feat(obs): add new resource bucket acl

---

docs/resources/images_image_copy.md
flexibleengine/acceptance/acceptance.go
flexibleengine/acceptance/resource_flexibleengine_images_image_copy_test.go
flexibleengine/provider.go

Add new resource support:
- IMS image copy
The test result:
```
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run=TestAccImsI
mageCopy_basic_cross_region'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run=TestAccImsImageCopy_basic_cross_region -timeout 720m
=== RUN   TestAccImsImageCopy_basic_cross_region
=== PAUSE TestAccImsImageCopy_basic_cross_region
=== CONT  TestAccImsImageCopy_basic_cross_region
--- PASS: TestAccImsImageCopy_basic_cross_region (850.17s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance    850.397s
```

feat(ims/copy): add new resource support

---

docs/resources/images_image_share.md
docs/resources/images_image_share_accepter.md
flexibleengine/acceptance/acceptance.go
flexibleengine/acceptance/resource_flexibleengine_images_image_copy_test.go
flexibleengine/acceptance/resource_flexibleengine_images_image_share_accepter_test.go
flexibleengine/acceptance/resource_flexibleengine_images_image_share_test.go
flexibleengine/provider.go
go.mod
go.sum

fixes #927 
```
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run=TestAccImsImageShare_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run=TestAccImsImageShare_basic -timeout 720m
=== RUN   TestAccImsImageShare_basic
=== PAUSE TestAccImsImageShare_basic
=== CONT  TestAccImsImageShare_basic
--- PASS: TestAccImsImageShare_basic (667.55s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      667.611s
```
```
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run=TestAccImsImageShareAccepter_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run=TestAccImsImageShareAccepter_basic -timeout …
```

feat(ims): support share and acceptance resources

---

docs/resources/cce_node_pool_v3.md
docs/resources/cce_node_v3.md
flexibleengine/resource_flexibleengine_cce_node_pool.go
flexibleengine/resource_flexibleengine_cce_node_v3.go
flexibleengine/resource_flexibleengine_cce_node_v3_test.go

Hello,
Please consider this PR which adds the KMS disk encryption on root_Volume for CCE nodes (and node pool) through the Volume Metadata object as described here: https://docs.prod-cloud-ocb.orange-business.com/api2/cce/cce_02_0242.html#cce_02_0242__request_VolumeMetadata
I've successfully tested the change on an existing terraform project, setting up a new Nodepool with KMS encryption on both root_volume and data_volumes.
It's my first PR so please feel free to correct me if I missed something.
As you can see below, the root_volume is encrypted with KMS
---------
The tests `TestAccCCENodeV3_basic` and `TestAccCCENodeV3_volumes_encryption` are FAILED, but I don't think it's related to the current changes. I also had to change the flavor "s1.medium" which no longer exists to "s3.large.2" …

feat(cce) Add kms_key_id on root_volume cce nodes/nodepool

---

docs/resources/networking_port_v2.md
flexibleengine/resource_flexibleengine_networking_port_v2.go

When creating a port with **mac_address**, we will get the following error:
```
resource "flexibleengine_networking_port_v2" "port_1" {
name        = "port_1"
network_id  = flexibleengine_vpc_subnet_v1.subnet_1.id
mac_address = "fa:16:3e:65:84:d3"
}
flexibleengine_networking_port_v2.port_1: Creating...
╷
│ Error: Error creating FlexibleEngine Neutron network: Bad request with: [POST https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/ports], error message: {"NeutronError":{"message":"Attribute 'mac_address' cannot be set.","type":"HTTPBadRequest","detail":""}}
│
│   with flexibleengine_networking_port_v2.port_1,
│   on main.tf line 22, in resource "flexibleengine_networking_port_v2" "port_1":
│   22: resource "flexibleengine_networking_port_v2" "port_1" {
```
It's not supported …

fix(network/port): deprecate mac_address which cannot be set

---

docs/data-sources/images_image.md
docs/data-sources/images_image_v2.md
docs/data-sources/images_images.md
docs/resources/images_image.md
docs/resources/images_image_v2.md
flexibleengine/acceptance/acceptance.go
flexibleengine/acceptance/data_source_flexibleengine_images_image_test.go
flexibleengine/acceptance/data_source_flexibleengine_images_images_test.go
flexibleengine/acceptance/resource_flexibleengine_images_image_test.go
flexibleengine/data_source_flexibleengine_images_image_v2.go
flexibleengine/data_source_flexibleengine_images_image_v2_test.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_images_image_v2.go
flexibleengine/resource_flexibleengine_images_image_v2_test.go

1. deperacate resource `flexibleengine_images_image_v2` and `data_source flexibleengine_images_image_v2`
2. replace them with resource `flexibleengine_images_image` and `data_source flexibleengine_images_image`
3. add a new data_source `flexibleengine_images_images`
```
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccImsImageDataSource_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccImsImageDataSource_basic -timeout 720m
=== RUN   TestAccImsImageDataSource_basic
=== PAUSE TestAccImsImageDataSource_basic
=== CONT  TestAccImsImageDataSource_basic
--- PASS: TestAccImsImageDataSource_basic (56.75s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/accep …
```

feat(ims): update image resource and data_source

---

docs/data-sources/cbr_backup.md
docs/data-sources/cbr_vaults.md
docs/resources/cbr_policy.md
docs/resources/cbr_vault.md
flexibleengine/acceptance/data_source_flexibleengine_cbr_backup_test.go
flexibleengine/acceptance/resource_flexibleengine_cbr_vault_test.go
flexibleengine/provider.go
go.sum

fixes #940 
1. update the docs of cbr resource and data_source
2. update test cases of resource flexibleengine_cbr_vault
3. add new data_source `flexibleengine_cbr_backup`
```
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccDataBackup_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccDataBackup_basic -timeout 720m
=== RUN   TestAccDataBackup_basic
=== PAUSE TestAccDataBackup_basic
=== CONT  TestAccDataBackup_basic
--- PASS: TestAccDataBackup_basic (550.04s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      550.125s
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccCBRV3Vault_BasicServer'
==> Checking that code …
```

feat(cbr): update vault and add a new data_source

---

docs/resources/kms_grant.md
flexibleengine/acceptance/resource_flexibleengine_kms_grant_test.go
flexibleengine/provider.go

fixes #951 
```
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccKmsGrant_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccKmsGrant_basic -timeout 720m
=== RUN   TestAccKmsGrant_basic
=== PAUSE TestAccKmsGrant_basic
=== CONT  TestAccKmsGrant_basic
--- PASS: TestAccKmsGrant_basic (35.89s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      35.944s
```

feat(kms): add new resource kms_grant

---

docs/data-sources/as_configurations.md
docs/data-sources/as_groups.md
docs/resources/as_configuration.md
docs/resources/as_group.md
docs/resources/as_instance_attach.md
docs/resources/as_notification.md
flexibleengine/acceptance/data_source_flexibleengine_as_configurations_test.go
flexibleengine/acceptance/data_source_flexibleengine_as_groups_test.go
flexibleengine/acceptance/resource_flexibleengine_as_instance_acctah_test.go
flexibleengine/acceptance/resource_flexibleengine_as_notification_test.go
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_as_group_v1.go

1. add new resources `flexibleengine_as_instance_attach` and `flexibleengine_as_notification`
2. add new data_sources `flexibleengine_as_configurations` and `flexibleengine_as_groups`
3. rename resource `flexibleengine_as_configuration_v1` to `flexibleengine_as_configuration`
4. rename resource `flexibleengine_as_group_v1` to `flexibleengine_as_group`
```
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccAsNotification_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccAsNotification_basic -timeout 720m
=== RUN   TestAccAsNotification_basic
=== PAUSE TestAccAsNotification_basic
=== CONT  TestAccAsNotification_basic
--- PASS: TestAccAsNotification_basic (245.25s)
PASS
ok …
```

feat(as): add new resources

---

docs/resources/lb_listener_v2.md
flexibleengine/data_source_flexibleengine_lb_certificates_v2.go
flexibleengine/resource_flexibleengine_lb_listener_v2_test.go

fixes #963 
the testing as follows:
```bash
$ make testacc TEST="./flexibleengine" TESTARGS="-run TestAccLBV2Listener"
TF_ACC=1 go test ./flexibleengine -v -run TestAccLBV2Listener -timeout 720m
--- PASS: TestAccLBV2Listener_basic (138.03s)
=== RUN   TestAccLBV2Listener_withCert
--- PASS: TestAccLBV2Listener_withCert (70.12s)
=== RUN   TestAccLBV2Listener_v3
--- PASS: TestAccLBV2Listener_v3 (71.04s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 279.292s
```

chore: deprecate lb_certificates_v2 in docs and acc-tests

---

docs/resources/nat_private_dnat_rule.md
docs/resources/nat_private_gateway.md
docs/resources/nat_private_snat_rule.md
docs/resources/nat_private_transit_ip.md
flexibleengine/acceptance/common.go
flexibleengine/acceptance/data_source_flexibleengine_images_image_test.go
flexibleengine/acceptance/resource_flexibleengine_nat_private_dnat_rule_test.go
flexibleengine/acceptance/resource_flexibleengine_nat_private_gateway_test.go
flexibleengine/acceptance/resource_flexibleengine_nat_private_snat_rule_test.go
flexibleengine/acceptance/resource_flexibleengine_nat_private_transit_ip_test.go
flexibleengine/provider.go

add new resources:
1. flexibleengine_nat_private_dnat_rule
2. flexibleengine_nat_private_gateway
3. flexibleengine_nat_private_snat_rule
4. flexibleengine_nat_private_transit_ip
Test results:
```bash
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccPrivateGateway_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccPrivateGateway_basic -timeout 720m
=== RUN   TestAccPrivateGateway_basic
=== PAUSE TestAccPrivateGateway_basic
=== CONT  TestAccPrivateGateway_basic
--- PASS: TestAccPrivateGateway_basic (90.01s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      90.059s
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run …
```

feat(NAT): add private nat resources

---

docs/resources/sfs_turbo.md
flexibleengine/acceptance/resource_flexibleengine_sfs_turbo_test.go

```
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccSFSTurbo_basic'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccSFSTurbo_basic -timeout 720m
=== RUN   TestAccSFSTurbo_basic
=== PAUSE TestAccSFSTurbo_basic
=== CONT  TestAccSFSTurbo_basic
--- PASS: TestAccSFSTurbo_basic (387.60s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine/acceptance      387.654s
make testacc TEST='./flexibleengine/acceptance' TESTARGS='-run TestAccSFSTurbo_crypt'
TF_ACC=1 go test ./flexibleengine/acceptance -v -run TestAccSFSTurbo_crypt -timeout 720m
=== RUN   TestAccSFSTurbo_crypt
=== PAUSE TestAccSFSTurbo_crypt
=== …
```

feat(sfs): support enhanced in sfs turbo

---

docs/data-sources/dns_zone_v2.md
docs/resources/dns_zone_v2.md
flexibleengine/data_source_flexibleengine_dns_zone_v2.go

```
=== RUN   TestAccDNSZoneV2DataSource_basic
--- PASS: TestAccDNSZoneV2DataSource_basic (69.62s)
PASS
```
```
=== RUN   TestAccDNSV2Zone_basic
=== PAUSE TestAccDNSV2Zone_basic
=== CONT  TestAccDNSV2Zone_basic
--- PASS: TestAccDNSV2Zone_basic (113.47s)
=== RUN   TestAccDNSV2Zone_private
=== PAUSE TestAccDNSV2Zone_private
=== CONT  TestAccDNSV2Zone_private
--- PASS: TestAccDNSV2Zone_private (111.93s)
=== RUN   TestAccDNSV2Zone_readTTL
=== PAUSE TestAccDNSV2Zone_readTTL
=== CONT  TestAccDNSV2Zone_readTTL
--- PASS: TestAccDNSV2Zone_readTTL (78.87s)
PASS
```

fix(DNS/zone): docs issues and incorrect attributes for schema fields

---

docs/data-sources/dws_flavors.md
docs/resources/dws_cluster_v1.md
flexibleengine/acceptance/data_source_flexibleengine_dws_flavors_test.go

**data_source_flexibleengine_dws_flavors**
1、unit test：
=== RUN   TestAccDwsFlavorsDataSource_dataStoreType
=== PAUSE TestAccDwsFlavorsDataSource_dataStoreType
=== CONT  TestAccDwsFlavorsDataSource_dataStoreType
--- PASS: TestAccDwsFlavorsDataSource_dataStoreType (25.22s)
PASS
2、dictionary value test：
3、attribute test：

docs(dws): fix docs issues.

---

docs/data-sources/dds_flavor_v3.md
docs/data-sources/dds_flavors_v3.md
docs/resources/dds_instance_v3.md
flexibleengine/data_source_flexibleengine_dds_flavor_v3_test.go

```hcl
=== RUN   TestAccDDSFlavorV3DataSource_basic
--- PASS: TestAccDDSFlavorV3DataSource_basic (37.46s)
PASS
coverage: 1.8% of statements in ../../terraform-provider-flexibleengine/...
```
---
`disk_encryption_id` is optional, the following image do not have the field, but it is created successfully

docs(dds): fix docs issues.

---

docs/data-sources/cce_addon_template.md
docs/data-sources/cce_cluster_v3.md
docs/data-sources/cce_clusters.md
docs/data-sources/cce_node_ids_v3.md
docs/data-sources/cce_node_v3.md
docs/resources/cce_addon_v3.md
docs/resources/cce_cluster_v3.md
docs/resources/cce_node_pool_v3.md
docs/resources/cce_node_v3.md

**data_source_flexibleengine_cce_clusters**
1、add attribute field

docs(cce): fix docs issues.

---

docs/data-sources/csbs_backup_policy_v1.md
docs/data-sources/csbs_backup_v1.md
docs/resources/csbs_backup_policy_v1.md
docs/resources/csbs_backup_v1.md

`provider_id` is optional, in the following image do not have `provider_id` field but it is still created successfully

docs(csbs): fix docs issues.

---

docs/data-sources/as_groups.md
docs/resources/cbr_vault.md
docs/resources/cse_microservice_engine.md
flexibleengine/acceptance/data_source_flexibleengine_as_groups_test.go

```hcl
=== RUN TestAccDataSourceASGroup_basic
=== PAUSE TestAccDataSourceASGroup_basic
=== CONT TestAccDataSourceASGroup_basic
--- PASS: TestAccDataSourceASGroup_basic (191.11s)
PASS
coverage: 3.7% of statements in ../../../terraform-provider-flexibleengine/...
```

docs(as/cbr/cse): processing Fields Referencing Huawei Cloud

---

docs/resources/api_gateway_api.md
docs/resources/api_gateway_group.md
docs/resources/apig_api.md
docs/resources/apig_api_publishment.md
docs/resources/apig_application.md
docs/resources/apig_custom_authorizer.md
docs/resources/apig_environment.md
docs/resources/apig_group.md
docs/resources/apig_instance.md
docs/resources/apig_response.md
docs/resources/apig_throttling_policy.md
docs/resources/apig_vpc_channel.md

fix docs of APIG service.
1、docs/resources/apig_application.md
`app_codes` is optional
2、docs/resources/apig_custom_authorizer.md
`validation` is optional, the unit test has its parent field but do not have the field.

fix: fix docs of APIG service.

---

docs/resources/cce_cluster_v3.md
flexibleengine/resource_flexibleengine_cce_cluster_v3.go
flexibleengine/resource_flexibleengine_cce_cluster_v3_test.go
flexibleengine/utils.go

fixes #976 
```
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCCEClusterV3_basic'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCCEClusterV3_basic -timeout 720m
=== RUN   TestAccCCEClusterV3_basic
--- PASS: TestAccCCEClusterV3_basic (457.11s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 457.159s
make testacc TEST='./flexibleengine' TESTARGS='-run TestAccCluster_hibernate'
TF_ACC=1 go test ./flexibleengine -v -run TestAccCluster_hibernate -timeout 720m
=== RUN   TestAccCluster_hibernate
=== PAUSE TestAccCluster_hibernate
=== CONT  TestAccCluster_hibernate
--- PASS: TestAccCluster_hibernate (708.70s)
PASS
ok …
```

feat(cce): support hibernate in cce cluster

---

docs/data-sources/enterprise_project.md
docs/resources/enterprise_project.md

**type**: resource
**field**: `name`
**reason**: `name` is required.
**attention:** The documents are modified only without running unit test because the accout does not have permission

docs(eps): fix docs issues

---

docs/resources/mrs_cluster_v1.md
docs/resources/mrs_hybrid_cluster_v1.md
docs/resources/mrs_job_v1.md
flexibleengine/provider.go
flexibleengine/resource_flexibleengine_mrs_cluster_v1.go
flexibleengine/resource_flexibleengine_mrs_cluster_v1_test.go
flexibleengine/resource_flexibleengine_mrs_hybrid_cluster_v1.go
flexibleengine/resource_flexibleengine_mrs_hybrid_cluster_v1_test.go
flexibleengine/resource_flexibleengine_mrs_job_v1.go
flexibleengine/resource_flexibleengine_mrs_job_v1_test.go

the following resources will be deprecated:
+ flexibleengine_mrs_cluster_v1
+ flexibleengine_mrs_hybrid_cluster_v1
+ flexibleengine_mrs_job_v1

chore: mark MRS v1 resources as deprecated

---

docs/data-sources/availability_zones.md
docs/data-sources/compute_instance_v2.md
docs/data-sources/compute_instances.md
docs/resources/compute_instance_v2.md
docs/resources/compute_interface_attach_v2.md
docs/resources/compute_volume_attach_v2.md
flexibleengine/data_source_flexibleengine_compute_instance_v2.go
flexibleengine/data_source_flexibleengine_compute_instances.go

type: data source
field: `scheduler_hints`, `scheduler_hints.group`
reason: The definition of schema is wrong, this field is attribute
type: data source
field: `instances`, `instances.scheduler_hints`,
reason: The definition of schema is wrong, this field is attribute

docs(ecs): fix docs issues

---

docs/data-sources/images_image.md
docs/data-sources/images_image_v2.md
docs/resources/images_image.md
docs/resources/images_image_copy.md
docs/resources/images_image_share_accepter.md
docs/resources/images_image_v2.md

**type: ​**data source
**field:** `size_max`, `size_min`
**reason:** The two fields are deprecated<br />

docs(ims): fix docs issues

---

docs/data-sources/elb_certificate.md
docs/data-sources/lb_certificate_v2.md
docs/data-sources/lb_loadbalancer_v2.md
docs/resources/elb_backend.md
docs/resources/elb_certificate.md
docs/resources/elb_health.md
docs/resources/elb_ipgroup.md
docs/resources/elb_listener.md
docs/resources/elb_loadbalancer.md
docs/resources/lb_certificate_v2.md
docs/resources/lb_l7policy_v2.md
docs/resources/lb_l7rule_v2.md
docs/resources/lb_listener_v2.md
docs/resources/lb_loadbalancer_v2.md
docs/resources/lb_loadbalancer_v3.md
docs/resources/lb_member_v2.md
docs/resources/lb_monitor_v2.md
docs/resources/lb_pool_v2.md
docs/resources/lb_pool_v3.md
docs/resources/lb_whitelist_v2.md
flexibleengine/acceptance/resource_flexibleengine_elb_certificate_test.go
flexibleengine/acceptance/resource_flexibleengine_lb_loadbalancer_v3_test.go
flexibleengine/resource_flexibleengine_lb_l7policy_v2.go
flexibleengine/resource_flexibleengine_lb_l7rule_v2.go
flexibleengine/resource_flexibleengine_lb_loadbalancer_v2.go
flexibleengine/resource_flexibleengine_lb_member_v2.go
flexibleengine/resource_flexibleengine_lb_monitor_v2.go
flexibleengine/resource_flexibleengine_lb_whitelist_v2.go

These deprecated documents are modified only and do not run unit test
* elb_backend
* elb_health
* elb_listener
* elb_loadbalancer
* lb_certificate_v2
type: resource
field: `enterprise_project_id`
reason: add the field due to the unit test is passed
`tenant_id`, `admin_state_up`,`value_specs` is deprecated

docs(elb): fix docs issues

---

docs/data-sources/gaussdb_cassandra_instances.md
docs/resources/gaussdb_cassandra_instance.md
docs/resources/gaussdb_influx_instance.md

**type: ​**resource
**reason:** The service does not support the field.

docs(GaussDB): fix docs issues

---

docs/data-sources/s3_bucket_object.md
docs/resources/obs_bucket.md
docs/resources/obs_bucket_acl.md
docs/resources/obs_bucket_notifications.md
docs/resources/obs_bucket_object.md
docs/resources/obs_bucket_replication.md
docs/resources/s3_bucket.md
docs/resources/s3_bucket_object.md
docs/resources/s3_bucket_policy.md
flexibleengine/resource_flexibleengine_s3_bucket.go

docs(obs): fix docs issues

---

docs/data-sources/waf_dedicated_instances.md
docs/resources/waf_certificate.md
docs/resources/waf_dedicated_certificate.md
docs/resources/waf_dedicated_domain.md
docs/resources/waf_dedicated_instance.md
docs/resources/waf_dedicated_policy.md
docs/resources/waf_domain.md
docs/resources/waf_policy.md
docs/resources/waf_rule_cc_protection.md

**type: ​**resource
**field:** `tls`, `cihper`, `pci_dss`,`pci_3ds`
**reason:** The unit test was already have the fields
**type: ​**data source
**reason:** The Terraform script is passed

docs(waf): fix docs issues

---

docs/data-sources/rts_software_config_v1.md
docs/data-sources/rts_stack_resource_v1.md
docs/data-sources/rts_stack_v1.md
docs/resources/rts_software_config_v1.md
docs/resources/rts_stack_v1.md

docs(rts): fix docs issues.

---

docs/data-sources/sdrs_domain_v1.md
docs/resources/sdrs_drill_v1.md
docs/resources/sdrs_protectedinstance_v1.md
docs/resources/sdrs_protectiongroup_v1.md
docs/resources/sdrs_replication_attach_v1.md
docs/resources/sdrs_replication_pair_v1.md
flexibleengine/resource_flexibleengine_sdrs_drill.go
flexibleengine/resource_flexibleengine_sdrs_replication_pair_v1.go

`replication_model`,`fault_level`,`status`,`target_volume_id` are computed in schema

docs(sdrs): fix docs issues.

---

docs/data-sources/rds_flavors_v3.md
docs/resources/rds_account.md
docs/resources/rds_database.md
docs/resources/rds_database_privilege.md
docs/resources/rds_instance_v3.md
docs/resources/rds_parametergroup_v3.md
docs/resources/rds_read_replica_v3.md
flexibleengine/acceptance/resource_flexibleengine_rds_account_test.go
flexibleengine/acceptance/resource_flexibleengine_rds_database_test.go
flexibleengine/acceptance/resource_flexibleengine_rds_instance_v3_test.go

**field:** `description`
**reason:** unit test was passed<br />
```hcl
=== RUN   TestAccRdsDatabase_basic
=== PAUSE TestAccRdsDatabase_basic
=== CONT  TestAccRdsDatabase_basic
--- PASS: TestAccRdsDatabase_basic (633.11s)
PASS
```
**reason:** The service does not support the field.<br />
**field:** `volume.limit_size`,`vloume.trigger_threshold`
**reason:** The service does not support the field.
**field:** `parameters.name`,`parameters.value`
**reason:** The service does not support the field.
**field:** `volume.size`
**reason: ​**The unit test has but docs is missed the field
**field:** `type`
**reason: ​**The docs is missed the field

docs(rds): fix docs issues.

---

docs/resources/aom_service_discovery_rule.md
flexibleengine/acceptance/resource_flexibleengine_aom_service_discovery_rule_test.go
flexibleengine/provider.go

import `flexibleengine_aom_service_discovery_rule` resource, unit test and document
fixes #xxx
```release-note
```
```
=== RUN   TestAccAOMServiceDiscoveryRule_basic
=== PAUSE TestAccAOMServiceDiscoveryRule_basic
=== CONT  TestAccAOMServiceDiscoveryRule_basic
--- PASS: TestAccAOMServiceDiscoveryRule_basic (237.71s)
PASS
```

feat(AOM): import AOM resource, unit test and document.

---

docs/data-sources/compute_servergroups.md
flexibleengine/acceptance/data_source_flexibleengine_compute_servergroups_test.go
flexibleengine/provider.go

import `data_source_flexibleengine_compute_servergroups` resource, unit test and document
fixes #xxx
```release-note
```
```
=== RUN   TestAccComputeServerGroupsDataSource_basic
=== PAUSE TestAccComputeServerGroupsDataSource_basic
=== CONT  TestAccComputeServerGroupsDataSource_basic
--- PASS: TestAccComputeServerGroupsDataSource_basic (81.96s)
PASS
coverage: 2.0% of statements in ../../../terraform-provider-flexibleengine/...
```

feat(ECS): import ECS resource, unit test and document.

---

docs/data-sources/gaussdb_cassandra_flavors.md
flexibleengine/acceptance/data_source_flexibleengine_gaussdb_cassandra_flavors_test.go
flexibleengine/provider.go

import `data_source_flexibleengine_gaussdb_cassandra_flavors` resource, unit test and document
fixes #xxx
```release-note
```
```
=== RUN   TestAccCassandraFlavorsDataSource_basic
=== PAUSE TestAccCassandraFlavorsDataSource_basic
=== CONT  TestAccCassandraFlavorsDataSource_basic
--- PASS: TestAccCassandraFlavorsDataSource_basic (36.29s)
PASS
```

feat(GaussDB): import GaussDB resource, unit test and document.

---

docs/resources/fw_firewall_group_v2.md
docs/resources/fw_policy_v2.md
docs/resources/fw_rule_v2.md
docs/resources/network_acl.md
docs/resources/network_acl_rule.md
flexibleengine/resource_flexibleengine_fw_firewall_group_v2.go
flexibleengine/resource_flexibleengine_fw_policy_v2.go
flexibleengine/resource_flexibleengine_fw_rule_v2.go

`tenant_id,` `admin_state_up`, `value_specs` are deprecated

docs(FireWall): fix docs issues

---

docs/data-sources/rds_backups.md
docs/data-sources/rds_engine_versions.md
docs/data-sources/rds_flavors_v3.md
docs/data-sources/rds_instances.md
docs/data-sources/rds_storage_types.md
docs/resources/rds_backup.md
docs/resources/rds_cross_region_backup_strategy.md
docs/resources/rds_instance_v3.md
docs/resources/rds_parametergroup_v3.md
docs/resources/rds_read_replica_v3.md
docs/resources/rds_sql_audit.md
flexibleengine/acceptance/data_source_flexibleengine_rds_backups_test.go
flexibleengine/acceptance/data_source_flexibleengine_rds_engine_versions_test.go
flexibleengine/acceptance/data_source_flexibleengine_rds_instances_test.go
flexibleengine/acceptance/data_source_flexibleengine_rds_storage_types_test.go
flexibleengine/acceptance/resource_flexibleengine_rds_backup_test.go
flexibleengine/acceptance/resource_flexibleengine_rds_cross_region_backup_strategy_test.go
flexibleengine/acceptance/resource_flexibleengine_rds_instance_v3_test.go
flexibleengine/acceptance/resource_flexibleengine_rds_sql_audit_test.go
flexibleengine/provider.go

import RDSresource, unit test and document.
fixes #xxx
```release-note
```
```
=== RUN   TestAccBackup_mysql_basic
=== PAUSE TestAccBackup_mysql_basic
=== CONT  TestAccBackup_mysql_basic
--- PASS: TestAccBackup_mysql_basic (1185.01s)
PASS
coverage: 2.1% of statements in ../../../terraform-provider-flexibleengine/...
=== RUN   TestAccBackup_sqlserver_basic
=== PAUSE TestAccBackup_sqlserver_basic
=== CONT  TestAccBackup_sqlserver_basic
--- PASS: TestAccBackup_sqlserver_basic (1931.04s)
PASS
coverage: 1.9% of statements in …
```

feat(RDS): import RDS resource, unit test and document.

---

docs/data-sources/vpc_subnets.md
docs/data-sources/vpcs.md
flexibleengine/acceptance/acceptance.go
flexibleengine/acceptance/data_source_flexibleengine_vpc_subnets_test.go
flexibleengine/acceptance/data_source_flexibleengine_vpcs_test.go
flexibleengine/provider.go

add vpc resources/data sources for flexibleengine, including vpc_subnets, vpcs
fixes #xxx
```
vpc_subnets
=== RUN   TestAccVpcSubnetsDataSource_basic
=== PAUSE TestAccVpcSubnetsDataSource_basic
=== CONT  TestAccVpcSubnetsDataSource_basic
--- PASS: TestAccVpcSubnetsDataSource_basic (147.13s)
PASS
```
```
vpcs 
=== RUN   TestAccVpcsDataSource_basic
=== PAUSE TestAccVpcsDataSource_basic
=== CONT  TestAccVpcsDataSource_basic
--- PASS: TestAccVpcsDataSource_basic (163.35s) …
```

feat(vpc): import vpc resource and add unit test and docs

---

docs/data-sources/account.md
docs/data-sources/identity_projects.md
flexibleengine/acceptance/data_source_flexibleengine_account_test.go
flexibleengine/acceptance/data_source_flexibleengine_identity_projects_test.go
flexibleengine/acceptance/data_source_flexibleengine_obs_bucket_object_test.go
flexibleengine/provider.go

import `data_source_flexibleengine_account` resource, unit test and document
fixes #xxx
‍‍```release-note
‍‍```
```
data_source_flexibleengine_account
=== RUN   TestAccDatasourceAccount_basic
=== PAUSE TestAccDatasourceAccount_basic
=== CONT  TestAccDatasourceAccount_basic
--- PASS: TestAccDatasourceAccount_basic (36.26s)
PASS
```
```
data_source_flexibleengine_identity_projects
=== RUN   TestAccIdentityProjectsDataSource_basic
=== PAUSE …
```

feat(IAM): import IAM resource, unit test and document.

---

docs/data-sources/networking_port.md
docs/data-sources/vpc_peering_connection_v2.md
docs/data-sources/vpc_route_ids_v2.md
docs/data-sources/vpc_route_v2.md
docs/data-sources/vpc_subnet_ids_v1.md
docs/data-sources/vpc_subnet_v1.md
docs/data-sources/vpc_v1.md
docs/data-sources/vpcep_endpoints.md
docs/data-sources/vpcep_public_services.md
docs/resources/networking_secgroup_rule_v2.md
docs/resources/networking_secgroup_v2.md
docs/resources/vpc_flow_log_v1.md
docs/resources/vpc_peering_connection_accepter_v2.md
docs/resources/vpc_peering_connection_v2.md
docs/resources/vpc_route_v2.md
docs/resources/vpc_subnet_v1.md
docs/resources/vpc_v1.md
docs/resources/vpcep_approval.md
docs/resources/vpcep_endpoint.md
docs/resources/vpcep_service.md

docs: fix docs of vpc_v1

---

docs/data-sources/rds_sqlserver_collations.md
flexibleengine/acceptance/data_source_flexibleengine_rds_sqlserver_collations_test.go
flexibleengine/provider.go

fixes #xxx
```release-note
```
```
=== RUN   TestAccDatasourceSQLServerCollations_basic
=== PAUSE TestAccDatasourceSQLServerCollations_basic
=== CONT  TestAccDatasourceSQLServerCollations_basic
--- PASS: TestAccDatasourceSQLServerCollations_basic (25.66s)
PASS
```

feat(RDS): add a data source to get the list of RDS SQLServer collations

---

docs/data-sources/smn_message_templates.md
flexibleengine/acceptance/data_source_flexibleengine_smn_message_templates_test.go
flexibleengine/provider.go

… document.
fixes #xxx
```release-note
```
```
=== RUN   TestAccDatasourceSmnMessageTemplates_basic
=== PAUSE TestAccDatasourceSmnMessageTemplates_basic
=== CONT  TestAccDatasourceSmnMessageTemplates_basic
--- PASS: TestAccDatasourceSmnMessageTemplates_basic (83.26s)
PASS
```

feat(SMN): add a data source to get the list of SMN message templates

---

docs/data-sources/css_flavors.md
docs/data-sources/smn_message_templates.md
flexibleengine/acceptance/data_source_flexibleengine_css_flavors_test.go
flexibleengine/provider.go

import `data_source_flexibleengine_css_flavors` resource, unit test and document.
fixes #xxx
```release-note
```
```
...
=== RUN   TestAccCssFlavorsDataSource_basic
=== PAUSE TestAccCssFlavorsDataSource_basic
=== CONT  TestAccCssFlavorsDataSource_basic
--- PASS: TestAccCssFlavorsDataSource_basic (57.14s)
PASS
=== RUN   TestAccCssFlavorsDataSource_all
=== PAUSE TestAccCssFlavorsDataSource_all …
```

feat(CSS): import CSS resource, unit test and document.

---

docs/data-sources/dds_instances.md
docs/resources/dds_audit_log_policy.md
docs/resources/dds_backup.md
docs/resources/dds_parameter_template.md
flexibleengine/acceptance/data_source_flexibleengine_dds_instances_test.go
flexibleengine/acceptance/resource_flexibleengine_dds_audit_log_policy_test.go
flexibleengine/acceptance/resource_flexibleengine_dds_backup_test.go
flexibleengine/acceptance/resource_flexibleengine_dds_parameter_template_test.go
flexibleengine/acceptance/resource_flexibleengine_rds_backup_test.go
flexibleengine/provider.go

import `resource_flexibleengine_dds_parameter_template`, `flexibleengine_dds_audit_log_policy`, `flexibleengine_dds_backup`, `flexibleengine_dds_instances` resource, unit test and document
fixes #xxx
```release-note
```
```
=== RUN   TestAccDdsParameterTemplate_basic
=== PAUSE TestAccDdsParameterTemplate_basic
=== CONT  TestAccDdsParameterTemplate_basic
--- PASS: TestAccDdsParameterTemplate_basic (98.42s)
PASS
=== RUN   TestAccDdsParameterTemplate_shared_basic
=== …
```

feat(DDS): import DDS resource, unit test and document.

---

docs/data-sources/apig_groups.md
flexibleengine/acceptance/data_source_flexibleengine_apig_groups_test.go
flexibleengine/provider.go

fixes #xxx
```release-note
```
```
=== RUN   TestAccGroupsDataSource_basic
=== PAUSE TestAccGroupsDataSource_basic
=== CONT  TestAccGroupsDataSource_basic
--- PASS: TestAccGroupsDataSource_basic (483.51s)
PASS
=== RUN   TestAccGroupsDataSource_filterById
=== PAUSE TestAccGroupsDataSource_filterById
=== CONT  TestAccGroupsDataSource_filterById
--- PASS: TestAccGroupsDataSource_filterById (611.85s)
PASS
=== RUN   TestAccAppcode_basic
=== PAUSE TestAccAppcode_basic
=== CONT  TestAccAppcode_basic
--- PASS: TestAccAppcode_basic (492.03s)
PASS
=== RUN …
```

feat(apig): add apig_groups data source

---

docs/data-sources/dcs_templates.md
flexibleengine/acceptance/data_source_flexibleengine_dcs_templates_test.go
flexibleengine/provider.go

add DCS templates data source, unit test and document.
fixes #xxx
```release-note
```
```
=== RUN   TestAccDatasourceTemplates_basic
=== PAUSE TestAccDatasourceTemplates_basic
=== CONT  TestAccDatasourceTemplates_basic
--- PASS: TestAccDatasourceTemplates_basic (26.78s)
```

feat(DCS): add a data source to get the list of DCS templates

---

docs/resources/cbr_policy.md
flexibleengine/acceptance/resource_flexibleengine_cbr_policy_test.go

fixes #xxx
```release-note
```
```
=== RUN   TestAccCBRV3Policy_basic
=== PAUSE TestAccCBRV3Policy_basic
=== CONT  TestAccCBRV3Policy_basic
--- PASS: TestAccCBRV3Policy_basic (40.89s)
PASS
coverage: 1.6% of statements in ../../../terraform-provider-flexibleengine/...
```
```
=== RUN   TestAccCBRV3Policy_retention
=== PAUSE TestAccCBRV3Policy_retention
=== CONT  TestAccCBRV3Policy_retention
--- PASS: TestAccCBRV3Policy_retention (39.38s)
PASS
coverage: 1.6% of statements in ../../../terraform-provider-flexibleengine/...
```
```
=== RUN …
```

docs(cbr): add some fields for CBR

---

docs/resources/obs_bucket.md
flexibleengine/resource_flexibleengine_obs_bucket.go
flexibleengine/resource_flexibleengine_obs_bucket_test.go

fixes #1112 
```release-note
```
```
$ make testacc TEST="./flexibleengine" TESTARGS="-run TestAccObsBucket_basic"
=== PAUSE TestAccObsBucket_basic
=== CONT  TestAccObsBucket_basic
--- PASS: TestAccObsBucket_basic (104.81s)
PASS
ok      github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/flexibleengine 104.864s
$ make testacc TEST="./flexibleengine" TESTARGS="-run …
```

feat(obs/bucket): support kms_key_project_id and logging agency params
